### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by Qazy147** [rcmaehl/WhyNotWin11#101]
[0405.lang.txt](https://github.com/rcmaehl/WhyNotWin11/files/6724402/0405.lang.txt)

**Comment by Qazy147** [comment]
Sorry, i have no idea, how to upload new translation other than this way.
[0405.lang.txt](https://github.com/rcmaehl/WhyNotWin11/files/6733856/0405.lang.txt)

**Comment by micwoj92** [comment]
@Qazy147  Is it update? You can go to https://github.com/rcmaehl/WhyNotWin11/blob/main/Langs/0405.lang

then click on edit 
![image](https://user-images.githubusercontent.com/45581170/123833104-4e341780-d906-11eb-9ea3-16e1c0f15234.png)

And paste your translation. Then GitHub should make PR from that. Will make much easier to review, thanks.

**Comment by Qazy147** [comment]
Yes, it is update and mainly code page change. I will try to do it by direct editing.
