### ISSUE TITLE
Slovak translation

### ISSUE THREAD

**Issue by sebkopal** [rcmaehl/WhyNotWin11#102]
041B  |  sk-SK  |  Slovak - Slovakia
[041B.lang.txt](https://github.com/rcmaehl/WhyNotWin11/files/6724485/041B.lang.txt)

**Comment by Qazy147** [comment]
Zdravím, zkoušel jste ten překlad použít? Já překládal do češtiny a pokud jsem to udělal v UTF-8, bylo to rozbité. Po převodu na Latin 2 to bylo OK, tak nevím, jestli někde nedělám chybu.

**Comment by sebkopal** [comment]
SK
Zdravím, žiaľ nie. Môj systém bol nainštalovaný v anglickom jazyku. Takže vždy mi zobrazí angličtinu, pokiaľ je v programe nastavené, že zobrazí jazyk v ako je systém, tak to nemám šancu vyskúšať. Stiahol som si DEV verziu a pomocou porovnávania som preložil anglické názvy do slovenčiny.

EN
Greetings, unfortunately not. My system was installed in English language. So it will always show me English, if this app has set detection which language is set for system, so I don't have a chance to test it. I downloaded DEV version and I translated it by comparing English text to Slovak text.

**Comment by micwoj92** [comment]
Thank you for translation, feel free to submit later patches if you find something wrong.
