### ISSUE TITLE
For New Buyers (Discussion, Not a Complaint)

### ISSUE THREAD

**Issue by kamleshrao** [rcmaehl/WhyNotWin11#103]
First of all, this is a FANTASTIC tool which helps us to provide details on our existing Computers/Laptops.

When a new person want to buy a laptop online (e.g. Amazon, NewEgg), it is difficult for end-users / consumers to find such technical information in the Product Details.  

What is the best way to bring awareness to Microsoft or Hardware vendors to add such details on the Online Shopping websites (Tech Specs section)?  

In the earlier version of Windows, I had faced this challenge for Intel Virtualization / Intel VTd support and now with Win11 its about SecureBoot and TPM.

**Comment by billysielu** [comment]
As Windows 11 awareness increases they'll all have marketing campaigns like "Windows 11 Ready" or similar.
Until then, you'd just have to email the vendors.
