### ISSUE TITLE
Do not hardcode system drive letter

### ISSUE THREAD

**Issue by dournois** [rcmaehl/WhyNotWin11#111]
I'm not using C: drive but E: drive as system, which causes GPT and left storage tests to fail.
![image](https://user-images.githubusercontent.com/86596058/123606266-04133f00-d7fd-11eb-950a-24100f9e2210.png)
![image](https://user-images.githubusercontent.com/86596058/123606494-3b81eb80-d7fd-11eb-92f4-99ffbb10b2e5.png)
![image](https://user-images.githubusercontent.com/86596058/123606828-974c7480-d7fd-11eb-9c3c-40cb23c4edbe.png)

**Comment by dournois** [comment]
`Get-Partition -DriveLetter $env:SystemDrive | Get-Disk | Select-Object -Property PartitionStyle | Out-File -FilePath out.txt ` seems to produce an out.txt with the following output

PartitionStyle
--------------
GPT     

It looks like the way to go

**Comment by Qazy147** [comment]
Missing piece of command:
RunWait("**powershell -Command** Get-Partition -DriveLetter $env:SystemDrive | Get-Disk | Select-Object -Property PartitionStyle | Out-File -FilePath " & $hFile, "", @SW_HIDE)

**Comment by rcmaehl** [comment]
> Missing piece of command:
> RunWait("**powershell -Command** Get-Partition -DriveLetter $env:SystemDrive | Get-Disk | Select-Object -Property PartitionStyle | Out-File -FilePath " & $hFile, "", @SW_HIDE)

Fixed, thank you
