### ISSUE TITLE
CPU Compatibility

### ISSUE THREAD

**Issue by jukebox1001** [rcmaehl/WhyNotWin11#118]
I suppose, most of us understand red and green... but what about amber? Does it mean fail or pass? ;)

And what what's the difference between amber with "!" and amber with "?"

**Comment by Sumitdhiman** [comment]
Guess that means May or may not work, like 7th gen - meets all requirements, but the CPU is not on the compatibility list.

**Comment by jukebox1001** [comment]
Yeah... but what's the difference in the legend? Like a Ryzen 1800X or Pentium 4415Y return amber with an exclamation mark, and then I get amber with a question mark from a Core 2 Extreme X9770.

**Comment by rcmaehl** [comment]
Better indication of this is coming later today with 2.2.5
