### ISSUE TITLE
Additional requirements from Hardware Requirements PDF

### ISSUE THREAD

**Issue by Mixaill** [rcmaehl/WhyNotWin11#119]
https://download.microsoft.com/download/7/8/8/788bf5ab-0751-4928-a22c-dffdc23c27f2/Minimum%20Hardware%20Requirements%20for%20Windows%2011.pdf

there are some additional requirements in the PDF, like

* Bluetooth
   * must comply >=4.0 specification
   * adapter is required for `SMBios enclosure_type != 0x03 (Desktop)` ([additional info, ChassisType array)](https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-systemenclosure) 
* CPU
   * x86: PAE, NX, SSE4.1, CMPXCHG16b, LAHF/SAHF, and PrefetchW support
   * arm64: atomic instructions support  ([additional info](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-isprocessorfeaturepresent))
* Connectivity
   * at least one network adapter (Ethernet or WiFi) is required 
* Display
   * screen must be >=9" if `enclosure_type != desktop`
   * screen native resolution must be 1280x720 at least
   * at least one video output port is required
   * output image must be 8 bit per channel (or 6+2 with FRC) at least 
* Touchpad
   * if exists, must support precision touchpad 
* TPM
   * is not required for OEMs in some cases
* Thunderbolt/USB4
   * Memory Access Protection must be supported ([additional info](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-kernel-dma-protection))
* UEFI
  * must comply UEFI >=2.3.1 specification
* USB
   * at least one port is required 
* Storage
  * non-rotational drive (SSD in other words) is highly recommended

**Comment by micwoj92** [comment]
@rcmaehl Should be added to readme as todo? Then it could be closed.

**Comment by micwoj92** [comment]
Closing, same things (linked pdf) were discussed in #136 and it got more activity.
