### ISSUE TITLE
RAM amount is shown incorrectly when using wine.

### ISSUE THREAD

**Issue by micwoj92** [rcmaehl/WhyNotWin11#12]
This is probably out of scope, I have 9933MB of RAM at my disposal.
It probably also includes swap, because it would be 18125 for me.
So it is possibly related to #6, I guess?
![image](https://user-images.githubusercontent.com/45581170/123434487-d3e55980-d5cc-11eb-945a-bf4a4c8cf787.png)

**Comment by namazso** [comment]
this is most likely just wine lying like it does in many aspects. why woudl you want to run this under wine in the first place

**Comment by micwoj92** [comment]
> this is most likely just wine lying like it does in many aspects.

I don't think that reporting ram+swap as one in counted as lying. I will test it later on 2nd pc just to confirm.

> why woudl you want to run this under wine in the first place

I do not own any machines with Windows.

**Comment by rcmaehl** [comment]
Won't fix. Wine reports swap as physical RAM. Also, you're not going to be installing Windows 11 on Wine anyway

**Comment by micwoj92** [comment]
Ok, closing then. I guess that most of "Linux people" don't have desire to run windows on bare metal anyway.
