### ISSUE TITLE
Added Simplified Chinese support 

### ISSUE THREAD

**Issue by hulovexu1314** [rcmaehl/WhyNotWin11#126]
Code 0004.lang
Chinese(Simplified)

[MetaData]
Language=Chinese(Simplified)China
Translator=DSQH
Version=2.2.4.0
[Strings]
Donate=捐赠
Check for Updates=检查更新
Your Windows 11 Compatibility Results are Below=你的系统兼容 Windows 11 结果如下
Now Reach WhyNotWin11 via https://www.whynotwin11.org/= 通过 https://www.whynotwin11.org 了解更多
Results Based on Currently Known Requirements!=检测的结果根据已知系统的需求得出!
Translation by=翻译由
Architecture (CPU + OS)=架构
Boot Method=系统启动方式
CPU Compatibility=CPU 兼容性
CPU Core Count=CPU核心
CPU Frequency=CPU 频率
DirectX + WDDM2=DirectX支持 + WDDM2
Disk Partition Type=磁盘分区类型
RAM Installed=电脑内存
Secure Boot=安全启动
Storage Available=可用磁盘空间
TPM Version=TPM版本
Checking...=检查中...
64 Bit CPU=64 位CPU
64 Bit OS=64位操作系统
32 Bit CPU=32 位CPU
32 Bit OS=32位操作系统
Unable to Determine=无法确定 
Unable to Check List=无法检查列表
Error Accessing List=错误访问列表
Not Currently Listed as Compatible=目前未被列为兼容
Listed as Compatible=列为兼容 
Cores=核心
Threads=线程 
GPT Detected=检测到 GPT
GPT Not Detected=未检测到 GPT
Enabled=已启用
Supported=支持
Not Supported=不支持
Disabled / Not Detected=已禁用 或 未检测到
Drive(s) Meet Requirements=驱动条件满足要求
TPM Missing / Disabled=TPM 未安装或禁用 
Detected=检测到
DirectX 12 and WDDM 3=DirectX 12 和 WDDM 3
DirectX 12 and WDDM 2=DirectX 13 和 WDDM 2
No DirectX 12, but WDDM2=没有 DirectX12，但有WDDM2
DirectX 12, but no WDDM2=有 DirectX12，没有WDDM2
No DirectX 12 or WDDM2=没有 DirectX12 或 WDDM2
Test Build?=测试版本?
You're running a newer build than publically available!=你正在运行的是未发行的版本！
Up to Date=最新更新
You're running the latest build!=你运行的是最新版本!
Unable to Check for Updates=检查更新失败
Unable to load release data.=载入发行资料失败.
Invalid Data Received!=接受数据失败！
Invalid Release Tags Received!=接收到的发行标签无效！
Invalid Release Types Received!=接收到的发行类型无效！
Update Available=有新版本可用!
An Update is Availabe, would you like to download it?=有新版本可使用，您要下载吗？

**Comment by micwoj92** [comment]
Closing, language already added.
