### ISSUE TITLE
UEFI not detected in Windows 7.

### ISSUE THREAD

**Issue by Kiki79250CoC** [rcmaehl/WhyNotWin11#127]
My Windows 7 installation is UEFI, but the program cannot detect UEFI BIOS as you can see in the following Image ↓.
Alongside with this, the GPT disk type is also not recognized correctly.

![Windows 7](https://user-images.githubusercontent.com/54137141/123643729-fbcefa00-d824-11eb-9032-2a6b2d16189a.PNG)

**Comment by htcfreek** [comment]
Can you please check the output of `$PSVersionTable` in your PowerShell.

_To open Powershell press `Win+R`, type `powershell.exe` and press enter.

**Comment by Kiki79250CoC** [comment]
Sure !
![image](https://user-images.githubusercontent.com/54137141/123663863-19a55a80-d837-11eb-9cc6-0ed1fb2113fe.png)

**Comment by htcfreek** [comment]
@rcmaehl 
- The uefi variabel is introduced on Windows 8 first.
- The Powershell commandlets for disk management are not suppoerted on Win7. WMF 5.1 is required for these commandlets.

**Comment by rcmaehl** [comment]
@htcfreek Might add minimum requirements. Windows 7 is not supported by MS and I really shouldn't be supporting it either, I may add bcdedit though as a non-powershell backup for those on non-english builds having powershell issues.

**Comment by htcfreek** [comment]
> @htcfreek Might add minimum requirements. Windows 7 is not supported by MS and I really shouldn't be supporting it either, I may add bcdedit though as a non-powershell backup for those on non-english builds having powershell issues.

I have a non-english (german) build and no PowerShell issues.

**Comment by Kiki79250CoC** [comment]
Update : I just noticed than my PowerShell version is extremely old (2.0), so i'm currently downloading the version 7.1.3, which is surprisely still supported on 7.

So if the problem is, as you said it, from non english Windows Installations, I think than this error is "normal" for now.

**Comment by htcfreek** [comment]
> Update : I just noticed than my PowerShell version is extremely old (2.0), so i'm currently downloading the version 7.1.3, which is surprisely still supported on 7.
> 
> So if the problem is, as you said it, from non english Windows Installations, I think than this error is "normal" for now.

If you want to have a newer > version plz install `windows management Framework 5.1`

**Comment by Kiki79250CoC** [comment]
> If you want to have a newer > version plz install `windows management Framework 5.1`

It's installed. Thanks.

**Comment by htcfreek** [comment]
@rcmaehl 
This could help you: https://www.powershellgallery.com/packages/GetFirmwareBIOSorUEFI/1.1/Content/GetFirmwareBIOSorUEFI.psm1

**Comment by rcmaehl** [comment]
Won't fix, sorry. 😞
