### ISSUE TITLE
CPU error reporting Core count

### ISSUE THREAD

**Issue by AndrewRChapman** [rcmaehl/WhyNotWin11#128]
I have run this programme and got a green light on all counts, however when it reports the CPU Ryzen 3950X, it only shows 8 of 16 cores which are verified in the AMD Ryzen programme.
![ScreenShot_20210628141800](https://user-images.githubusercontent.com/54445303/123650806-d3de9700-d822-11eb-8c7b-6cdaa8a91276.png)

**Comment by rcmaehl** [comment]
Try the latest action build and let me know if it has the same issue: https://github.com/rcmaehl/WhyNotWin11/suites/3103560831/artifacts/70964083

**Comment by AndrewRChapman** [comment]
Hi, tried both the 64 and 32 bit versions of the latest version, with the same result. It gets the CPU ID correct but only reports 8 cores, 16 threads. It may have something to do with the way the 3950X works in that it can/does sleep banks of cores when not under load.

Politeness is priceless when received, cost nothing to own or give, yet some cannot afford.
 

    On Monday, 28 June 2021, 15:18:44 BST, Robert C. Maehl ***@***.***> wrote:  
 
 


Try the latest action build and let me know if it has the same issue: https://github.com/rcmaehl/WhyNotWin11/suites/3103560831/artifacts/70964083

**Comment by rcmaehl** [comment]
Odd, the results should be coming straight from Windows. Can you run

`wmic CPU Get NumberOfCores,NumberOfLogicalProcessors /Format:List` in command prompt

![image](https://user-images.githubusercontent.com/716581/123657650-fa8ad680-d7fe-11eb-8038-92ebbc7dcc77.png)

**Comment by rcmaehl** [comment]
I've been unable to reproduce with another person with a 3950X

![image](https://user-images.githubusercontent.com/716581/123670314-16947500-d80b-11eb-914d-84fc12694bbe.png)

Verify that Windows is reporting the correct amount of Cores and Processors, You may need to set/unset Number of Processors in msconfig

![image](https://user-images.githubusercontent.com/716581/123670561-58bdb680-d80b-11eb-947c-5c4d5a234a0d.png)

Apparently it's not an unheard of issue

https://www.reddit.com/r/Amd/comments/eyh5y1/3950x_only_8_cores_in_hwinfo/
https://community.amd.com/t5/processors/8-core-ryzen-9-3950x/td-p/83146

**Comment by AndrewRChapman** [comment]
Hi,
This is from Settings: Device name ***************************Processor AMD Ryzen 9 3950X 16-Core Processor               3.49 GHzInstalled RAM 32.0 GBDevice ID ***************************************Product ID ***************************************System type 64-bit operating system, x64-based processorPen and touch No pen or touch input is available for this display
I have attached a variety of reports given from windows, which seems to give a lot of conflicting information and confusion about what is and isn't a core.


Politeness is priceless when received, cost nothing to own or give, yet some cannot afford.
 

    On Monday, 28 June 2021, 17:22:14 BST, Robert C. Maehl ***@***.***> wrote:  
 
 


Closed #128.
