### ISSUE TITLE
Error when 3.9 GB of RAM is used instead of 4.

### ISSUE THREAD

**Issue by Sumitdhiman** [rcmaehl/WhyNotWin11#13]
![613654b1-47a6-4a71-896e-919bda741fbb](https://user-images.githubusercontent.com/10372750/123436558-60ebdb00-d5ec-11eb-9895-6167a75e1f10.png)
I believe the 3.9 RAM is fine, but the tool doesnt agree.

**Comment by bl-ue** [comment]
From https://www.microsoft.com/en-us/windows/windows-11

> Memory: 4 GB RAM

😞

**Comment by Sumitdhiman** [comment]
I agree, but I wonder what happens with the real world scenario :)

**Comment by bl-ue** [comment]
Probably runs really slow, for one.

**Comment by micwoj92** [comment]
It probably still should work, if I remember correctly win8 had minimal 1GB, but it "works" with 512MB or even less.

**Comment by codeinteger6** [comment]
The tool is checking the wrong info, #6
