### ISSUE TITLE
General PowerShell-Script for all PS based checks

### ISSUE THREAD

**Issue by htcfreek** [rcmaehl/WhyNotWin11#132]
We should have a PowerShel-Skript for all check based on PowerShell which allows us to log errors. 

@rcmaehl 
I can create the script for you. But a small list of all necessary checks would be great to have.

# Checks
- [x] ~UEFI~ (#145)
- [x] ~SecureBoot~ (#144)
- [ ] GPT

# Option 1:
- The script is running at the start of WhyNotWin11 and generates an Ini with all check results.
- All errors and PS-Version will be logged.
- Results will be written into an Ini file. (-1 = Check failed.)

```
[Results]
Firmware=UEFI
PartitionSheme=GPT
...
```

# Option 2
- Script is started with a parameter that indicates what to check.
- All errors and PS-Version will be logged.
- Return code of script is the check result. (-1=failed, 100=not available, 101=available)

**Comment by htcfreek** [comment]
This could fix #93

**Comment by htcfreek** [comment]
Could be an solution for the localization problems

**Comment by rcmaehl** [comment]
@htcfreek Let me finish yoinking out the checks first. Should be easier for me to implement that then. If you want to start on a powershell script I'll add it in once it's complete.

**Comment by htcfreek** [comment]
> @htcfreek Let me finish yoinking out the checks first. Should be easier for me to implement that then. If you want to start on a powershell script I'll add it in once it's complete. I'd prefer option 1.

On option 1 we have to take care on the encoding. Which do you want?

**Comment by rcmaehl** [comment]
Ideally ASCII or ANSI. AutoIt and Unicode can be... needlessly difficult.

**Comment by micwoj92** [comment]
Unicode, I thinnk that's also reason for translations failing with things like umlauts.

**Comment by htcfreek** [comment]
I will add a param or var to later change that

**Comment by rcmaehl** [comment]
Added #144. Allows removal of admin rights, although I'm not sure if they're still needed for `-ExecutionPolicy Bypass`

**Comment by rcmaehl** [comment]
GPT may be able to be done using WMI somehow. I had my concerns somewhere though

**Comment by htcfreek** [comment]
> GPT may be able to be done using WMI somehow. I had my concerns somewhere though

Yes.You need win32_logicaldisks, win32_diskpartition and getenv("systemdrive").

**Comment by htcfreek** [comment]
Issue resolved by removing pwsh.
