### ISSUE TITLE
Processor Supported Still an exclamation Mark

### ISSUE THREAD

**Issue by vr513** [rcmaehl/WhyNotWin11#133]
I have Intel Core i5-7200U processor .It meets all the technical specifications.Still an exclamation mark is there .Will I be able to update to windows 11 ?
![image](https://user-images.githubusercontent.com/81068517/123667307-a6f8a700-d857-11eb-8dff-429d4f58d349.png)

**Comment by htcfreek** [comment]
You run an old version

**Comment by vr513** [comment]
Updated to 2.2.4.0 still a question mark is present . Will I be able to update to windows 11 ?
![image](https://user-images.githubusercontent.com/81068517/123670663-12904380-d85b-11eb-9fd2-46c811f238b6.png)

**Comment by micwoj92** [comment]
@vr513 It is not in the officially supported list, that's why. You can try latest prelease build (download artifact), contains some fixes

https://github.com/rcmaehl/WhyNotWin11/actions/runs/979639531
