### ISSUE TITLE
Windows Blogs: Update on Windows 11 minimum system requirements 

### ISSUE THREAD

**Issue by tonyunreal** [rcmaehl/WhyNotWin11#136]
https://blogs.windows.com/windows-insider/2021/06/28/update-on-windows-11-minimum-system-requirements/

Sounds like they are keeping an eye on whether the compatibility list should be expanded, especially with 7th gen Intel processors and 1th gen Ryzen processors, as the insider program goes on.

**Comment by tonyunreal** [comment]
> In support of the Windows 11 system requirements, we’ve set the bar for previewing in our Windows Insider Program to match the minimum system requirements for Windows 11, **with the exception for TPM 2.0 and CPU family/model.** By providing preview builds to the diverse systems in our Windows Insider Program, we will learn how Windows 11 performs across CPU models more comprehensively, informing any adjustments we should make to our minimum system requirements in the future.

The TPM / CPU model requirements won't be enforced for Insider builds. 

Maybe WhyNotWin11 should reflect this in the UI, like having a status prompt (fully compatible / partially compatible / not compatible), and offer a link to a beginner's guide to Windows Insider Program if the user's computer is partially compatible.

**Comment by rcmaehl** [comment]
If someone could get me a list of

- Insider Requirements
- 2023 Requirements (webcam, etc)

I'll see if I can get that implemented. WhyNotWin11 is only supposed to show release status but I'll add it in after the MAJOR bugs are taken care of ( #53 👀 )

**Comment by Vengirni** [comment]
Those 2023 requirements are available here: https://download.microsoft.com/download/7/8/8/788bf5ab-0751-4928-a22c-dffdc23c27f2/Minimum%20Hardware%20Requirements%20for%20Windows%2011.pdf

Those sound more like OEM's requirements rather than user's requirements.

**Comment by ParkoutV** [comment]
It would be better to add some check for SSE4.1 features - Here's the reason
![image](https://user-images.githubusercontent.com/51396052/123687101-7b8faf80-d88b-11eb-9913-99d331f24d93.png)

As you can see, even though others are ignorable since that have been required for Windows 10 - but SSE4.1 is the new requirement of it.

Original Source : https://download.microsoft.com/download/7/8/8/788bf5ab-0751-4928-a22c-dffdc23c27f2/Minimum%20Hardware%20Requirements%20for%20Windows%2011.pdf

**Comment by PierreGrillet** [comment]
From the same document : 
![image](https://user-images.githubusercontent.com/34492324/123690943-4bc5b500-d855-11eb-9e3d-446588dc57b2.png)

It seems that this document is only a guide line to the patterns / OEM as @Vengirni said.
My understanding is that Microsoft want the new Windows 11 devices to match a minimum quality / feature set.
We can maybe add a optional check (not red), but without further information I don't see this as a user requirement.

**Comment by PierreGrillet** [comment]
The complete specification (looks like it) is here https://go.microsoft.com/fwlink/?linkid=2166396
(If not been posted or mentioned before)

**Comment by PierreGrillet** [comment]
Microsoft published a [post](https://blogs.windows.com/windows-insider/2021/06/28/update-on-windows-11-minimum-system-requirements/)

**Comment by micwoj92** [comment]
So is there anything specific that can be added to checks? Otherwise I think this issue could be closed.

**Comment by micwoj92** [comment]
No response for a week and this "issue" is really general, so I will close it. There are already several open issues for adding specific checks and couple for improving existing ones. https://github.com/rcmaehl/WhyNotWin11/issues?q=is%3Aopen+is%3Aissue+label%3Achecks
