### ISSUE TITLE
malicious in WhyNotWin11.exe

### ISSUE THREAD

**Issue by hlogit** [rcmaehl/WhyNotWin11#137]
hi,
i downloaded the WhyNotWin11.exe hasg: 84b818bf3c06297fb59306bfde8a7afa2d3564483bac7b85ae8f0a4212bc7367
virustotal shows 3 security vendors flagged this file as malicious
same as in my build by WhyNotWin11.aus
is it safe to go?
thanks

**Comment by micwoj92** [comment]
Autoit executables often get false positives. Future releases are planned to be released from CI, which also produces shasums. Also check out #59
