### ISSUE TITLE
Results differ based on logged in user

### ISSUE THREAD

**Issue by Scrotos** [rcmaehl/WhyNotWin11#140]
This is on a domain joined Win10 21H1 machine.  Dell Latitude 7400.  

Non-admin user:

![image](https://user-images.githubusercontent.com/80605830/123685726-3aa48600-d80c-11eb-92ac-6e95c1d4bc45.png)

Admin user (domain admin):

![image](https://user-images.githubusercontent.com/80605830/123685980-85260280-d80c-11eb-8889-cacc0e4ee0d5.png)

I checked in the BIOS and Secure Boot is enabled so I'm not sure what specific test is failing with that.  Even stranger is that the domain admin couldn't determine GPT as I would have guessed a user with more limited access would have had a problem like that.

**Comment by rcmaehl** [comment]
It shouldn't be allowing the program to run without admin rights. Anyway, some of these may be known issues, please try the latest action build:

https://github.com/rcmaehl/WhyNotWin11/suites/3105887685/artifacts/71037202

**Comment by Scrotos** [comment]
As my admin.  Also of interest was that this is the second run, the first one gave an error about being unable to retrieve the CPU compatibility list.  Running again cleared up whatever connection issue that was.

![image](https://user-images.githubusercontent.com/80605830/123688861-c9ff6880-d80f-11eb-9e69-18160290e9da.png)

**Comment by rcmaehl** [comment]
> As my admin. Also of interest was that this is the second run, the first one gave an error about being unable to retrieve the CPU compatibility list. Running again cleared up whatever connection issue that was.

I'll look into the CPU list issue. It looks like the 3 checks that are having issues are all currently powershell command based. Do you have any GP restrictions on powershell commands?

**Comment by rcmaehl** [comment]
Fixed next release, admin rights not required anymore thanks to recent changes and to help with batch deployment.
