### ISSUE TITLE
Secureboot: Use regedit

### ISSUE THREAD

**Issue by htcfreek** [rcmaehl/WhyNotWin11#144]
`HKEY_LOCAL_MACHINE \ System \ CurrentControlSet \ Control \ SecureBoot \ State`

We should replace PowerShell where possible

**Comment by rcmaehl** [comment]
Added. Allows removal of admin rights, although I'm not sure if they're still needed for `-ExecutionPolicy Bypass`

**Comment by htcfreek** [comment]
> Added. Allows removal of admin rights, although I'm not sure if they're still needed for `-ExecutionPolicy Bypass`

Novadmin rights not needed for execution policy. because you don't change setting. you only overwrite it for the running PowerShell instance.

**Comment by htcfreek** [comment]
@rcmaehl 
you have to fix case two and three which try to read the file

**Comment by Qazy147** [comment]
Secureboot detection no longer works correctly. It looks like mix `RegRead` and `FileRead($hFile)`.

I suggest this:
```
    $sSecureBoot = RegRead("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecureBoot\State", "UEFISecureBootEnabled")
    If @error Then $sSecureBoot=999
    Switch $sSecureBoot
        Case 0
            GUICtrlSetData($hCheck[8][0], "0")
            GUICtrlSetBkColor($hCheck[8][0], 0xF4C141)
            GUICtrlSetData($hCheck[8][2], _Translate("Supported"))
        Case 1
            GUICtrlSetData($hCheck[8][0], "OK")
            GUICtrlSetBkColor($hCheck[8][0], 0x4CC355)
            GUICtrlSetData($hCheck[8][2], _Translate("Enabled"))
        Case Else
            GUICtrlSetData($hCheck[8][0], "X")
            GUICtrlSetBkColor($hCheck[8][0], 0xFA113D)
            GUICtrlSetData($hCheck[8][2], _Translate("Disabled / Not Detected"))
    EndSwitch

```

**Comment by rcmaehl** [comment]
> Secureboot detection no longer works correctly. It looks like mix `RegRead` and `FileRead($hFile)`.
> 
> I suggest this:
> 
> ```
>     $sSecureBoot = RegRead("HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecureBoot\State", "UEFISecureBootEnabled")
>     If @error Then $sSecureBoot=999
>     Switch $sSecureBoot
>         Case 0
>             GUICtrlSetData($hCheck[8][0], "0")
>             GUICtrlSetBkColor($hCheck[8][0], 0xF4C141)
>             GUICtrlSetData($hCheck[8][2], _Translate("Supported"))
>         Case 1
>             GUICtrlSetData($hCheck[8][0], "OK")
>             GUICtrlSetBkColor($hCheck[8][0], 0x4CC355)
>             GUICtrlSetData($hCheck[8][2], _Translate("Enabled"))
>         Case Else
>             GUICtrlSetData($hCheck[8][0], "X")
>             GUICtrlSetBkColor($hCheck[8][0], 0xFA113D)
>             GUICtrlSetData($hCheck[8][2], _Translate("Disabled / Not Detected"))
>     EndSwitch
> ```

Did the commit not take?

![image](https://user-images.githubusercontent.com/716581/123704545-bf56ca80-d833-11eb-90cc-2c7ce085ff9a.png)

**Comment by rcmaehl** [comment]
I'll merge it in though.

**Comment by rcmaehl** [comment]
OH. I'm blindddddd
