### ISSUE TITLE
UEFI or Bios: Use AutoIt

### ISSUE THREAD

**Issue by htcfreek** [rcmaehl/WhyNotWin11#145]
We could replace PowerShell here with `GetEnv("...")`! 

_Note: This isn't available on Win7. Possible fallback would be to parse sysinfo32 export to txt._

**Comment by rcmaehl** [comment]
Which environment variable?

**Comment by htcfreek** [comment]
`firmware_type`

In your ps command you have `$env:firmwaretyp` and in Powershell `$env:` indicates it is an env var.

**Comment by htcfreek** [comment]
Btw: My idea for win7 doesn't work.
