### ISSUE TITLE
My GPU support DX12, tool show it's not

### ISSUE THREAD

**Issue by NinjaGamerow** [rcmaehl/WhyNotWin11#146]
As in title. My card is GTX 1070

**Comment by rcmaehl** [comment]
Can you open DXDIAG and Upload the files it makes from `Save All Information`?

**Comment by NinjaGamerow** [comment]
All right, that might was a bug, I run program few times and now it says no warning. Only "?" on CPU, Ryzen 5 1400. Once more time thanks for your reply!
