### ISSUE TITLE
Move GPU and CPU Names Elsewhere

### ISSUE THREAD

**Issue by red-ray** [rcmaehl/WhyNotWin11#147]
![WhyNotSpaceForAllTheGPUs](https://user-images.githubusercontent.com/25452387/123694612-7150bf80-d851-11eb-938d-43bc2f76ee20.png)

**Comment by rcmaehl** [comment]
I may just remove the CPU and GPU names out of the boxes to somewhere else.

**Comment by Qazy147** [comment]
Or maybe use something like this:
```
Func _GUICtrlSetDataAndTip($id, $data, $tip=$data)
    GUICtrlSetData($id, $data)
    GUICtrlSetTip($id, $tip)
EndFunc
```
And replace `GUICtrlSetData` by this function.
