### ISSUE TITLE
Scaling worse than ever in 2.2.5.0

### ISSUE THREAD

**Issue by jmwoods301** [rcmaehl/WhyNotWin11#149]
Practically unusable at 125%

**Comment by rcmaehl** [comment]
Please try: https://github.com/rcmaehl/WhyNotWin11/suites/3106654694/artifacts/71057812

**Comment by jmwoods301** [comment]
> 
> 
> Please try: https://github.com/rcmaehl/WhyNotWin11/suites/3106654694/artifacts/71057812

No change.

**Comment by jmwoods301** [comment]
![WNW11 Scaling Issue](https://user-images.githubusercontent.com/23463919/123702000-709b3780-d817-11eb-9de8-a360c938cac8.JPG)

**Comment by rcmaehl** [comment]
OH

**Comment by rcmaehl** [comment]
Please try: https://github.com/rcmaehl/WhyNotWin11/suites/3107344754/artifacts/71077864

**Comment by jmwoods301** [comment]
Built it on my system.

Looks much better.

![WNW11](https://user-images.githubusercontent.com/23463919/123706773-9297b880-d81d-11eb-9b6f-25d6e90bc174.JPG)
