### ISSUE TITLE
README Download zip

### ISSUE THREAD

**Issue by alexmajor** [rcmaehl/WhyNotWin11#150]
The download zip link 404s because it is pointing to the old main artifact.

**Comment by micwoj92** [comment]
Works for me

**Comment by alexmajor** [comment]
Clicking the link [downloading zip](https://codeload.github.com/rcmaehl/WhyNotWin11/zip/master) to https://codeload.github.com/rcmaehl/WhyNotWin11/zip/master
![image](https://user-images.githubusercontent.com/5017286/123698918-a72f7d00-d82c-11eb-9c8e-bc768f092421.png)

Leads to a 404.
![image](https://user-images.githubusercontent.com/5017286/123698938-ac8cc780-d82c-11eb-880b-0f75df6ac29f.png)

**Comment by micwoj92** [comment]
Ah this one. You meant source. Fixed.
