### ISSUE TITLE
TPM Version detection is not correct

### ISSUE THREAD

**Issue by ftamminga** [rcmaehl/WhyNotWin11#151]
My system uses fTPM, which is identified by the PC Health Check as a sufficient version. At least, PC Health Check says my PC is good for W11.
WhyNotWin11, however, rejects the TPM Version as Missing / Disabled.

**Comment by rcmaehl** [comment]
Microsoft has changed this a couple times. What version of health check are you running, and what version of TPM is being reported?

**Comment by red-ray** [comment]
It would be much simpler and more reliable to use **Tbsi_GetDeviceInfo()**

**Comment by jmwoods301** [comment]
> 
> 
> My system uses fTPM, which is identified by the PC Health Check as a sufficient version. At least, PC Health Check says my PC is good for W11.
> WhyNotWin11, however, rejects the TPM Version as Missing / Disabled.

Curious as to what Windows Security > Device Security displays...

windowsdefender://devicesecurity

**Comment by piru** [comment]
I have the same problem.

Here's what I see:
![amd-ftpm-device-security](https://user-images.githubusercontent.com/1134152/123709320-89d2d100-d875-11eb-8d7b-1fa5917af533.png)

![amd-ftpm](https://user-images.githubusercontent.com/1134152/123709180-4aa48000-d875-11eb-97be-8730c52ad0b4.png)

**Comment by tvdruten** [comment]
Did you try running the software as administrator? That seemed to work for me.

**Comment by piru** [comment]
@tvdruten

That appears to work with the TPM check, *but* also makes it fail "Disk Partition Type" check. "Disk Partition Type" check works when run as regular user.

So running as admin is clearly not a solution (nor is it listed as a requirement for this tool).

**Comment by rcmaehl** [comment]
@piru All 3 checks will be fixed in the next release. Working on a non-admin TPM check now, but yes, running as admin was supposed to be a requirement but broke, in a lot of domain environments especially

**Comment by rcmaehl** [comment]
Hi all,

Please give it a couple minutes to be uploaded and try https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

**Comment by ftamminga** [comment]
This latest version now detects TPM 2 correctly. Thanks!

And for the record:
![image](https://user-images.githubusercontent.com/6064650/123737953-31ff8e80-d8a4-11eb-8411-3b32851efde4.png)
