### ISSUE TITLE
Incorrect RAM result

### ISSUE THREAD

**Issue by samwatkinson1** [rcmaehl/WhyNotWin11#154]
RAM was reported as shown below:
![WhyNotWin11_(1)_DVL2I7lm7b](https://user-images.githubusercontent.com/41587235/123701965-736b4c00-d85a-11eb-9340-2e2dc2ef509a.png)
If I did have that many GB's of RAM im sure NASA would come knocking on my door ;)
Looks like a division issue, maybe bytes not being converted? Happy to elaborate on system specs and windows settings as applicable!

**Comment by rcmaehl** [comment]
What is your actual RAM amount? 15GB?

**Comment by samwatkinson1** [comment]
> What is your actual RAM amount? 15GB?

Nope 16GB, I have 2 8GB DIMMs in dual channel.

**Comment by rcmaehl** [comment]
> > What is your actual RAM amount? 15GB?
> 
> Nope 16GB, I have 2 8GB DIMMs in dual channel.

Can you send me a picture of your Memory Graph in Task Manager?
![image](https://user-images.githubusercontent.com/716581/123702635-61c17e80-d831-11eb-9d9e-46496a48422f.png)

**Comment by jmwoods301** [comment]
![Ram Count](https://user-images.githubusercontent.com/23463919/123702737-5c0b6f00-d818-11eb-9429-79d0d25e07aa.JPG)

**Comment by samwatkinson1** [comment]
> > > What is your actual RAM amount? 15GB?
> > 
> > 
> > Nope 16GB, I have 2 8GB DIMMs in dual channel.
> 
> Can you send me a picture of your Memory Graph in Task Manager?
> ![image](https://user-images.githubusercontent.com/716581/123702635-61c17e80-d831-11eb-9d9e-46496a48422f.png)

As below:
![Taskmgr_LJrV12jdJ5](https://user-images.githubusercontent.com/41587235/123702800-803c6f80-d85b-11eb-8e0c-2a4157c6ea14.png)

**Comment by rcmaehl** [comment]
Patched, forgot to math
