### ISSUE TITLE
Not showing full CPU details

### ISSUE THREAD

**Issue by btwaukegan** [rcmaehl/WhyNotWin11#155]
It's not displaying my full CPU line.  This can be corrected by widening the window to 900px and the field to 400px.
![image](https://user-images.githubusercontent.com/84921219/123703051-81ed3f80-d829-11eb-966e-69a4f78c80f1.png)
![image](https://user-images.githubusercontent.com/84921219/123703250-c1b42700-d829-11eb-8847-eda532a21849.png)

**Comment by micwoj92** [comment]
@rcmaehl duplicate #149 ?

**Comment by btwaukegan** [comment]
@micwoj92 Not quite.  I'm not doing any scaling, this is with text at 100%, so it is an issue with minimum field length.
A possible solution is to scale the text based on windows settings.

**Comment by micwoj92** [comment]
Oh sorry, the text looks huge compared to readme. Thought it's same...

**Comment by micwoj92** [comment]
Duplicate #147
