### ISSUE TITLE
GPT detection not working

### ISSUE THREAD

**Issue by Qazy147** [rcmaehl/WhyNotWin11#158]
Function `_GetDiskInfo` is no working correctly. Problem is (I think) in
`Local $Obj_WMIService = ObjGet('winmgmts:\\' & @ComputerName & '\root\cimv2\Security\MicrosoftTPM');`
it should be only
`Local $Obj_WMIService = ObjGet('winmgmts:\\' & @ComputerName & '\root\cimv2')`
and
`Return String($sType)`
should be
`Return StringLeft($sType,3)`

**Comment by rcmaehl** [comment]
Thank you. The check fails on my system regardless, so I would not have noticed.
