### ISSUE TITLE
CPU compatibility does not work correctly at the first start

### ISSUE THREAD

**Issue by iamtheRichie** [rcmaehl/WhyNotWin11#159]
Thanks for the great program 

it runs great only one thing I noticed

At the first start after several minutes CPU-Compatibility Checking... , no CPU and a yellow ? left

After I have closed the program once and restarted, my CPU is displayed

Windows 10 21 H1
Version(WhyNotWin11): 2.2.5.0

**Comment by rcmaehl** [comment]
Known issue. Will be fixed with next release. 2.2.5 was supposed to be marked as a pre-release
