### ISSUE TITLE
Secure Boot Disabled / Not Detected while msinfo32 says its enabled

### ISSUE THREAD

**Issue by tvdruten** [rcmaehl/WhyNotWin11#160]
My msinfo32 says secure boot is enabled. Though WhyNotWin11 says its Disabled / Not Detected

![secure boot](https://user-images.githubusercontent.com/77735024/123712852-74f53e00-d873-11eb-85ac-e272e26a6237.jpg)

**Comment by rcmaehl** [comment]
Are you running 2.2.5 from Releases or https://github.com/rcmaehl/WhyNotWin11/actions?

**Comment by tvdruten** [comment]
> 
> 
> Are you running 2.2.5 from Releases or https://github.com/rcmaehl/WhyNotWin11/actions?

From release

**Comment by rcmaehl** [comment]
Please try the latest action. A lot of bugs have been fixed by moving away from Powershell

**Comment by tvdruten** [comment]
Haha I compiled like an hour ago. I see .6 version is there. I just tested it and you nailed it ^^

![fixed](https://user-images.githubusercontent.com/77735024/123713550-f26d7e00-d874-11eb-83c6-bc05466b9459.jpg)
