### ISSUE TITLE
Running non-elevated does not detect TPM

### ISSUE THREAD

**Issue by tvdruten** [rcmaehl/WhyNotWin11#161]
If I run WhyNotWin11 non-elevated TPM is not recognized. 

![tpm](https://user-images.githubusercontent.com/77735024/123713123-05cc1980-d874-11eb-9858-40813715b429.jpg)

**Comment by tvdruten** [comment]
Just retested on 2.2.6.0 and issue remains in that version

Non elevated:
![non elevated](https://user-images.githubusercontent.com/77735024/123713688-3ceefa80-d875-11eb-8a3e-72c9a1ea14ab.jpg)



Elevated:
![fixed](https://user-images.githubusercontent.com/77735024/123713694-40828180-d875-11eb-98ff-941b72ef437e.jpg)

**Comment by rcmaehl** [comment]
There has to be some way to get this without admin rights

**Comment by tvdruten** [comment]
> 
> 
> There has to be some way to get this without admin rights

If thats not possible not: maybe just put the message at TPM Version to "Run as administrator required" when its not ran as admin

**Comment by rcmaehl** [comment]
> > There has to be some way to get this without admin rights
> 
> If thats not possible not: maybe just put the message at TPM Version to "Run as administrator required" when its not ran as admin

Absolutely agree

**Comment by tvdruten** [comment]
Left side is non-elevated, right side is elevated.
So that wont work

![image](https://user-images.githubusercontent.com/77735024/123714117-036abf00-d876-11eb-99e2-b37928a4eaf4.png)

**Comment by rcmaehl** [comment]
Yeah, currently looking into registry values and checking devices. If I can see it exists without admin rights using device manager, I should be able to do it someway

**Comment by tvdruten** [comment]
Also sad news

![image](https://user-images.githubusercontent.com/77735024/123714273-47f65a80-d876-11eb-9e05-a30ea864dbe2.png)

**Comment by rcmaehl** [comment]
@tvdruten 

Please give it a couple minutes to be uploaded and try https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

**Comment by tvdruten** [comment]
> 
> 
> @tvdruten
> 
> Please give it a couple minutes to be uploaded and try https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip


Seems to work now
