### ISSUE TITLE
CPU Compatibility, unable to check list.

### ISSUE THREAD

**Issue by naobug** [rcmaehl/WhyNotWin11#167]
Why is the CPU Compatibility staying yellow and the "checking..." status isn't changing?
A mouse-over reveals "unable to check list"

Does it mean, the List is offline?
![CheckCPUList](https://user-images.githubusercontent.com/12033198/123717336-eb4a6e00-d87c-11eb-9695-077b1bc942a2.jpg)

**Comment by micwoj92** [comment]
Known bug, please check latest dev build. Link is in readme. if issue persists then comment.
