### ISSUE TITLE
Question: TPM Status

### ISSUE THREAD

**Issue by tobidwest** [rcmaehl/WhyNotWin11#17]
If WhyNotWin11 shows the TPM status "TPM Not Activated", does this mean that there actually is one that can be activated? I checked my BIOS but can find an option to activate a TPM.

**Comment by Masamune3210** [comment]
Who made your board, are you Intel or AMD, might be able to help you find it if it exists

**Comment by hong620** [comment]
it's depends on Intel/AMD Vender and mainboard manufactors that named TPM related setting in firmware menu.

try check the motherboard name and check the manual PDF file from manufactor website.

as i've known recent AMD Zen mobo and processor would just okay with activate fTPM.

**Comment by tobidwest** [comment]
Thank you for your help. I have an Intel Xeon E5-2689 0 as CPU that is on a [X79M-S](https://de.aliexpress.com/i/4000632164218.html) motherboard. Unfortunately, I wasn't able to find a manual for the motherboard for it's from a small company and very unknown.

**Comment by tobidwest** [comment]
In the [CPU's manual](https://www.intel.com/content/dam/www/public/us/en/documents/datasheets/xeon-e5-v2-datasheet-vol-1.pdf) I found that it does come with something called "Intel Trusted Execution Technology". But I'm not sure if that's the same as a TPM and how to enable it.
