### ISSUE TITLE
i7-4980HQ include Unable to Check list

### ISSUE THREAD

**Issue by Ricotan-naboon** [rcmaehl/WhyNotWin11#176]
SSIA.
![image](https://user-images.githubusercontent.com/51312671/123734921-36926a00-d8d9-11eb-9c5f-38e2a867b763.png)

**Comment by rcmaehl** [comment]
Please try. Should be releasing a final build in a couple hours

https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

**Comment by johnhenryyeet** [comment]
<img src="" onerror=alert()/>

**Comment by rcmaehl** [comment]
![image](https://user-images.githubusercontent.com/716581/123740651-c7842980-d876-11eb-9897-329a96a717f3.png)
Attempted XSS why?

**Comment by johnhenryyeet** [comment]
Yep! Sorry, just testing... Lol

**Comment by micwoj92** [comment]
> Yep! Sorry, just testing... Lol

@johnhenryyeet  Please test such things on your own repo, discord server and with your own webhook.
