### ISSUE TITLE
Unable to Check list when the app is downloaded

### ISSUE THREAD

**Issue by TheGreekDev** [rcmaehl/WhyNotWin11#177]
If you delete the contents in the %temp% folder, and you try to download any new version of the app, the CPU compatibility is showing a "?" mark, if you close the app, add the lists yourself to the %temp%, and open it again, then it works. It does not do it automatically :(

**Comment by rcmaehl** [comment]
If you're not already using the latest build, please try it as this should be fixed

https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

**Comment by TheGreekDev** [comment]
Oh thank you, that's fixed in this version, tried it right now!

**Comment by jmwoods301** [comment]
> 
> 
> If you delete the contents in the %temp% folder, and you try to download any new version of the app, the CPU compatibility is showing a "?" mark, if you close the app, add the lists yourself to the %temp%, and open it again, then it works. It does not do it automatically :(

The files no longer exist in %temp% on my system.

They are in C:\Users\<My User Name>\AppData\Local\WhyNotWin11

**Comment by TheGreekDev** [comment]
Just checked it, pretty cool tbh, better than the %temp% it was before
