### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by gidano** [rcmaehl/WhyNotWin11#179]
Hello,
I can't make a pull request, but I made the Hungarian language file, it may be interesting for those who don't know English in my country! :)
Thank you for the opportunity!

Regards,
gidano
from Hungary

[Hungarian.zip](https://github.com/rcmaehl/WhyNotWin11/files/6730827/Hungarian.zip)

**Comment by micwoj92** [comment]
Please refer to this guide when translating https://github.com/rcmaehl/WhyNotWin11/blob/main/Langs/REFERENCE%20GUIDE.txt

Hungarian has already been added: https://github.com/rcmaehl/WhyNotWin11/blob/main/Langs/040E.lang

And here is GitHub's tutorial on how to create pull requests: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
