### ISSUE TITLE
SetProcessDpiAwarenessContext

### ISSUE THREAD

**Issue by Qazy147** [rcmaehl/WhyNotWin11#180]
I'm not sure what this function does and mayby it works "by accident". Expression `"DPI_AWARENESS_CONTEXT"-1` evaluates as -1 because string converts to zero. 
So if last parameter should be -1, it is OK, but in this case ther is no need for string `"DPI_AWARENESS_CONTEXT"`.

**Comment by rcmaehl** [comment]
This is based on MS's example: https://docs.microsoft.com/en-us/windows/win32/hidpi/dpi-awareness-context

**Comment by jmwoods301** [comment]
> I'm not sure what this function does .

From Microsoft -

https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process?redirectedfrom=MSDN

**Comment by Qazy147** [comment]
In this case I think DPI_AWARENESS_CONTEXT should be some numerical constant not string.

**Comment by Qazy147** [comment]
Something like:
```
Const $DPI_AWARENESS_CONTEXT = 0x????
DllCall("User32.dll", "bool", "SetProcessDpiAwarenessContext" , "HWND", $DPI_AWARENESS_CONTEXT-1)
```

**Comment by jmwoods301** [comment]
> 
> 
> In this case I think DPI_AWARENESS_CONTEXT should be some numerical constant not string.

In the SDK, they are negative integers cast to a handle.

**Comment by Qazy147** [comment]
OK, if it is working, let it be. :-)
