### ISSUE TITLE
i5-7200U is not in your checklist, pls add it 

### ISSUE THREAD

**Issue by kumarayush2104** [rcmaehl/WhyNotWin11#181]
![Screenshot (3)](https://user-images.githubusercontent.com/40270440/123742426-3c804f00-d8c9-11eb-9cc7-458e1c5787d9.png)

**Comment by jmwoods301** [comment]
i5-7200U is not listed in Microsoft's documentation -

https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors
