### ISSUE TITLE
German Translation: Special characters not shown

### ISSUE THREAD

**Issue by htcfreek** [rcmaehl/WhyNotWin11#185]
Special characters from german translation shown as ??, ++, ....
Seems to be an encoding bug.

**Comment by micwoj92** [comment]
Yeah, it is encoding. GitHub can't store these properly afaik, so it's best
to change these in CI before compiling. I know it's possible Linux, so
should also be possible here.

W dniu wtorek, 29 czerwca 2021 Heiko ***@***.***> napisał(a):

**Comment by htcfreek** [comment]
@micwoj92 
What encoding do we need?

**Comment by htcfreek** [comment]
I think about if we can fix it with git attributes config?

**Comment by micwoj92** [comment]
I would just do it in CI, I have seen some "fixes" in prs already but they make characters look "bugged" when looked on GitHub website and I think it's unacceptable.

**Comment by htcfreek** [comment]
> I would just do it in CI, I have seen some "fixes" in prs already but they make characters look "bugged" when looked on GitHub website and I think it's unacceptable.

There git attributes will help because they get converted on upload to show on webpage and on download back to original encoding

**Comment by micwoj92** [comment]
Do you know how to do this? I have no idea...

**Comment by htcfreek** [comment]
> Do you know how to do this? I have no idea...

You can search in google for `git attributes encoding`. There you should find the document for `.gitattributes` file.
