### ISSUE TITLE
Multilingual support error due to encoding issue, UTF-8 not handled correctly

### ISSUE THREAD

**Issue by Howard20181** [rcmaehl/WhyNotWin11#186]
Does not seem to handle UTF8 correctly
![image](https://user-images.githubusercontent.com/40033067/123753458-71ea6400-d8ec-11eb-8ecf-a1c965db39c6.png)

**Comment by DrPeaboss** [comment]
Unless the encoding of the file "0804.lang" is changed to ANSI
