### ISSUE TITLE
Not displayed correctly in Simplified Chinese Windows version

### ISSUE THREAD

**Issue by BINGHUAice** [rcmaehl/WhyNotWin11#188]
![image](https://user-images.githubusercontent.com/63250003/123753373-58491c80-d8ec-11eb-9c71-6c1fdb7cb3c8.png)

Maybe wrong font be used

**Comment by DrPeaboss** [comment]
我估计 Autoit3 不支持 UTF8 编码的 ini 文件
Maybe Autoit3 does not support utf8 ini file

**Comment by nAnderYang** [comment]
same that,mabe wrong character set.

**Comment by IT-YUNMENGZE** [comment]
Me too.
How to solve it?
