### ISSUE TITLE
Does not check the display requirement (DirectX 12, WDDM 2)

### ISSUE THREAD

**Issue by verdy-p** [rcmaehl/WhyNotWin11#19]
Can you check the requirement for display?
As well the check on processor has a "?": Microsoft has obviously been hacked internally by Microsoft China, that silently modified the CPU support for ALL existing supported versions of Windows (7, 8, 8.1, 10, Home/Pro/Server/Enterprise/IOT...)
The Microsoft eligibility program was made by Microsoft China, using rules applicable only to PR China for the specific versions of Windows distributed in PR China (with many restrictions and differences).
Win 11 alpha tests have been made only internally by MS China, (including the leaked version that appeared on their site for some Chinese manufacturers): this version was evidently made only to test the program for manufacturers of new products. This should have had NO consequences on the existing contracted licences for the rest of the world.

Windows 11 eligibility has simply NEVER been tested by Microsoft for use by any one else than Chinese manufacturers for new PCs. But pushing that version is simply an abuse, because it has also silently dropped the support for all existing versions.

Microsoft must restore their support pages for Win7/8/8.1/10 (and related server/IOT versions) and clearly state that Win11 is still NOT ready and will not be available at fall outside the PR China market with their specific licences.

And Microsoft must drop their trust in their PR-Chinese subsidiary, clearly under influence of the PR China government, jsut interested to boost their sales (as if they needed it! There's not even enough supply to satisfy the demand on CPUs, RAMs, Graphics cards, SSD for billions new PCs that Microsoft want to waste with its current plan).

Windows 11 is simply not ready, it has NEVER been tested for deployment outside Chinese manufacturers or designers for new PCs. Microsoft has to admit it, and restore the existing support that has been maliciously and severey hacked by MS China!

But now Microsoft is lying and this LIE must end very fast, before it causes massive damages. All worldwide deployment plans have to be cancelled. They are FAKE.

**Comment by micwoj92** [comment]
>  Microsoft has obviously been hacked internally by Microsoft China, that silently modified the CPU support for ALL existing supported versions of Windows (7, 8, 8.1, 10, Home/Pro/Server/Enterprise/IOT...)

Windows 11 in an inside job???

> Microsoft must restore their support pages for Win7/8/8.1/10 (and related server/IOT versions) 


> and clearly state that Win11 is still NOT ready and will not be available at fall outside the PR China market with their specific licences.

**Comment by micwoj92** [comment]
>  Microsoft has obviously been hacked internally by Microsoft China, that silently modified the CPU support for ALL existing supported versions of Windows (7, 8, 8.1, 10, Home/Pro/Server/Enterprise/IOT...)

Windows 11 in an inside job???

> Microsoft must restore their support pages for Win7/8/8.1/10 (and related server/IOT versions) 

Microsoft can do whatever they want to do. 

> and clearly state that Win11 is still NOT ready and will not be available at fall outside the PR China market with their specific licences.

I don't know, on they page it clearly says that "Upgrade rollout plan is being finalized and is scheduled to begin in late 2021 and continue into 2022. Specific timing will vary by device."

Without any sources this whole post looks like meaningless rant. Only first 2 sentences have relation to this software. If you really hate MS that much then just switch to different operating system and stop caring what people use, it's only their business.

**Comment by rcmaehl** [comment]
DirectX 12 check has been added to Version 2.1.0
