### ISSUE TITLE
If you run the program in a Japanese environment, the text will be garbled.

### ISSUE THREAD

**Issue by Tomo-Tg** [rcmaehl/WhyNotWin11#191]
<img width="602" alt="スクリーンショット 2021-06-29 165849" src="https://user-images.githubusercontent.com/66196203/123760063-75391c00-d8fb-11eb-888e-20047d270870.png">
If you run it in a Japanese environment, the text is garbled. You may want to add a language selection menu or something until the problem is solved.

**Comment by arigayas** [comment]
Is it a related issue?
#186

**Comment by Tomo-Tg** [comment]
I'm afraid so.

**Comment by arigayas** [comment]
![image](https://user-images.githubusercontent.com/11251874/123800376-34093200-d924-11eb-868c-0438bda3d6dd.png)

Fixed in 2.3.0.1!
