### ISSUE TITLE
German translation - 1031.lang  added as UTF8  with Unix Linefeed(s) at the end(s)

### ISSUE THREAD

**Issue by hajubu** [rcmaehl/WhyNotWin11#194]
Observing , that the 0000.lang and the 409.lang does not really ends with a linefeed  before end-of-file , I remembered me , that 
In the past I'd learned the hard-way tha might cause problems.

So I do add my own translation  (1031.lang.txt) in the attached zip-file (1031.lang.zip) as a proposal for you. 
I kept some of the wording  in English, because I believe it is better to stay with the technical terms.

[1031.lang.zip](https://github.com/rcmaehl/WhyNotWin11/files/6731691/1031.lang.zip)

b.r. Hajubu

**Comment by PierreGrillet** [comment]
You seems to have been trapped as I have been 🙃. The MUI code to use is the Hexadecimal one not decimal. 
`1031.lang` -> `0407.lang`

**Comment by micwoj92** [comment]
@hajubu there already is German translation. please submit pull request to make review easier to do.
