### ISSUE TITLE
TPM wrong check for AMD Ryzen 5 5600X with Gigabyte X570 Aorus Pro motherboard

### ISSUE THREAD

**Issue by jcomas** [rcmaehl/WhyNotWin11#196]
Microsoft PC Health Check shows Windows 11 compatibility, but your tool says TPM is missing (fTPM activated in BIOS). I attach an image of it.

![Windows 11 compatibility check 2](https://user-images.githubusercontent.com/6289333/123762661-50c14d80-d8c3-11eb-8159-42a313355c65.png)

**Comment by DrPeaboss** [comment]
Try open as administrator

**Comment by red-ray** [comment]
What does the powershell *get-tpm* command report?

**Comment by jcomas** [comment]
Internal error:

PS C:\Windows\system32> get-tpm
get-tpm : Error interno del programa de soporte del Módulo de plataforma segura. (Exception from HRESULT: 0x80284001)
En línea: 1 Carácter: 1
+ get-tpm
+ ~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Tpm], TpmWmiException
    + FullyQualifiedErrorId : Microsoft.Tpm.Commands.TpmWmiException,Microsoft.Tpm.Commands.GetTpmCommand

**Comment by jcomas** [comment]
Two screens more for diagnostics.
![tpm windows security](https://user-images.githubusercontent.com/6289333/123773290-d990b700-d8cc-11eb-89b4-50ccdd731ab2.png)
![tpm msc](https://user-images.githubusercontent.com/6289333/123773295-da294d80-d8cc-11eb-93c8-35e5eb4c27be.png)

**Comment by jcomas** [comment]
Rebooting the PC I saw a message asking "TPM reset", I answered YES and it is detecting ok.

![Windows 11 compatibility check ok](https://user-images.githubusercontent.com/6289333/123778860-d946ea80-d8d1-11eb-9936-facefc8bd829.png)
![tpm windows security ok](https://user-images.githubusercontent.com/6289333/123778863-d9df8100-d8d1-11eb-951d-da7653a521b7.png)
