### ISSUE TITLE
Weird symbols in v 2.3.0.0

### ISSUE THREAD

**Issue by timofeika** [rcmaehl/WhyNotWin11#197]
![WhyNotWin11_x86_d8fRSSROSz](https://user-images.githubusercontent.com/17032666/123763267-09e05180-d8dd-11eb-8c48-53083bb6abad.png)

**Comment by GodinRaider** [comment]
![image](https://user-images.githubusercontent.com/22397709/123769608-23c86700-d8d2-11eb-848d-3940c304eab1.png)
Same.
System lang - russian.

**Comment by MetaMmodern** [comment]
Same here)
![image](https://user-images.githubusercontent.com/42899786/123775480-15c91500-d8d7-11eb-99fc-04f2853eaa20.png)
