### ISSUE TITLE
Bad codepage

### ISSUE THREAD

**Issue by VassilSanych** [rcmaehl/WhyNotWin11#198]
![image](https://user-images.githubusercontent.com/11015941/123764532-8b2fe800-d8cd-11eb-8925-cd462b974a4c.png)

**Comment by SnowPowerCore** [comment]
+1 have the same issue on Windows 10 21H1 using Russian interface language.

**Comment by Qazy147** [comment]
I had same problem. I had to convert my translation (czech) from UTF-8 into Latin 2 (Code page 852).

**Comment by akulisch** [comment]
Same with German, everything that is not ASCII doesn't work.
![image](https://user-images.githubusercontent.com/15906252/123772105-e2cd5400-d8cb-11eb-966c-0216332b46fd.png)

**Comment by Qazy147** [comment]
Czech in 2 different codepages:![CodaPage](https://user-images.githubusercontent.com/86588462/123777020-19a56900-d8d0-11eb-83a6-b72853c4e040.png)

**Comment by BSoD38** [comment]
Same deal for French.

![WhyNotWin11_tIXDtdkRrt](https://user-images.githubusercontent.com/15630367/123796552-870fc480-d8e5-11eb-9e8d-3ed70c879e2d.png)

**Comment by rcmaehl** [comment]
Fixed in 2.3.0.1

**Comment by Qazy147** [comment]
Now is my translation in Code page 852 broken. Which code page should I use UTF-8, UTF-16, ... ?

**Comment by rcmaehl** [comment]
> Now is my translation in Code page 852 broken. Which code page should I use UTF-8, UTF-16, ... ?

"unicode" / Unicode UTF16 Little Endian
