### ISSUE TITLE
gpt detect

### ISSUE THREAD

**Issue by Javier666777** [rcmaehl/WhyNotWin11#199]
GPT not detected

![partition](https://user-images.githubusercontent.com/86654975/123767379-b31c4d00-d8c7-11eb-82ba-a70b487625d3.jpg)

**Comment by AGuyNamedJens** [comment]
I think the checker for the GPT is messed up in the update, works fine in v2..

**Comment by htcfreek** [comment]
do you have more than one disk connected? Then it's a duplicate

**Comment by micwoj92** [comment]
@Javier666777 could you confirm?

**Comment by htcfreek** [comment]
> @Javier666777 could you confirm?

look at image. it shows disk1 and not disk0

**Comment by micwoj92** [comment]
Oh yeah, sorry
