### ISSUE TITLE
v2.3.0.0 hungarian language 

### ISSUE THREAD

**Issue by gidano** [rcmaehl/WhyNotWin11#201]
I think character encoding is error and the font size is too large for the required text.
Moreover, translation is not appropriate everywhere. Unnecessary plural in many cases.

![Képernyőkép 2021-06-29 105456](https://user-images.githubusercontent.com/4068977/123768631-c8de4200-d8c8-11eb-8343-69c71dfddcb7.png)

**Comment by PierreGrillet** [comment]
Every translation is impacted.
Should be merge with #186. Problem seems coming from Lang file encoding.
