### ISSUE TITLE
german umlauts

### ISSUE THREAD

**Issue by Henry2o1o** [rcmaehl/WhyNotWin11#207]
In German Ä Ü Ö ß - umlauts are displayed incorrectly.

![image](https://user-images.githubusercontent.com/6131799/123776269-6dfc1900-d8cf-11eb-8821-be95d5291c8a.png)

**Comment by PierreGrillet** [comment]
Every translation is impacted.
Should be merge with #186. Problem seems coming from Lang file encoding.
