### ISSUE TITLE
Traditional Chinese display garbled

### ISSUE THREAD

**Issue by nightsnowlin** [rcmaehl/WhyNotWin11#208]
![image](https://user-images.githubusercontent.com/24751265/123776548-f98e9d80-d901-11eb-80c8-7c95fe7ae0fc.png)

**Comment by aiqinxuancai** [comment]
![image](https://user-images.githubusercontent.com/4475018/123781140-7754a800-d906-11eb-9bff-393ce592ae76.png)
Don't support multiple languages, just support English

**Comment by PierreGrillet** [comment]
Every translation is impacted.
Should be merge with #186. Problem seems coming from Lang file encoding.

**Comment by karakoo** [comment]
1. 控制面板👉区域👉管理👉更改系统区域设置
2. 将UTF-8勾选上
![image](https://user-images.githubusercontent.com/70872201/123787148-0e246300-d90d-11eb-96f1-66b18c3c9860.png)
**然后就可以正常显示了**
![image](https://user-images.githubusercontent.com/70872201/123787211-1f6d6f80-d90d-11eb-97b5-f77ff85c298f.png)

**Comment by PierreGrillet** [comment]
Can we have this insight in English please :pray: ?
