### ISSUE TITLE
Improve CI

### ISSUE THREAD

**Issue by micwoj92** [rcmaehl/WhyNotWin11#21]
I think that the CI is pretty bad, I have been working a bit on improving it but I don't know Windows/Powershell that much and I hope that due to this project's popularity someone who knows better will see it. 
So couple of points I think are worth improving:

* [x] Use more (GitHub provided) variables so the CI is more flexible (example `${{ github.repository }}` which is used now)

* [x] Change manual git clone to actions/checkout (it's pretty easy, but for some reason not always as reliable)

* [x] Change manual autoit download+install to use some package manager (or just a faster/better/more elegant way, I tried chocolatey and it worked but was very slow, scoop worked much better, but with pretty small size of autoit tools and the fact that first you need to get scoop itself I don't know if it brings any time benefits)
   ^ Caching is used now

* [x] Remove the ugly (in my opinion) need for `Start-Sleep -s 10`. This is "because it returns back to shell before it completes". and by "it" I mean the autoit compiler/tools. I tried different methods, for example loop that checks if file exists but it either hanged the GitHub runner or was really slow (and still needed wait command anyway). Again, I might be missing something obvious here.

* [x] Print hash of produced binary (and then use it in release)

* [x] Automatically upload artifacts on release.

**Comment by sanny-io** [comment]
Linking this related comment here.

https://github.com/rcmaehl/WhyNotWin11/issues/20#issuecomment-868900466

**Comment by micwoj92** [comment]
Ok, this should be easy (besides that automation part) but it is up to Robert to change his workflow. Thanks for suggestion.

**Comment by micwoj92** [comment]
@rcmaehl Will next release be artifact from CI? Then it would solve 1st point.

**Comment by rcmaehl** [comment]
> @rcmaehl Will next release be artifact from CI? Then it would solve 1st point.

I mean.... It can be.

**Comment by micwoj92** [comment]
Thanks, then it also needs to include new x86 build + hashes for it.
