### ISSUE TITLE
French translation texts are too long

### ISSUE THREAD

**Issue by BSoD38** [rcmaehl/WhyNotWin11#217]
Many of the french translations's strings are too long and clip out of bounds of the UI.

![WhyNotWin11_Lzq6bjBl2z](https://user-images.githubusercontent.com/15630367/123798181-3b5e1a80-d8e7-11eb-9e20-164e0176aa00.png)

Shorter variants of the same sentences should be used, for example :

* `Votre résultat de compatiblité de Windows 11 est ci-dessous` -> `Résultats de compatiblité avec Windows 11`
* `Espace de stockage disponible` -> `Espace disque disponible` or `Stockage disponible`
*  `Architecture (Processeur + OS)` -> `Architecture (CPU + OS)`

**Comment by DanGM96** [comment]
This is happening in a few other languages too, including pt-BR. I'm sure most could change for shorter variants, but idk for everyone. We may need a bigger window or tool tips in a few places to make up for that, but it's not up to me.

**Comment by micwoj92** [comment]
Feel free to submit shorter translation. It does not have to be word for word, just the same meaning.

**Comment by micwoj92** [comment]
> Co z Russian one is really bad translation.

If you think you can improve feel free to submit pull request.

**Comment by Oleg-Chashko** [comment]
Russian translation texts are too long.

<img width="588" alt="Screen Shot 2021-06-29 at 18 46 03" src="https://user-images.githubusercontent.com/62497891/123837518-37dc8a80-d90b-11eb-9868-8286d8e0e71e.png">

**Comment by micwoj92** [comment]
@Oleg-Chashko feel free to submit pull request to fix that.

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko feel free to submit pull request to fix that.

Ok

**Comment by micwoj92** [comment]
Fixed, for other languages please just open pull requests.
