### ISSUE TITLE
Collaboration for this program

### ISSUE THREAD

**Issue by rmcpantoja** [rcmaehl/WhyNotWin11#222]
Hello,
I want to collaborate in the development of this program, since I have found it an excellent alternative to the "pc health check" program.
I have experience programming in autoit, in fact, I added the Spanish translation, but when I want to make a Pull request from my Git For Windows, in the final step, it tells me that the permission has been denied, and from what I understand it is necessary to create an issue before collaborating.
In addition, I have tried this program and the interface has seemed good to me, only, there is a small problem that is the accessibility for users with screen readers and I would also like to collaborate on it if they allow me, but I also want to give to know what this is more or less about.
A screen reader is a program where people with visual disabilities can access all the information on the computer, tablet, mobile and a long etcetera through text to speech, navigating the application controls with the keyboard. One of them is "NVDA" (Non Visual Desktop Access) Open Source Screen Reader for Windows, which provides a good experience for us. So, when on some occasions when we test a different program than the one we know, when navigating in each of the GUI controls there are certain conflicts. Or is it that the screen reader will not tell us that control information we are in and we need some OCR or help from a sighted person, or is it that sometimes it can generate confusion or a bad interpreter in the controls with screen readers, and this is what I call lack of accessibility.
That being said, I know how to handle this because I have all the necessary knowledge, and I hope I can add; in fact, I had planned to add the documentation and some user manual for each of the languages ​​(although I speak Spanish, English and Portuguese)
I hope again to help, thank you very much.

**Comment by micwoj92** [comment]
You need to fork it to your account, push changes and then you can submit pull request
https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by micwoj92** [comment]
I will close this one, feel free to resubmit with pull request or create issues, 1 issue per ticket, thanks!
