### ISSUE TITLE
Quadro P5000 (maybe more) does not report DDI Version

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/WhyNotWin11#223]
[DxDiag (1).txt](https://github.com/rcmaehl/WhyNotWin11/files/6733712/DxDiag.1.txt)

![image](https://user-images.githubusercontent.com/716581/123805753-59faec00-d8bc-11eb-95af-ff60b976706d.png)

**Comment by rcmaehl** [comment]
Wrong ticket reference

**Comment by micwoj92** [comment]
After couple hours of searching I can say the following: if you have wddm 2(or even 2.7 in that case) then you should have dx12. I have seen couple dxdiag reports with windows 10 having wddm1.2 but it was only if it didnt have dx12 capable card. If you are on win10 and have one then you most definitely also have the second one.

**Comment by micwoj92** [comment]
Duplicate #58
