### ISSUE TITLE
Wrong CPU i5-8365U detected instead of according to CPU-Z i5-8665U 

### ISSUE THREAD

**Issue by ajoe** [rcmaehl/WhyNotWin11#230]
CPU-Z version 1.96.1.x64 show's CPU Name: i5 8665U
WhyNotWin11 version 2.2.4.0 show's CPU Compatibility: i5-8365U
The 6 and 3 are different. 

This is not a big issue for me, but it just seams strange... 

WhyNotWin11
![grafik](https://user-images.githubusercontent.com/550961/123815961-34d79f00-d8f7-11eb-83b1-8ca66a0e905e.png)

CPU-Z
![grafik](https://user-images.githubusercontent.com/550961/123816018-3f923400-d8f7-11eb-8024-1e4b93974d38.png)

**Comment by rcmaehl** [comment]
What does Task Manager show?

![image](https://user-images.githubusercontent.com/716581/123817560-43f22900-d8c6-11eb-95c6-873907c155c7.png)

**Comment by ajoe** [comment]
OH! the Task Manager show's the number i5-8365U, the same as within WhyNotWin11. 
![grafik](https://user-images.githubusercontent.com/550961/123827596-0bbc0c00-d901-11eb-8dee-1a56493e3445.png)

**Comment by rcmaehl** [comment]
Might be a CPU-Z bug then ;)

**Comment by ajoe** [comment]
I'll post a bug report there and close this..

**Comment by JohnnyTowns94** [comment]
It does say "i5-8365U" next to specification in CPU-Z. Just weird that it has it different name listed.
