### ISSUE TITLE
MBR formatted SD Card affect the detection

### ISSUE THREAD

**Issue by HuJK** [rcmaehl/WhyNotWin11#231]
Hardware: Surface pro 5
OS: Windows 10

SD card inserted:
![image](https://user-images.githubusercontent.com/15907444/123816342-d0820300-d929-11eb-856f-5d98ad7eaa92.png)

SD card removed:
![image](https://user-images.githubusercontent.com/15907444/123816467-ee4f6800-d929-11eb-955d-bfaab38ed592.png)

**Comment by rcmaehl** [comment]
Please wait 3-5 minutes then try: https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

**Comment by micwoj92** [comment]
ping @HuJK

**Comment by HuJK** [comment]
Now it can detect my GPT drive, thank you!
![image](https://user-images.githubusercontent.com/15907444/123836088-e3053800-d93b-11eb-82e8-3f7ec4974c66.png)

Is it a good idea to exclude removable disks in checklist? Not sure this behavior is same as Microsoft's PC Health Checker.

**Comment by micwoj92** [comment]
I think microsoft app checks for main drive. Thanks for confirming as fixed.
