### ISSUE TITLE
Physical Memory Detect ERROR

### ISSUE THREAD

**Issue by HanHan233** [rcmaehl/WhyNotWin11#233]
My real physical memory is 7.5GiB(512MiB for Intel HD Graphics)
But WhyNotWin11.exe detected 7850120GB
![image](https://user-images.githubusercontent.com/64469437/123819803-a120c580-d92c-11eb-84b8-c55ac12ecd4c.png)
![image](https://user-images.githubusercontent.com/64469437/123819888-b4cc2c00-d92c-11eb-97ad-87797d46a7be.png)

**Comment by rcmaehl** [comment]
Please wait 3-5 minutes then try: https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

**Comment by micwoj92** [comment]
ping @HanHan233

**Comment by rcmaehl** [comment]
Closing as there's no other reason it could be giving that value.

**Comment by HanHan233** [comment]
![image](https://user-images.githubusercontent.com/64469437/123890121-4d909500-d989-11eb-9492-e930deb51bf4.png)
It's OK now , thank you!
