### ISSUE TITLE
Disk Partition Type is incorrect

### ISSUE THREAD

**Issue by ringtailedfox** [rcmaehl/WhyNotWin11#236]
ever since version 2.3.x came out, WhyNotWin11 stopped properly detecting my SSD's partition type.  It used to correctly identify it as GPT, but now it says "GPT Not Detected"...   what's the change that broke this?

**Comment by rcmaehl** [comment]
Please try https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

**Comment by georgiy0804** [comment]
> Please try https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

It`s version is working correctly.

**Comment by micwoj92** [comment]
Thank you for confirming!
