### ISSUE TITLE
Add note for computers that already updated to Windows 11

### ISSUE THREAD

**Issue by 1011025m** [rcmaehl/WhyNotWin11#239]
Current dev build is 22000.51

I just thought to myself, "why would I need to check my compatibility if I already updated anyways?" Would be a great enhancement though.

One thing that I really like is the executable is small enough to be uploaded to Discord, it can be very helpful at times!

**Comment by micwoj92** [comment]
Probably needs to be done same way as win 7 check.

**Comment by micwoj92** [comment]
> One thing that I really like is the executable is small enough to be uploaded to Discord, it can be very helpful at times!

Please rather post direct download link to spread awareness and help boost download count ;p

**Comment by krystian3w** [comment]
Maybe before and add optional run tests.

**Comment by micwoj92** [comment]
> Maybe before 

win 7 check does that, you should be able to use compatibility mode for executable to check
![image](https://user-images.githubusercontent.com/45581170/123853601-edb0d480-d91d-11eb-966c-1be4788e58ec.png)
(screenshot from Wine)

> and add optional run tests.

What do you mean by that?

**Comment by krystian3w** [comment]
To detect instalation based on cheats:

https://github.com/St1ckys/Win11/blob/main/BypassTPMCheck&SecureBoot.reg
