### ISSUE TITLE
Allow Window Dragging

### ISSUE THREAD

**Issue by TrashAccount3424** [rcmaehl/WhyNotWin11#24]
Whats the reason behind the weird window settings?

I just quickly changed

```
$hGUI = GUICreate("WhyNotWin11", 800, 600, -1, -1)
;GUISetBkColor(0xF8F8F8)
```

Now the window can be dragged, minimized and closed normally and there isn't this weird line at the bottom anymore.

```
;$hExit = GUICtrlCreateLabel("X", 760, 10, 30, 30, $SS_CENTER+$SS_CENTERIMAGE)
;GUICtrlSetFont(-1, 24, 400)
```

Can be removed

**Comment by rcmaehl** [comment]
I'll add in dragging in a later version. The Windows 10 title bars aren't the best and I'd like to have a slightly different experience than default. Many applications do this, Discord, Chrome, Telegram.
