### ISSUE TITLE
app shows legacy boot and secure boot not found

### ISSUE THREAD

**Issue by nichog** [rcmaehl/WhyNotWin11#243]
I have verified in my bios that fTPM is enabled, as well as secure boot UFEI. why is it not being reconized by this app
ROG STRIX B350-f Gaming ASUS motherboard

**Comment by nichog** [comment]
Also, I have 2 M.2 drives, the os is on a Samsung 970 250 g, my data and gaming is a Samsung 970 1 tb, it lists only one drive as may not be compatible.  CPU is a Ryzen 5 2nd generation 6 core 1600 it supposedly not on the compatibility list

**Comment by htcfreek** [comment]
@nichog 
Can you please upload a screenshot.

**Comment by nichog** [comment]
How do you do a bios screen screenshot. Or can this    shown in windows   
  

  

  

  

  
  
  
  
  
>

**Comment by micwoj92** [comment]
@nichog You could make picture with your phone.

**Comment by nichog** [comment]
Sorry. Had a brain fart there, will do that is a few.  Eating lunch

**Comment by rcmaehl** [comment]
@nichog Please try the latest build https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip and report back. Due to inactivity on this ticket I will be closing it out in 12 hours.
