### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by Arci224** [rcmaehl/WhyNotWin11#245]
Wrong text encoding for Czech Language:
![image](https://user-images.githubusercontent.com/12967102/123840405-922b1a80-d90e-11eb-9d72-e64d01939588.png)

**Comment by micwoj92** [comment]
Could you test this test build? Scroll down and download Artifact.
https://github.com/rcmaehl/WhyNotWin11/actions/runs/983430159

**Comment by Arci224** [comment]
@micwoj92 some strings still broken.
![image](https://user-images.githubusercontent.com/12967102/123841865-5ee98b00-d910-11eb-85f4-87327e8ca6e3.png)

**Comment by micwoj92** [comment]
@Arci224 
Could you test this one? 
https://github.com/rcmaehl/WhyNotWin11/actions/runs/983581053

I think it should be good, here translation source https://github.com/rcmaehl/WhyNotWin11/blob/main/Langs/0405.lang

**Comment by Arci224** [comment]
Still glitched

**Comment by micwoj92** [comment]
Weird, it seems like Czech is the only language with this problem, other ones seemed to be fixed. Will investigate.

**Comment by micwoj92** [comment]
@Arci224 Could you open %localappdata%\WhyNotWin11\langs\version in notepad and set it to 0.0.0.0? Then download latest dev change and test. Thanks!

**Comment by Arci224** [comment]
@micwoj92 Its working!

**Comment by micwoj92** [comment]
Thanks for confirmation, seems that translation file was not updating to latest version.
