### ISSUE TITLE
The incorrect display of Russian localization.

### ISSUE THREAD

**Issue by georgiy0804** [rcmaehl/WhyNotWin11#246]
Russian localization of the application is displayed incorrectly.

![image](https://user-images.githubusercontent.com/30828435/123840425-f94ccd00-d916-11eb-9d8a-f5a3ef45ac27.png)

**Comment by georgiy0804** [comment]
The first string does not fit on the screen.

**Comment by micwoj92** [comment]
Not really application bug, please submit pull request with shorter translation.
