### ISSUE TITLE
Czech Translation is broken (v.2.3.0.1)

### ISSUE THREAD

**Issue by MasterixCZ** [rcmaehl/WhyNotWin11#247]
![Snímek obrazovky 2021-06-29 191840](https://user-images.githubusercontent.com/84620639/123840776-0ebdf900-d90f-11eb-9ba9-8b3cddead919.png)
Czech Translation is broken in version **2.3.0.1**. Version **2.3.0.0** is ok. Letters like: ž, ř, č, š, ě, ý, á, í, é, are replaced with some random Unicode letters.

**Comment by micwoj92** [comment]
Could you test this test build? Scroll down and download Artifact.
https://github.com/rcmaehl/WhyNotWin11/actions/runs/983430159

 and report in #245? thanks
