### ISSUE TITLE
Issue with accented characters on some systems

### ISSUE THREAD

**Issue by MarioMarietto** [rcmaehl/WhyNotWin11#248]
Accented characters are not displayed correctly for the Italian language (I believe it happens with other languages too)

![AutoIt3_x64_ocoyqTrjL3](https://user-images.githubusercontent.com/46113285/123843352-1df27600-d912-11eb-945e-b4dd91f39206.png)

**Comment by micwoj92** [comment]
@MarioMarietto  Could you open %localappdata%\WhyNotWin11\langs\version in notepad and set it to 0.0.0.0? Then download latest dev change and test. Thanks!

**Comment by MarioMarietto** [comment]
> @MarioMarietto Could you open %localappdata%\WhyNotWin11\langs\version in notepad and set it to 0.0.0.0? Then download latest dev change and test. Thanks!

Hey there! Is it possible to get the au3 version (of the dev version)? The tool doesn't automatically switch the language to Italian (my PC language is currently Italian) and I need to force the loading of that language file. Thank you :)

**Comment by micwoj92** [comment]
You can download the source code from GitHub, if that's what you mean
https://github.com/rcmaehl/WhyNotWin11/archive/refs/heads/main.zip

**Comment by MarioMarietto** [comment]
> You can download the source code from GitHub, if that's what you mean
> https://github.com/rcmaehl/WhyNotWin11/archive/refs/heads/main.zip

Alright. I just tested it and it's giving me the same issue :(

**Comment by sebkopal** [comment]
First I tested Czech language, because people have same problems like Italian language

Windows 10 on my real HW, Slovak language as default
![image1](https://user-images.githubusercontent.com/35070740/123866684-b21e0680-d92d-11eb-8969-84ad1bc37dbb.png)

Windows 10 on VMWare, EN-US language as default
![image2](https://user-images.githubusercontent.com/35070740/123866808-d7127980-d92d-11eb-8afe-d8c664a7a5f5.png)

You can test this one
[0410.lang.txt](https://github.com/rcmaehl/WhyNotWin11/files/6736433/0410.lang.txt)

Maybe specific Windows 10 update causing that ?
Or people using Insider builds of Windows 10 ?

**Comment by micwoj92** [comment]
Thanks for testing, will need further investigation.

**Comment by MarioMarietto** [comment]
That could be an actual issue with the OS version. I'm currently running Windows 11 Insider Build, I don't know if that's the issue :)

**Comment by micwoj92** [comment]
Oooh, wonder what @Masterix is using.

**Comment by MarioMarietto** [comment]
I will test it now on my Windows 10 Virtual Machine and I'll let you know if I get the same problem :) @micwoj92

**Comment by sebkopal** [comment]
I using Windows 10 Enterprise LTSC 2019 (v1809) [sk-SK] on my real HW
and in VMWare I using Windows 10 Pro 21H1 [en-US]

I never used Insider versions of Windows

Btw I used realease 2.3.0.1 WhyNotWin11, not DEV versions

**Comment by micwoj92** [comment]
Initial issue was from 2.3.0.1, but could you check dev just to be 100% sure?

**Comment by sebkopal** [comment]
Nothing changed, still works same for me.

@MarioMarietto, did you first installed Windows 11 Insider build in en-US language, then you installed Italian language pack ?
This caused same specific problem in World Editon for Warcraft III (2002) I used.

**Comment by MarioMarietto** [comment]
Alright, I've tested it on my VM (Windows 10 21H1 - 19043) and I'm getting the same issue. The thing is that I have the English Language Pack installed (because I couldn't get the tool running in Italian even if I had the Italian Language Pack installed)
> @MarioMarietto, did you first installed Windows 11 Insider build in en-US language, then you installed Italian language pack ?
Yup

I will test it on another real machine (running the Italian Language Pack only) and I'll see what happens :)

**Comment by MarioMarietto** [comment]
> Alright, I've tested it on my VM (Windows 10 21H1 - 19043) and I'm getting the same issue. The thing is that I have the English Language Pack installed (because I couldn't get the tool running in Italian even if I had the Italian Language Pack installed)
> 
> > @MarioMarietto, did you first installed Windows 11 Insider build in en-US language, then you installed Italian language pack ?
> > Yup
> 
> I will test it on another real machine (running the Italian Language Pack only) and I'll see what happens :)

Update: Still getting the same issue

**Comment by MarioMarietto** [comment]
btw I'm using this to force the Italian language
`Func _Translate($sString)
	_INIUnicode(@LocalAppDataDir & "D:\0410.lang")
	Return _WinAPI_OemToChar(INIRead("D:\0410.lang", "Strings", $sString, $sString))
	Return INIRead(@LocalAppDataDir & "D:\0410.lang", "Strings", $sString, $sString)
EndFunc`

Am I doing something wrong?

**Comment by rcmaehl** [comment]
> btw I'm using this to force the Italian language (where "D:\0410.lang" is the location of the translation file)
> 
> ```autoit
> Func _Translate($sString)
> 	_INIUnicode(@LocalAppDataDir & "D:\0410.lang")
> 	Return _WinAPI_OemToChar(INIRead("D:\0410.lang", "Strings", $sString, $sString))
> 	Return INIRead(@LocalAppDataDir & "D:\0410.lang", "Strings", $sString, $sString)
> EndFunc
> ```
> 
> Am I doing something wrong?

I wouldn't use _WinAPI_OemToChar with _INIUnicode

**Comment by Sap1k** [comment]
> @MarioMarietto Could you open %localappdata%\WhyNotWin11\langs\version in notepad and set it to 0.0.0.0? Then download latest dev change and test. Thanks!

By the way, this worked for me to fix Czech strings.

**Comment by micwoj92** [comment]
I think we need some sort of quick-fixes.md or something with fixes for common issues like these.

**Comment by MarioMarietto** [comment]
Hey! Update: I've managed to get the issue fixed! 
First of all, I was probably doing something wrong when trying to force the Italian Translation. This worked for me:
```autoit
Func _Translate($iMUI, $sString)
	_INIUnicode(@LocalAppDataDir & "\WhyNotWin11\Langs\0410.lang")
	Return INIRead(@LocalAppDataDir & "\WhyNotWin11\Langs\0410.lang", "Strings", $sString, $sString)
EndFunc
````
(before I was using)
```autoit
Func _Translate($sString)
	_INIUnicode(@LocalAppDataDir & "D:\0410.lang")
	Return _WinAPI_OemToChar(INIRead("D:\0410.lang", "Strings", $sString, $sString))
	Return INIRead(@LocalAppDataDir & "D:\0410.lang", "Strings", $sString, $sString)
EndFunc
````
(where "D:\0410.lang" was the location of the translation file)

Then I've deleted every file in %LocalAppData%\WhyNotWin11 and I've restarted the tool. And this somehow fixed the issue! I'm sorry, this was probably an issue on my end, but I wasn't 100% sure :)

**Comment by micwoj92** [comment]
Thank you for confirming.
