### ISSUE TITLE
The 1.2 tpm requirement is gone

### ISSUE THREAD

**Issue by ender1324** [rcmaehl/WhyNotWin11#25]
Microsoft removed soft-floor/hard-floor requirements and just made it on, saying only tpm >=2.0 is allowed.
Reference: https://docs.microsoft.com/en-us/windows/compatibility/windows-11/

**Comment by rcmaehl** [comment]
Yeah, they've been changing it around a lot. I'll update the check in the next release

**Comment by krystian3w** [comment]
Maybe mirror: https://www.microsoft.com/en-us/windows/windows-11-specifications

**Comment by treysis** [comment]
The app still shows TPM 1.2 as sufficient.

**Comment by rcmaehl** [comment]
> The app still shows TPM 1.2 as sufficient.

WhyNotWin11 or PC Health Check?

**Comment by treysis** [comment]
WhyNotWin11 shows TPM 1.2 as green. PC Health Check says minimum TPM 2.0 required.
