### ISSUE TITLE
Please reduce the font size a bit

### ISSUE THREAD

**Issue by Oleg-Chashko** [rcmaehl/WhyNotWin11#261]
If you can, please make the font size smaller. 
I would like the font size to be neither large nor small. 

**Currently:**

![123688747-6598d500-d820-11eb-802e-a97c39695f10](https://user-images.githubusercontent.com/62497891/123869307-1c847600-d931-11eb-8b92-a442e25d230a.png)

**A couple of versions ago:**

![123548297-33a94500-d732-11eb-882d-720fe989f2f2](https://user-images.githubusercontent.com/62497891/123869382-30c87300-d931-11eb-9ae1-e337f5274471.png)

**Comment by micwoj92** [comment]
I think previous was better.

**Comment by Oleg-Chashko** [comment]
> I think previous was better.

Yes, I completely agree with you.

**Comment by rcmaehl** [comment]
Please try https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

**Comment by shark873** [comment]
> Please try https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

Better, but still blocks some text on PT-BR(Brazilian Portuguese) language as you can see below \/ on the CPU part.

![WhyNotWin11_2021-06-30_01-50-59](https://user-images.githubusercontent.com/10945499/123903986-1351d400-d946-11eb-9f4a-5568f1f6b070.png)

**Comment by rcmaehl** [comment]
The issue with text will to be fixed by the translator. EIther by adjusting font size for the translation or replacing the text with a shorter alternative

**Comment by shark873** [comment]
> The issue with text will to be fixed by the translator. EIther by adjusting font size for the translation or replacing the text with a shorter alternative

Thx,..

I also saw that there will be a language selector in version 3.0, that will also solve the issue for me.

**Comment by DanGM96** [comment]
> Better, but still blocks some text on PT-BR(Brazilian Portuguese) language as you can see below / on the CPU part.

Actually it is already fixed, but when using dev builds you should go to `C:\Users\YOUR-USERNAME\AppData\Local\WhyNotWin11` and delete the `\Langs` folder so the software can insert the new files.
This happens because the files are only updated when the version changes, and we've been using that same version for testing.

**Comment by shark873** [comment]
> > Better, but still blocks some text on PT-BR(Brazilian Portuguese) language as you can see below / on the CPU part.
> 
> Actually it is already fixed, but when using dev builds you should go to `C:\Users\YOUR-USERNAME\AppData\Local\WhyNotWin11` and delete the `\Langs` folder so the software can insert the new files.
> This happens because the files are only updated when the version changes, and we've been using that same 2.3.0.1 version for testing for quite a while.

Thx for letting me know that, will do it and check again :D

**Comment by Oleg-Chashko** [comment]
> Please try https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

Thx,.. Ok.
