### ISSUE TITLE
提示不支持DX12

### ISSUE THREAD

**Issue by hayye** [rcmaehl/WhyNotWin11#265]
![IHOR0BRJ_5QN_FZ)~DYVZE](https://user-images.githubusercontent.com/30612116/123888891-04d7dc80-d987-11eb-854e-72544a0c70b6.png)
![%HA0BT4Y9U7F3XUK(XV2RP7](https://user-images.githubusercontent.com/30612116/123888895-06a1a000-d987-11eb-9c44-c9167e4052fa.png)
在DirectX诊断工具中检查是DX12的

**Comment by rcmaehl** [comment]
翻译：请选择“保存所有信息”并附上它保存的文件

**Comment by hayye** [comment]
> 翻译：请选择“保存所有信息”并附上它保存的文件



> 翻译：请选择“保存所有信息”并附上它保存的文件

**Comment by hayye** [comment]
> 翻译：请选择“保存所有信息”并附上它保存的文件

[DxDiag.txt](https://github.com/rcmaehl/WhyNotWin11/files/6737453/DxDiag.txt)

**Comment by rcmaehl** [comment]
翻译：看来 DDI 版本正在报告 11。
`DDI Version: 11.1`
我会为未来的版本制作一个补丁
