### ISSUE TITLE
Respect windows theme background color or hard code font color

### ISSUE THREAD

**Issue by TayouVR** [rcmaehl/WhyNotWin11#268]
I have a custom windows theme installed. The font color gets applied, but the background not. therefore text in some places is a bit harder to read.
![image](https://user-images.githubusercontent.com/31988415/123899881-545ae000-d968-11eb-88fb-8cdc6d9aa07b.png)
Fetching the actual theme background color would be optimal, but just hard setting font color to black would work too.
Particularly on the colored squares. those need a set color.

**Comment by TayouVR** [comment]
![image](https://user-images.githubusercontent.com/31988415/123954517-c81cdd00-d9a8-11eb-9b07-113552e97282.png)
perfect. didn't expect such a fast response. Now the text on the squares needs to be.. solid black? or white? or tied to the square color maybe, some kind of complementary color?

And I guess the icons on the left theoretically need to be changed too, but that doesn't really matter and might not be worth the effort.

**Comment by rcmaehl** [comment]
> ![image](https://user-images.githubusercontent.com/31988415/123954517-c81cdd00-d9a8-11eb-9b07-113552e97282.png)
> perfect. didn't expect such a fast response. Now the text on the squares needs to be.. solid black? or white? or tied to the square color maybe, some kind of complementary color?
> 
> And I guess the icons on the left theoretically need to be changed too, but that doesn't really matter and might not be worth the effort.

@TayouVR Excuse the late reply. @micwoj92 generally handles issue routing and PRs. I skimmed over this past the initial report. I'll see if I can fix text too, but it's the same color as the rest of the text. And yeah, icons have been a pain because they're using fake transparency and I can't seem to fix it.
