### ISSUE TITLE
Ram 0 GB

### ISSUE THREAD

**Issue by vinay-winai** [rcmaehl/WhyNotWin11#27]
when i ran your latest version it gave all green checks except ram(0gb)
![Screenshot (29)](https://user-images.githubusercontent.com/60219349/123509130-72d38980-d691-11eb-817b-7c9488c241ea.png)

**Comment by vinay-winai** [comment]
FYI, I have  enabled xmp profile

**Comment by Viking602** [comment]
mee to! is it a.. bug?

**Comment by vinay-winai** [comment]
> mee to! is it a.. bug?

May be 2.1.0 version exclusive bug, I have no coding skills to verify or fix it

**Comment by htcfreek** [comment]
@rcmaehl 
Maybe it's better to use https://www.autoitscript.com/autoit3/docs/functions/MemGetStats.htm instead the DLLCall.

**Comment by rcmaehl** [comment]
> @rcmaehl
> Maybe it's better to use https://www.autoitscript.com/autoit3/docs/functions/MemGetStats.htm instead the DLLCall.

MemGetStats only returns Available RAM, excluding Hardware Reserved. I know this is an issue for some VMs, but I'll add back in a rounded version of MemGetStats on failure to be safe
