### ISSUE TITLE
x64 and x86 not giving same DirectX result

### ISSUE THREAD

**Issue by IvanAclu** [rcmaehl/WhyNotWin11#270]
When I run 2.3.0.1 x64 and x86 executables on my 64 bit PC.
x64 displays, "DirectX 12 & WDDM 2".
x86 displays, "No DirectX 12, but WDDM 2".

**Comment by rcmaehl** [comment]
Please upload the `save all information` files from

C:\Windows\System32\dxdiag.exe
C:\windows\SysWOW64\dxdiag.exe

I have a feeling that I need to restrict the executables to their native systems

**Comment by IvanAclu** [comment]
DxDiag.txt x86 & x64 files as requested.

[DxDiag_x86.txt](https://github.com/rcmaehl/WhyNotWin11/files/6742693/DxDiag_x86.txt)
[DxDiag_x64.txt](https://github.com/rcmaehl/WhyNotWin11/files/6742694/DxDiag_x64.txt)

**Comment by rcmaehl** [comment]
Odd, I'm not sure how x64 is getting different results. Please try the latest build

https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

**Comment by IvanAclu** [comment]
Both executables now give same result.
"No DirectX 12, but WDDM 2".
This seems to disagree with DxDiag, which says "DirectX Version: DirectX 12".

**Comment by rcmaehl** [comment]
DirectX Version is for what version of DirectX your OS supports. 

You have a UHD 4000, per TechPowerUp (creators of GPU-Z), you have DirectX 11 which matches DDI Version (11) and Feature Level 11

https://www.techpowerup.com/gpu-specs/hd-graphics-4000.c1266

**Comment by IvanAclu** [comment]
Thanks for clarifying the issue.
The PC also has a Geforce 650M
https://www.techpowerup.com/gpu-specs/geforce-gt-650m.c547
This seems to show that this card supports DirectX 12
However I see that in DxDiag for this card.
DDI Version: Unknown
Feature Levels: Unknown

**Comment by rcmaehl** [comment]
> Thanks for clarifying the issue.
> The PC also has a Geforce 650M
> https://www.techpowerup.com/gpu-specs/geforce-gt-650m.c547
> This seems to show that this card supports DirectX 12
> However I see that in DxDiag for this card.
> DDI Version: Unknown
> Feature Levels: Unknown

Ah, I'm not sure if there's some sort of display switching enabled causing the card to not report currently, but as soon as that card reports it's versioning you'll get a pass on WhyNotWin11. I'm not aware of any other to get directx for that meets current project specs.

I'm going to close this issue for now

**Comment by IvanAclu** [comment]
Happy for you to close this issue as both executables give same result.

However, I wonder if perhaps you need to warn about more than 1 graphics card making the results uncertain.
Is it possible there might be a corner case where one card passes DirectX test and the other passes the WDDM test but neither card is fully compliant?
