### ISSUE TITLE
Improving the user interface

### ISSUE THREAD

**Issue by Oleg-Chashko** [rcmaehl/WhyNotWin11#271]
Desirable, but not necessary.
The interface will be, more symmetrical and more beautiful.

1. Replace the letter "X" with a cross and a smaller size.
2. Double lines of text, require vertically alignment.
3. Preferably a horizontal line.
4. Align "Localization Author" data vertically.
5. Group the icons, down vertically.
6. Lift up, header text.

**Currently:**
<img width="555" alt="Screen Shot #2" src="https://user-images.githubusercontent.com/62497891/123914255-7e6bcc80-d97f-11eb-9615-8ec0bef6322c.png">

**Example:**
<img width="555" alt="Screen Shot #1" src="https://user-images.githubusercontent.com/62497891/123917623-49617900-d983-11eb-9ada-3a59294b6318.png">

**Comment by PierreGrillet** [comment]
4. should not be reduced to a single line : if there are multiple translators, their name will be warp in two lines. Yet it would be nice that the first line was aligned with the CPU description line.

**Comment by Oleg-Chashko** [comment]
To put it simply, I don't understand why the names of the translators are written here.
Make an "About" button and put everyone who participated in this project there, if that's what the author of the program wants.

**Comment by PierreGrillet** [comment]
That make sense.

**Comment by rcmaehl** [comment]
1. Sure
2. Can't do this as a multiline label control, might switch to flat buttons
3. Can't add a line on just the bottom without adding it to the right, or well, I might be able to as an image but it'd be janky
4. Will improve slightly but needs to be aligned with CPU Name because it can multiple multiple lines of Translators
5. Sure
6. Sure

**Comment by micwoj92** [comment]
_offtopic_
About 4. I think we need to standardize how people credit themselves, for example either real name or github username.

**Comment by Oleg-Chashko** [comment]
@rcmaehl 
Do as you see fit and possible. The main thing is that you like it.
The only thing I don't understand is point number 4. Why see the authors of the localization of the program?
For example, I did localization, just for fun, to help. Not so that my name would be in front of everyone, that's how good I am. :)

**Comment by micwoj92** [comment]
Yeah, maybe better change authors to comments/metadata, in future some translation might get multiple authors so the UI will be really busy there.

**Comment by Oleg-Chashko** [comment]
> Yeah, maybe better change authors to comments/metadata, in future some translation might get multiple authors so the UI will be really busy there. (or about tab/page)

I totally agree with you! (or about tab/page)

P.S.: Especially when the number of localization authors increases. It will look like a list of localizers who died translating this program. It may turn into a tombstone instead of a program. I hope you know what I mean. :)

**Comment by htcfreek** [comment]
Tabbed User interface could be interesting for implantation of #32 too.

Maybe something like this: Scan Summary | Scan Details | About this app

**Comment by rcmaehl** [comment]
Potentially, was sent a concept for a dark mode theme by @botflakes

**Comment by botflakes** [comment]
I really need to change my handle on GitHub :D

**Comment by hooddy** [comment]
PLeasew add language switrch into app settings. Right now i forced to remove russian lang. I need English only.

**Comment by micwoj92** [comment]
@hooddy #195

**Comment by htcfreek** [comment]
> Potentially, was sent a concept for a dark mode theme by @botflakes 
> 
> ![image](https://user-images.githubusercontent.com/716581/124056172-39817d80-d9f3-11eb-90a1-44917327bac5.png)
> 
> Font is 0xCDCDCD
> Side and footer is 0x222222
> Main is 0x333333
> 
> WIll use this to improve Dark Mode in a later release. I think I like the icons arranged this way too.

We shouldn't color checks in progress with yellow. Let's choose another color for check in progress.

**Comment by htcfreek** [comment]
@rcmaehl 
- Would be great to define constants for the different state symbols that ee only have to update one place in code.
- Not sure how theming works atm. But imo we should have theme inis which define colors by element type.

**Comment by Oleg-Chashko** [comment]
Very nice concept. 👍🏻 
I added an "About Us" button (for Localizers of this program, etc.).
Added "Settings" button (Localization Selection, Design Themes, etc.).

**Example:**
![124056172-39817d80-d9f3-11eb-90a1-44917327bac5](https://user-images.githubusercontent.com/62497891/124156093-7b63ff80-da97-11eb-8e89-e68cd7223c1c.png)

**Comment by htcfreek** [comment]
> Very nice concept. 👍🏻
> I added an "About Us" button (for Localizers of this program, etc.).
> Added "Settings" button (Localization Selection, Design Themes, etc.).
> 
> **Example:**
> ![124056172-39817d80-d9f3-11eb-90a1-44917327bac5](https://user-images.githubusercontent.com/62497891/124156093-7b63ff80-da97-11eb-8e89-e68cd7223c1c.png)

Not sure if the "About us" icon is the best choice. Maybe something like this ℹ would be better.

**Comment by rcmaehl** [comment]
For licensing reasons, it'll likely be one of these:

![image](https://user-images.githubusercontent.com/716581/124158612-20ff7a80-da68-11eb-960c-339ff376e90b.png)

**Comment by Oleg-Chashko** [comment]
@htcfreek 
Icons, this is an example (the author of the program, it chooses what he likes), I just showed the location on the interface of the program.

**Comment by Oleg-Chashko** [comment]
> For licensing reasons, it'll likely be one of these:
> 
> ![image](https://user-images.githubusercontent.com/716581/124158612-20ff7a80-da68-11eb-960c-339ff376e90b.png)

If I may, I'm in favor of #2.

**Comment by rcmaehl** [comment]
I don't think there's enough information for an About Page, and enough settings for a settings page, so I'm going to combine them into one child GUI. 

Ideas for icon:

![image](https://user-images.githubusercontent.com/716581/124225652-d4eb1f00-dad5-11eb-8bc1-9002a436fece.png)

**Comment by htcfreek** [comment]
My vote for 12 or14. 👍

**Comment by rcmaehl** [comment]
14 is too arty, but I'd be fine with 12. @Oleg-Chashko  @micwoj92 opinions?

**Comment by Oleg-Chashko** [comment]
I'm in favor of: 12 👍🏻

**Comment by rcmaehl** [comment]
![image](https://user-images.githubusercontent.com/716581/124228472-4036f000-dada-11eb-97c2-52fbfb229282.png)

Now I just need to set up content for the settings page.

**Comment by Oleg-Chashko** [comment]
I'd like to see the settings page when it's ready.

P.S.: The design of the settings button is slightly different from the rest of the buttons. But this is for the best, because visually you pay attention to it. And you don't have to look for it in the program interface.

**Comment by htcfreek** [comment]
> ![image](https://user-images.githubusercontent.com/716581/124228472-4036f000-dada-11eb-97c2-52fbfb229282.png)
> 
> Now I just need to set up content for the settings page.

- Lang selection
- Color mode
- Main contributors
- Credits for includes
- Translators

**Comment by micwoj92** [comment]
I think that settings cog icon looks much better.

**Comment by Oleg-Chashko** [comment]
@micwoj92

I agree with you, I quote: The design of the settings button is slightly different from the rest of the buttons.
Which gear do you like? Suggest your option.

**Comment by rcmaehl** [comment]
@micwoj92 I'm off to bed, if you can get a consensus on a different icon, go ahead and merge it in.

**Comment by micwoj92** [comment]
> Which gear do you like? Suggest your option.

I'm not the best when it comes to UI, couple look fine to me. But I think that the best one would be one looking close to what Windows settings application on win10 uses, so the "settings" one, I think it needs to be rotated a bit.

**Comment by Oleg-Chashko** [comment]
@micwoj92 
Please choose from this list and write the numbers. A couple of options are desirable.

![124225652-d4eb1f00-dad5-11eb-8bc1-9002a436fece](https://user-images.githubusercontent.com/62497891/124236388-ae010d00-db16-11eb-8ff3-2d48ca762250.png)

**Comment by micwoj92** [comment]
I meant the "setting" one, no nmber, but 4 and 17 also look fine to me.

**Comment by Oleg-Chashko** [comment]
Let's come to a single option.


- **12 number:**

![124228472-4036f000-dada-11eb-97c2-52fbfb229282](https://user-images.githubusercontent.com/62497891/124240213-d25ee880-db1a-11eb-8882-4e283c78bbdb.png)

---
- **13 number:** But I think that the best one would be one looking close to what Windows settings application on win10 uses, so the "settings" one, I think it needs to be rotated a bit.

![13](https://user-images.githubusercontent.com/62497891/124239139-adb64100-db19-11eb-8819-605d7988e742.png)

---
- **4 number:**

![4](https://user-images.githubusercontent.com/62497891/124239321-dd654900-db19-11eb-8fdb-300ee89f4b0c.png)

---
- **17 number:**

![17](https://user-images.githubusercontent.com/62497891/124239370-e6eeb100-db19-11eb-8471-dc5cef5eeb53.png)

---
- **9 number:**

![9](https://user-images.githubusercontent.com/62497891/124239409-f3730980-db19-11eb-872b-fc5db9e80af7.png)

**Comment by sanny-io** [comment]
I think 4 fits in with the others the most.

**Comment by micwoj92** [comment]
Yeah, after seeing this mockup, definitely 4.

W dniu piątek, 2 lipca 2021 sanny.io ***@***.***> napisał(a):
> I think 4 fits in with the others the most.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/V3uGy2Dre5pH1LaLrYXmBtdhu6NTC7r_aTIZwwx0gV10UdEtpknxiXYHrn5QwueXKvVmH8ISWkfiAqDn1-cKzR2j2DfUaj45Inz-P3pTPohrYszX1fICUyUYP1n8v4q2f3fwZ1Cl3uR_5hrlXGDqdclkHBM8B_RyUkDyTHO29wjCBukLjj9uuEJkYieHOE96JRyb4K3jIhjfY4CKAAvjbP93bZAf19sFY8vA5Hb0WQ=s0-d-e1-ft#https://github.com/notifications/beacon/AK3YG4TUTTZKMSUXQJNXMQ3TVVWSHA5CNFSM47RWVOP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGQC534A.gif>

**Comment by Oleg-Chashko** [comment]
A small request, slightly reduce the size of the font (in the red rectangle). 
Since the same font size is used in the program header (in the green rectangle).

![124239321-dd654900-db19-11eb-8fdb-300ee89f4b0c](https://user-images.githubusercontent.com/62497891/124270159-20d0af00-db3c-11eb-9a14-18ff0a6229d0.png)

**Comment by Oleg-Chashko** [comment]
@rcmaehl, @micwoj92 

**Request and Question:**
1. The red zone must not be sensitive to pressure.
 Only the green area, should be, sensitive to pressure, equal to the length of the inscription. 
 _It was discovered by accident, tried to click on the cross to exit the program, and as a result came through a link to GitHub._
2. Please explain why to make two identical links to GitHub site, located from each other in a couple of centimeters (green arrow). I'm sorry, I don't understand this.

<img width="607" alt="Screen Shot 2021-07-03 at 19 37 48" src="https://user-images.githubusercontent.com/62497891/124363508-ec441c80-dc3b-11eb-9bbc-7787ec71a956.png">

**Comment by rcmaehl** [comment]
![image](https://user-images.githubusercontent.com/716581/124505517-af8d3800-dd97-11eb-92b5-9332dbb5b9fa.png)

Do I need to move the existing section over? Or maybe switch to a tooltip on hover (and add info that it exists?)

**Comment by Oleg-Chashko** [comment]
![124505517-af8d3800-dd97-11eb-92b5-9332dbb5b9fa](https://user-images.githubusercontent.com/62497891/124506093-3ad3f100-ddcb-11eb-87a0-17dda85217de.png)

**Comment by rcmaehl** [comment]
Either that or 
![image](https://user-images.githubusercontent.com/716581/124506407-95ecf000-dd99-11eb-9a5d-4128214f0ca6.png)

Maybe removing the "Results based on currently known requirements"

**Comment by Oleg-Chashko** [comment]
The icons are clearer and will be understood in any country without translation. And the interface is not overloaded.

**Comment by rcmaehl** [comment]
> The icons are clearer and will be understood in any country without translation. And the interface is not overloaded.

Maybe not in English...

**Comment by rcmaehl** [comment]
![image](https://user-images.githubusercontent.com/716581/124507107-13653000-dd9b-11eb-821c-12dd9b2ec7dc.png)

Slight adjustment

**Comment by Oleg-Chashko** [comment]
Important condition, the distance on the right and left must be the same!
![124505517-af8d3800-dd97-11eb-92b5-9332dbb5b9fa](https://user-images.githubusercontent.com/62497891/124507172-87203080-ddcd-11eb-9b2b-5b8023d672a1.png)

**Comment by Oleg-Chashko** [comment]
> Slight adjustment
Totally agree with you.

**Comment by Oleg-Chashko** [comment]
> > The icons are clearer and will be understood in any country without translation. And the interface is not overloaded.
> 
> Maybe not in English...

I have to work with people. And I can say with certainty that people do not like to count any text.

**Comment by htcfreek** [comment]
> ![image](https://user-images.githubusercontent.com/716581/124507107-13653000-dd9b-11eb-821c-12dd9b2ec7dc.png)
> 
> Slight adjustment

Please add a bit space between result and info icon.

**Comment by rcmaehl** [comment]
![image](https://user-images.githubusercontent.com/716581/124508956-ed418f00-dd9e-11eb-8c16-1530d929ee80.png)
There, even in 3 places

**Comment by Oleg-Chashko** [comment]
@rcmaehl 

Important condition, the distance on the right and left must be the same!

![124507172-87203080-ddcd-11eb-9b2b-5b8023d672a1](https://user-images.githubusercontent.com/62497891/124509441-4545b900-ddd2-11eb-8d56-d90966a9bff0.png)

**Comment by Oleg-Chashko** [comment]
@rcmaehl 

I'm sorry for interrupting. Will you change something?
https://github.com/rcmaehl/WhyNotWin11/issues/271#issuecomment-873448849

**Comment by rcmaehl** [comment]
> @rcmaehl
> 
> I'm sorry for interrupting. Will you change something?
> [#271 (comment)](https://github.com/rcmaehl/WhyNotWin11/issues/271#issuecomment-873448849)

Was removed in https://github.com/rcmaehl/WhyNotWin11/issues/271#issuecomment-874277194 test

Just commited 0720ebe if you want to see a test build, bit busy with work but will continue on UI in a couple hours

**Comment by Oleg-Chashko** [comment]
@rcmaehl 
Thanks for answering. Take your time, work calmly. I just asked. I won't disturb you. :)

**Comment by rcmaehl** [comment]
Please review the latest dev build and advise on tips.

**Comment by Oleg-Chashko** [comment]
> Please review the latest dev build and advise on tips.

@rcmaehl 

Download latest stable release -> It starts and runs ok.
Download latest testing release -> Runs, but doesn't work.
Compiling -> Runs, but doesn't work.

<img width="361" alt="Screen Shot 2021-07-08 at 08 54 53" src="https://user-images.githubusercontent.com/62497891/124878407-5ce89180-dfcc-11eb-8a78-d2ccdd81b601.png">

---
AutoIt v.3.3.14.5
Windows v.11 Dev 22000.51 (Juni 2021)
VMware Fusion Pro v.12.1.2 (17964953)

---

Example:

**CPU Name=The CPU you have installed in your computer. Compatibility is subject to change. Requires physical replacement on Desktops; Not replaceable on Laptops.**

1. CPU Name=The CPU you have installed in your computer. Compatibility is subject to change. -> 100% 👍🏻
2. Requires physical replacement on Desktops. -> 50/50: Unfortunately, not quite right.
3. Not replaceable on Laptops. -> 50/50: Unfortunately, not quite right.

Better, 100% correct information.
I would avoid inaccurate information. So that there are no accusations from the user. That the program has misled him.
1. There are desktop computers where the processor is plugged (Soldered) into the motherboard and the bios is locked by the manufacturer.
2. In a desktop computer you might have to change not only the cpu but also the bios. And maybe even the motherboard and memory, the cooler and so on.
3.  In cheap and old laptops you could replace the CPU and memory. In the newer cheap laptops , it all depends on the level of "Marketing".

This is just one example. I think you understand what I wanted to say.

**Comment by htcfreek** [comment]
@rcmaehl 
1. The msgbox title should be the app title and not the on in screenshot of @Oleg-Chashko .

2. Latest dev build failed to run with `array var out of dimension`!!

**Comment by Oleg-Chashko** [comment]
@rcmaehl

CPU Name=Requires physical replacement on Desktops; Not replaceable on Laptops. -> Please consult your device manual for details.
CPU Cores= Requires physical replacement on Desktops; Not replaceable on Laptops. -> Please consult your device manual for details.
CPU Speed= Requires physical replacement on Desktops; Not replaceable on Laptops. -> Please consult your device manual for details.
RAM= Physically upgradeable in high end Laptops. -> Please consult your device manual for details.
Storage= upgradeable in high end Laptops. -> Please consult your device manual for details.

P.S.: Or something similar, at your discretion.

**Comment by Oleg-Chashko** [comment]
Example:
CPU Speed=The rate that your CPU processes tasks.

Preferably, take information from official sources.

The clock speed measures the number of cycles your CPU executes per second.
https://www.intel.com/content/www/us/en/gaming/resources/cpu-clock-speed.html

P.S.: This is just one example. I think you understand what I wanted to say.

**Comment by Oleg-Chashko** [comment]
@rcmaehl

Results Based on Currently Known Requirements! -> Switch to a tooltip on hover "I".
We need to make a list: CPU and video cards and CPUs with integrated video cores. 
In order for the computer owner to know what is required to upgrade to Windows 11.
The list should be 100% correct so the user won't complain! Example: Oops, i bought CPU and it doesn't fit.

P.S.: Or something similar, at your discretion.

Example:

![124508956-ed418f00-dd9e-11eb-8c16-1530d929ee80](https://user-images.githubusercontent.com/62497891/124914463-a945c880-dff0-11eb-9d92-068e9578e0ea.png)

**Comment by Oleg-Chashko** [comment]
@rcmaehl 

Can you post a working the latest dev build?

**Comment by rcmaehl** [comment]
https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip will always link to whatever the newest dev build is

**Comment by Oleg-Chashko** [comment]
@rcmaehl

_Can you post a **working** the latest dev build?_
I asked for a working version of the build. And this build does not work.

<img width="329" alt="Screen Shot 2021-07-08 at 18 00 50" src="https://user-images.githubusercontent.com/62497891/124955166-23894380-e017-11eb-8c3a-97f4236813d3.png">

**Comment by rcmaehl** [comment]
> @rcmaehl
> 
> _Can you post a **working** the latest dev build?_
> I asked for a working version of the build. And this build does not work.
> 
> <img alt="Screen Shot 2021-07-08 at 18 00 50" width="329" src="https://user-images.githubusercontent.com/62497891/124955166-23894380-e017-11eb-8c3a-97f4236813d3.png">

It looks like you're on Windows 11. Let me remove the check temporarily

**Comment by Oleg-Chashko** [comment]
@rcmaehl

Yes it is Windows 11. I'm going to uninstall Windows 11 and install Windows 10 so you don't have to change anything. I don't use the Windows operating system anyway.

Windows v.11 Dev 22000.51 (Juni 2021)
VMware Fusion Pro v.12.1.2 (17964953)

**Comment by Oleg-Chashko** [comment]
@rcmaehl

At this point in time:

<img width="1035" alt="Screen Shot 2021-07-08 at 20 02 53" src="https://user-images.githubusercontent.com/62497891/124976066-111b0400-e02f-11eb-9897-b6fd7c692884.png">

Would like:

<img width="814" alt="Screen Shot 2021-07-08 at 20 04 21" src="https://user-images.githubusercontent.com/62497891/124976087-16784e80-e02f-11eb-9179-862f4efc98a3.png">

**Comment by rcmaehl** [comment]
Yeah, I'll need to add support for new lines \n like I did in NotCPUCores. Expect it Soon:TM:

**Comment by Oleg-Chashko** [comment]
Maybe sometime in the future, add a resolution check for Display and Internet connection?
These are requirements for Windows 11 Home.
<img width="786" alt="Screen Shot 2021-07-09 at 12 19 08" src="https://user-images.githubusercontent.com/62497891/125064282-c6da6700-e0b0-11eb-99ec-c8361accfae2.png">

**Comment by micwoj92** [comment]
https://github.com/rcmaehl/WhyNotWin11/issues/116

**Comment by Oleg-Chashko** [comment]
Maybe that's enough of a description?

- Architecture: Windows 11 requires a 64-bit processor and operating system. If you are using a 32-bit OS but your CPU supports 64-bit, you need to wipe the drive and reinstall Windows.

- Boot Mode: Windows 11 is UEFI-only. Legacy BIOS is not supported.

- CPU Compatibility: Windows 11 requires a compatible 64-bit processor:
• Intel Core 8th Gen and above.
• AMD Ryzen based on Zen+ and above (except Ryzen 3 2200G and Ryzen 5 2400G).

- CPU-Core Count: The number of tasks your CPU can process at once. Threads are the virtual components or codes, which divides the physical core of a CPU into virtual multiple cores.

- CPU Frequency: The clock speed measures the number of cycles your CPU executes per second.

- DirectX + WDDM2: Windows 11 requires a GPU that's compatible with DirectX 12 and later.

- Disk Partition Type: The format that your data is stored on your Disk. Non-GPT results can be fixed using Microsoft's MBR2GPT tool.

- RAM Installed: Windows 11 requires at least 4GB of RAM.

- Secure Boot: Windows 11 requires Secure Boot.

- Storage Available: Windows 11 requires at least 64GB of storage.

- TPM Version: Windows 11 requires, Trusted Platform Module (TPM) version 2.0.

- Screen resolution: Windows 11 requires a display with a 720p resolution (1280 x 720) and higher.

- Internet connection: Windows 11 Home edition requires internet connectivity and a Microsoft account to complete device setup on first use.

**Comment by Oleg-Chashko** [comment]
@rcmaehl

- The distances are preferably the same.
<img width="326" alt="Screen Shot 2021-07-11 at 09 29 43" src="https://user-images.githubusercontent.com/62497891/125187047-ed71dc80-e22d-11eb-9275-702616c95801.png">

---
- It is preferable that the alignment be as before.
<img width="345" alt="Screen Shot 2021-07-11 at 09 20 29" src="https://user-images.githubusercontent.com/62497891/125187107-3f1a6700-e22e-11eb-9ee8-9885fc9069fb.png">

---
- Preferably, the alignment should be the same on each line.
- Preferably, the quotation marks should be double.
<img width="608" alt="Screen Shot 2021-07-11 at 09 16 30" src="https://user-images.githubusercontent.com/62497891/125187280-1050c080-e22f-11eb-811b-0d8c8f79f06c.png">

**Comment by bovirus** [comment]
@rcmaehl 

"Check update" translated is truncated as text.
I proposse to move this string in the new position on bottom and icnrease text string width

"Architecture" string is not translated and not available in language file.
Please add to the language file.

CPU/GPU on bottom right for me is not reported right (the strings about CPU seems in English).
For me the info should be reported as
CPU = CPU model
GPU = GPU mdoel

**Original screen**
![image](https://user-images.githubusercontent.com/1262554/125187218-c962cb00-e22e-11eb-9772-5f14239c73a2.png)

New GUI with my proposals
![image](https://user-images.githubusercontent.com/1262554/125187395-bac8e380-e22f-11eb-8e6a-23417850bb14.png)

**Comment by bovirus** [comment]
@rcmaehl 

**Long multiperiod string with new line between period.**

Pelase consider for long string multiperiod to use  a new line to separate period.
This improve readbility. Ex.

TPM=A security module used by Windows. All modern AMD CPUs contain one; Some modern Intel CPUs contain one. Check your BIOS/UEFI settings. Refer to your motherboard manual.

The string

A security module used by Windows. All modern AMD CPUs contain one; Some modern Intel CPUs contain one. Check your BIOS/UEFI settings. Refer to your motherboard manual.
 
could be like

 A security module used by Windows. 
All modern AMD CPUs contain one. 
Some modern Intel CPUs contain one. 
Check your BIOS/UEFI settings. 
Refer to your motherboard manual.
