### ISSUE TITLE
Optimize text length and reduce size

### ISSUE THREAD

**Issue by bastianfbr** [rcmaehl/WhyNotWin11#275]
The title and some fields have a lot of words, even though it is quite understandable, not everything is displayed well.

The font size should be optimized according to the length of the text. 

--> Title, fields (left and right), updates (bottom right) and translation note next to it
![image](https://user-images.githubusercontent.com/29505634/123931455-cf37f100-d990-11eb-9a57-f08987356688.png)

**Comment by PierreGrillet** [comment]
The French text have already been fixed with #226. 
I agree with you for the font size optimization. However it seems it is not the priority.

**Comment by micwoj92** [comment]
@bastianfbr 
open %localappdata%\WhyNotWin11\langs\version in notepad and set it to 0.0.0.0. Then download latest dev change and test.

@PierreGrillet @bastianfbr 
Open prs for changes in translation. It is now possible to change font settings in translation files.

**Comment by PierreGrillet** [comment]
@micwoj92 Can you please tell me more about the font option ? Is there an example ?

**Comment by micwoj92** [comment]
https://github.com/rcmaehl/WhyNotWin11/commit/c44fda4b5535ff0f4b7fd644142b5cd7e42add10
This commit added this, I haven't tested myself but I think that if you add one of these to your translation:
![image](https://user-images.githubusercontent.com/45581170/123952862-de299e00-d9a6-11eb-8ca8-5b7e50790385.png)

then it should work. But I am unsure about syntax. I think best to wait until @rcmaehl sees this.

**Comment by micwoj92** [comment]
@PierreGrillet here updated
https://github.com/rcmaehl/WhyNotWin11/commit/9fb3bf65d05944b97c9e33060db611a8866fb77e
