### ISSUE TITLE
4-bit CPU detected when compiled for x86

### ISSUE THREAD

**Issue by XenoPanther** [rcmaehl/WhyNotWin11#28]
So I decided to see how the app would react when installed on Insider Build 21390 x86 and while all other detections are fine. The CPU reports as 4-bit
![unknown](https://user-images.githubusercontent.com/81916167/123512781-46177600-d681-11eb-81b3-047c489791f9.png)

**Comment by htcfreek** [comment]
@rcmaehl 
You use `AdressWidth` property. I suggest to use `Architecture` instead and maybe convert ot by using a switch case to a numeric value.
