### ISSUE TITLE
Package release version in Zip file for easier download

### ISSUE THREAD

**Issue by m4ttyj** [rcmaehl/WhyNotWin11#280]
Would it be possible to have the most recent version available in a ZIP file. With this app becoming more prominent due to media and blogs etc (Which is great), more and more none-technical users are downloading it. 

Some browsers (inc edge) will block the download of the EXE because its unsigned, leading users to believe they are downloading something dangerous. A Zip file would get round this.

**Comment by m4ttyj** [comment]
![Screenshot 2021-06-30 111844](https://user-images.githubusercontent.com/13242159/123944360-f55f9000-d994-11eb-9162-50e09899b563.png)

**Comment by micwoj92** [comment]
This will be easy to do in CI, just need approval from @rcmaehl because it changes the way we release, so his word and decission on this is final.

**Comment by mlipok** [comment]
it was disscused here:
https://github.com/rcmaehl/WhyNotWin11/discussions/274#discussioncomment-942636

**Comment by micwoj92** [comment]
@mlipok now I understand, please open another issue for that with detailed description as this is not the same as this one mentioned here. Could you also post screenshot of your version if you post new post?

**Comment by rcmaehl** [comment]
@micwoj92 Go ahead and zip it but it'll break some file mirror sites due to the file type change 😆

**Comment by micwoj92** [comment]
Zip exes separately or do same as CI with only one download?

**Comment by rcmaehl** [comment]
> Zip exes separately or do same as CI with only one download?

1 Single Exe

**Comment by m4ttyj** [comment]
Maybe offer both. The open EXE and a ZIP?

**Comment by micwoj92** [comment]
Then I would do 1. unzipped exes 2. zipped everything, same as CI.

**Comment by rcmaehl** [comment]
> Then I would do 1. unzipped exes 2. zipped everything, same as CI.

SGTM

**Comment by micwoj92** [comment]
In future versions the published files will look like this
zip contains both .exe files and shasum file
![image](https://user-images.githubusercontent.com/45581170/124002323-e0efb780-d9d5-11eb-94c9-11f439988bf9.png)
