### ISSUE TITLE
Another DX12 detection issue

### ISSUE THREAD

**Issue by peterlukerow** [rcmaehl/WhyNotWin11#282]
In the previous version the disk partition type passed and said GPT was detected. On this new version the same check on the same machine fails saying GPT not detected.

I have 3 drives connected to computer 2 x SSD (C and D) and external USB drive (F).
According to Windows disk management tool C - which is the windows/boot drive - is GPT partition type and D and F are MBR and don't the option to convert to GPT is disabled.

Seems like this check should pass as long as the boot drive is GPT shouldn't it?

**Comment by micwoj92** [comment]
Could you test with latest test version? Link in readme

**Comment by fiftydinar** [comment]
> 
> 
> Could you test with latest test version? Link in readme

Test version fixed the GPT detection, but it broke WDDM detection.

Test version on the left, stable version on the right.
![Clipboarder 2021 06 30](https://user-images.githubusercontent.com/65243233/123955118-8b051a80-d9a9-11eb-83e9-8334cabf617b.png)

**Comment by micwoj92** [comment]
Could you attach output of dxdiag as dxdiag.txt? The DX12 detection was changed recently.

**Comment by micwoj92** [comment]
I've changed title accordingly.

**Comment by rcmaehl** [comment]
"Another DX12 detection issue" 😔

**Comment by micwoj92** [comment]
Rewrite to support Vulkan

**Comment by rcmaehl** [comment]
> Rewrite to support Vulkan

~~Vulkan~~ Romulan

**Comment by pakass** [comment]
Same issue here. That's the DxDialog:

[DxDiag.txt](https://github.com/rcmaehl/WhyNotWin11/files/6741506/DxDiag.txt)

**Comment by rcmaehl** [comment]
> Same issue here. That's the DxDialog:
> 
> [DxDiag.txt](https://github.com/rcmaehl/WhyNotWin11/files/6741506/DxDiag.txt)

This is a known issue with the 760, and likely other cards that were released as DX11 and forced to "DX12 API"

You can see the issue on Nvidia's own website even:

https://www.nvidia.com/en-gb/geforce/graphics-cards/geforce-gtx-760/specifications/
vs
https://www.nvidia.com/en-us/geforce/graphics-cards/geforce-gtx-760/specifications/

What does GPU-Z say for this card?

**Comment by peterlukerow** [comment]
![image](https://user-images.githubusercontent.com/28951140/123986753-7d0dc480-d9be-11eb-8243-3ac62eb6ffa7.png)

Test results above, it now says 1/3 drives have GPT.  My Asus TPM 2.0 module arrived today and will install later so fingers crossed the TPM check will pass after that. DirectX is fine for me on GTX 2060, from above comments because it's not that old.

**Comment by rcmaehl** [comment]
Fixing this shortly to pass if either DDI or FeatureLevel is >=12
