### ISSUE TITLE
[Github Workflow] WIP label

### ISSUE THREAD

**Issue by htcfreek** [rcmaehl/WhyNotWin11#305]
A lable to mark issues where work is in progress or which are in PR would be good.

**Comment by micwoj92** [comment]
You mean this? For PR there is already draft and you can also tag issues in prs.
![image](https://user-images.githubusercontent.com/45581170/124046877-38f8df00-da13-11eb-8906-ac6c356e207c.png)

**Comment by htcfreek** [comment]
For me it's really difficult to see  on which things @rcmaehl is working. He doesn't use PRs and don't label the issues as in progress

**Comment by micwoj92** [comment]
Technically easy to do, but I don't know his workflow, so assigning to him.

**Comment by rcmaehl** [comment]
Fine

**Comment by htcfreek** [comment]
I think we should rename label to `Work-in-progress` which is better understandable for other contributors who don't know the meaning of "wip".

**Comment by rcmaehl** [comment]
> I think we should rename label to `In-progress` which is better understandable for other contributors who don't know the meaning of "wip".

Updated

**Comment by micwoj92** [comment]
> I think we should rename label to `In-progress` which is better understandable for other contributors who don't know the meaning of "wip".

Labels can have description, hovering mouse shows it
![image](https://user-images.githubusercontent.com/45581170/124156304-bfef9b00-da97-11eb-84bb-6efb48a3a60d.png)

**Comment by htcfreek** [comment]
Another good lable is "Fix-Committed".

**Comment by micwoj92** [comment]
There already is "Patched?"

**Comment by micwoj92** [comment]
But to be honest I don't think it's needed. Usually issue is closed when the "Fix is Committed"

**Comment by htcfreek** [comment]
okay.
