### ISSUE TITLE
Figure out Release Bug

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/WhyNotWin11#306]
**Describe the bug**
CI uploaded the wrong artifact to the release tag

**To Reproduce**
1. Push Changes
2. 1 minute later create release

**Expected behavior**
Latest Push is Built and uploaded

**Comment by rcmaehl** [comment]
Tagging @Margen67 

This is why I don't trust robots

**Comment by micwoj92** [comment]
I would not blame CI. When creating tag, you can specify branch and even commit. This was human mistake (2 times in a row) unless you prove me otherwise

![image](https://user-images.githubusercontent.com/45581170/124068949-b0daff80-da3b-11eb-99fe-672e3c904d8c.png)

**Comment by micwoj92** [comment]
Because when I clicked on (now non existing) 2.3.0.2 it showed commit from my (now also non existing) branch.

**Comment by micwoj92** [comment]
Here, latest commit before release, and 2.3.0.2
![image](https://user-images.githubusercontent.com/45581170/124069245-26df6680-da3c-11eb-8460-5d17adadeeee.png)

Where 2.3.0.2 is the same as my testing branch
![image](https://user-images.githubusercontent.com/45581170/124069306-3fe81780-da3c-11eb-858b-9042264ac33b.png)

**Comment by rcmaehl** [comment]
Well it was a valuable lesson. A lot of them this week.

**Comment by micwoj92** [comment]
Ahem, we all should sleep more.
