### ISSUE TITLE
Dark theme missed icons on left side

### ISSUE THREAD

**Issue by FadeMind** [rcmaehl/WhyNotWin11#308]
**Describe the bug**
Dark theme missed icons on left side.

**To Reproduce**
1. Enable Dark Theme in Windows
2. Launch latest WhyNotWin11 app. Look on top left side. 
3. Not reverted icons.

**Expected behavior**
Reverted icons.

**Screenshots**
![20210701-1625113733](https://user-images.githubusercontent.com/9846948/124064877-f85e8d00-da35-11eb-83a3-63c87a0dbeba.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 
 - Browser Edge Chromium latest
 - Version: latest

**Additional context**
none

**Comment by DanGM96** [comment]
- Latest build: Icons are now rearranged vertically (not sure if intentional).
- The background being so black and the font color being full white makes it very hard on eyes.
I would like to leave this article on [GitHub's default dark mode](https://uxdesign.cc/githubs-dark-mode-is-too-dark-f6ab415cd4d4) that has good examples of Other Dark Mode Site Palettes.

**Comment by savaloi** [comment]
This appears to happen even when 'default windows mode' is set to 'Dark', and 'default app mode' is set to 'Light'.
Even setting both back to 'Light' and re-running the app results in the same black window... Thought this might help
Tested on the latest v2.3.0.5 and deleted the content from %localappdata%\WhyNotWin11 - still no good.

Not sure Dark mode in Windows is the issue?
I'm on Win10 1909 FWIW

![image](https://user-images.githubusercontent.com/20825757/124702701-2c551900-df34-11eb-93bc-17a8df4b2215.png)

**Comment by rcmaehl** [comment]
> This appears to happen even when 'default windows mode' is set to 'Dark', and 'default app mode' is set to 'Light'.
> Even setting both back to 'Light' and re-running the app results in the same black window... Thought this might help
> Tested on the latest v2.3.0.5 and deleted the content from %localappdata%\WhyNotWin11 - still no good.
> 
> Not sure Dark mode in Windows is the issue?
> I'm on Win10 1909 FWIW
> 
> ![image](https://user-images.githubusercontent.com/20825757/124702701-2c551900-df34-11eb-93bc-17a8df4b2215.png)

Please try 
https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

**Comment by Taomyn** [comment]
Just downloaded latest, still not correct in when OS in dark mode - in light mode it's fine and the icons are in black

![image](https://user-images.githubusercontent.com/4365929/125187114-4b062900-e22e-11eb-9044-3ff5162ec9f2.png)

**Comment by micwoj92** [comment]
@Taomyn this is correct.

**Comment by micwoj92** [comment]
And it's actually solved now as far as I know so I will close it.

**Comment by Taomyn** [comment]
> And it's actually solved now as far as I know so I will close it.

Sorry, just realised I pasted the wrong screen shot as the first time I tried it I was running an older version

![image](https://user-images.githubusercontent.com/4365929/125192065-1605d080-e246-11eb-8e36-ab78a7ff34bb.png)
![image](https://user-images.githubusercontent.com/4365929/125192069-19995780-e246-11eb-83c5-d1d510303f61.png)

**Comment by micwoj92** [comment]
@Taomyn Are you visually impaired or maybe are your monitor settings wrong? I can see icons in both of your screenshots and in initial bug report they are black squares.

**Comment by Taomyn** [comment]
> @Taomyn Are you visually impaired or maybe are your monitor settings wrong? I can see icons in both of your screenshots and in initial bug report they are black squares.

No, but I have 3 screens if I place it on each one there is nothing unless I kick the contrast up to stupid levels, but it's still black on dark grey. This is not a good look, why are the icons not white or a light grey which would at least be the opposite of the black.

**Comment by micwoj92** [comment]
Then this is another issue "[enchancement] theme aware icons" or something like this.

**Comment by rcmaehl** [comment]
It's being worked on. They'll eventually use the same color as text
