### ISSUE TITLE
The CI uploads empty artifact when build fails

### ISSUE THREAD

**Issue by micwoj92** [rcmaehl/WhyNotWin11#309]
**Describe the bug**
Build of the application on CI fails, yet it doesn't error, because it can find the empty sha256  file.

**To Reproduce**
1. Make some changes that fail build, commit.
2. Go to Actions tab, latest commit
3. Find artifact which is empty

**Expected behavior**
CI fails upload

**Desktop (please complete the following information):**
N/A

**Additional context**
I don't know how, but this started happening after adding 7zip

**Possible solutions**

1. Use different archiver that fails if it doesn't find files
2. Make the sha generation fail if no files are found
3. Delete the sha file if empty

**Comment by micwoj92** [comment]
Ping @Margen67 
Is there a way in the actions/upload-artifact where if fails if only some files are found? I did read the documentation, but could not find anything like that.

**Comment by Margen67** [comment]
> 
> 
> Ping @Margen67
> Is there a way in the actions/upload-artifact where if fails if only some files are found? I did read the documentation, but could not find anything like that.

`if-no-files-found: error` only errors if it can't find any files at all.
GitHub Actions should exit after the build fails, but `Start-Process` doesn't give an exit code.
The command `sha256sum -b WhyNotWin*.exe > checksums.sha256` creates a file even when it fails.
`7z` overwrites sha256sum's exit code, so the build step "succeeds" and thus upload-artifact runs.

**Comment by micwoj92** [comment]
>  7z overwrites sha256sum's exit code, so the build step "succeeds" and thus upload-artifact runs.

Thanks for confirming, was also thinking about that, that's why I just moved that step to release only, a place where it is needed.
