### ISSUE TITLE
x64 and x86 not giving same DirectX result

### ISSUE THREAD

**Issue by IvanAclu** [rcmaehl/WhyNotWin11#311]
Issue (#270) was closed because the interim build that I tested gave the same result for both executables.
Version 2.3.0.3 reverts to the same behaviour as 2.3.0.1

x64 displays, "DirectX 12 & WDDM 2".
x86 displays, "No DirectX 12, but WDDM 2".

I wonder if there may be an issue when the PC has more than 1 graphics card?

**Comment by micwoj92** [comment]
> I wonder if there may be an issue when the PC has more than 1 graphics card?

As Robert said in closing comment "I'm not sure if there's some sort of display switching enabled causing the card to not report currently, but as soon as that card reports it's versioning you'll get a pass on WhyNotWin11"

**Comment by micwoj92** [comment]
@rcmaehl 
![image](https://user-images.githubusercontent.com/45581170/124311891-bc7b1300-db6e-11eb-838a-fe2bf8f9a8b9.png)

64 bit on right, 32 on left.

**Comment by micwoj92** [comment]
intel igpu reports same on both versions

**Comment by rcmaehl** [comment]
I'm going to assume this is an issue with running a non-native version of dxdiag. I'll add in a warning about this issue but I don't think I can fix this

**Comment by micwoj92** [comment]
Also I've read a bit and it seems like WDDM2+ requires DX12, so couldn't it be hardcoced to pass both then? If you have wddm 2 then you also should have dx 12.

**Comment by rcmaehl** [comment]
If you can provide a link so I could verify that it'd be appreciated. Would make things simpler

**Comment by micwoj92** [comment]
Actually it seems other way around?
https://github.com/MicrosoftDocs/windows-driver-docs/blob/119a8f0435127a41cd215063200f67cd6eb51ed1/windows-driver-docs-pr/display/what-s-new-for-prior-wddm-2-x-versions.md#wddm-21

I fucking hate tech news sites man....
