### ISSUE TITLE
On Windows 8.1 application uses dark theme all the time

### ISSUE THREAD

**Issue by micwoj92** [rcmaehl/WhyNotWin11#314]
**Describe the bug**
Since 2.3.0.3 on Windows 8.1 the application seems to use dark theme. I am using the default "Windows" theme

**To Reproduce**
1. Launch application on Windows 8.1
2. See darkness

**Expected behavior**
White theme

**Screenshots**
Left 2.3.0.1, right 2.3.0.3
![image](https://user-images.githubusercontent.com/45581170/124124788-2618f580-da79-11eb-8b63-e5f7a051b4cd.png)

It's black even on high contrast white theme (yes, I did relaunch)
![image](https://user-images.githubusercontent.com/45581170/124125064-7d1eca80-da79-11eb-83d6-ec5c300629a0.png)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Version 2.3.0.3

**Additional context**
None

**Comment by rcmaehl** [comment]
@micwoj92 Please try the latest build when you have the chance

**Comment by micwoj92** [comment]
I think it gave effect mirrored to desired one
![image](https://user-images.githubusercontent.com/45581170/124154983-4b682c80-da96-11eb-8475-3733c8b4a90c.png)

Here my theming settings
![image](https://user-images.githubusercontent.com/45581170/124155121-6dfa4580-da96-11eb-8712-653be570ac7d.png)

Composition: Windows
Wallpaper: Harmony
Colour: Automatic

And here on white contrast 
![image](https://user-images.githubusercontent.com/45581170/124155412-c03b6680-da96-11eb-978a-023dce63bc87.png)

On black/high contrast settings it looks fine, black/dark window + white/bright text

**Comment by micwoj92** [comment]
As of https://github.com/rcmaehl/WhyNotWin11/commit/38cb18b467ee8c37f86454a7cd43d340e5826f60 looks like this
![image](https://user-images.githubusercontent.com/45581170/124344931-cf74fe00-dbd5-11eb-81a4-b44e7c3a415d.png)

**Comment by rcmaehl** [comment]
~~Moves 8 and 8.1 to Unsupported~~

I'm marking as low for now. The number of 8.1 users is low. The number of 8.1 Dark Mode users are even lower

**Comment by micwoj92** [comment]
I think then that low label needs adjustment in description ;)

**Comment by Androish** [comment]
I have the same issue on windows 10. 

So it seems not only windows 8.1 users are affected

v2.3.0.4

windows 10 21H1

![windows10](https://user-images.githubusercontent.com/16946169/124359406-0d4d4300-dc25-11eb-8b5b-9d370f68d050.PNG)

**Comment by micwoj92** [comment]
@Androish Check latest dev build, the text issue should be fixed there if you are on win10.

**Comment by Androish** [comment]
@micwoj92 That it does, works on v2.3.0.5 latest dev build

**Comment by nbmrjuhneibkr** [comment]
> I'm marking as low for now. The number of 8.1 users is low. The number of 8.1 Dark Mode users are even lower

There is no such thing as system-wide dark mode in Windows 8.1.

**Comment by micwoj92** [comment]
Maybe he meant dark contrast?

**Comment by nbmrjuhneibkr** [comment]
I've never enabled high-contrast mode, but I'm also experiencing this issue, which means that it affects _all_ 8.1 users. I tried latest dev build, it didn't help.

**Comment by rcmaehl** [comment]
> To be honest, I'm kind of shocked to see how something as unimportant as a color scheme can take priority over making the app usable on all supported operating systems. This is the definition of "form over function". This app is supposed to provide accurate technical information, everything else is irrelevant.

Which supported OSes does it not work on?

**Comment by micwoj92** [comment]
I think he meant that the application was unusable on Windows 8.1 due to this theming bug.
