### ISSUE TITLE
Local folder is not created properly by the script

### ISSUE THREAD

**Issue by PierreGrillet** [rcmaehl/WhyNotWin11#321]
**Description**
The Local folder is created, no CPU list file, the local Lang file is empty.

```
$ find Local/WhyNotWin11/
./Langs
./Langs/040C.lang --> empty
./Langs/version
```

**Steps to reproduce**
1. Delete `/WhyNotWin11/Local` folder
2. Double click on *WhyNotWin11.au3*
3. CPU checks fail, GUI not in french

**Expected Local folder**
```
$ find Local/WhyNotWin11/
./Langs
./Langs/0004.lang
(...)
./Langs/540A.lang
./Langs/version
./SupportedProcessorsAMD.txt
./SupportedProcessorsIntel.txt
./SupportedProcessorsQualcomm.txt
```

Is this behavior intended or a bug ?

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2
 - Version 2.3.0.4

**Comment by micwoj92** [comment]
Does this also happen on 2.3.0.3 STABLE release?

**Comment by PierreGrillet** [comment]
Affirm
Also on the 2.3.0.3 STABLE release

**Comment by micwoj92** [comment]
Adding high because it prevents from launching. ping @rcmaehl

**Comment by micwoj92** [comment]
Maybe it is better to have all files embedded into application? Is it possible with AutoIt?

**Comment by PierreGrillet** [comment]
> Adding high because it prevents from launching.
In my case, the app was launching though.
Only the CPU list test was "failling".

**Comment by micwoj92** [comment]
Oh, when you posted "See error" I thought it means error code and the app didn't start

**Comment by PierreGrillet** [comment]
ok, that was misleading.
The app runs fine though. It just not getting files copied right. So translation and CPU list checks both fail.

**Comment by PierreGrillet** [comment]
I think you can remove the high tag 😄

**Comment by micwoj92** [comment]
I mean, high description is "High Priority, Negatively affects functionality for all users "

And this does, no CPU check + no translation.
