### ISSUE TITLE
Specify supported versions of Windows and AutoIt in readme

### ISSUE THREAD

**Issue by micwoj92** [rcmaehl/WhyNotWin11#325]
My suggestion is as follows:

For AutoIt, latest stable and latest beta release.

For Windows I suggest 8.1 and up, and for Windows Server 2012. I know that Windows 7 and server 2008 are still supported  if you pay for ESU (or whatever the name was) but if Microsoft requires paid support, then I think that you @rcmaehl should also demand that.

Reasoning:
Issues like these https://github.com/rcmaehl/WhyNotWin11/issues/127 where operating system is unsupported, it only takes time and benefits minuscule amount of users.
Bug reports should be closed if they can't be reproduced on Windows versions that receive support for free.

**Comment by rcmaehl** [comment]
Resolved.

**Comment by micwoj92** [comment]
> That's a pretty shitty attitude. Windows 8.1 and 10 are also software that you need to pay for. The people that think like you and pay for everything usually own a MacBook with macOS.

There is nothing wrong with free and open source software having paid support. Many companies that produce FOSS use this strategy.

I have never owned MacBook nor used macOS and I don't like Apple.

**Comment by JohnLGalt** [comment]
> 
> 
> > but if Microsoft requires paid support, then I think that you @rcmaehl should also demand that.
> 
> That's a pretty shitty attitude. Windows 8.1 and 10 are also software that you need to pay for. The people that think like you and pay for everything usually own a MacBook with macOS.

He said you had to pay **for support** for Windows 7, not pay for the OS itself.  Read it again.
