### ISSUE TITLE
TPM 1.2 marked as "Missing / Disabled"

### ISSUE THREAD

**Issue by EastArctica** [rcmaehl/WhyNotWin11#326]
**All Checks**
- Download and run the latest build https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip
- Attach a picture of your WhyNotWin11 Results
- https://i.eastarcti.ca/PjN1F.png
- Attach required information based on the category:

**TPM**
- Please run `windowsdefender://devicesecurity`, Select `Security Processor Details` and attach a screenshot of the output
- https://i.eastarcti.ca/PRQ7D.png

Although I do have TPM 1.2(Theoretically not supported), WNW11 marks it as Missing/Disabled.

**Comment by rcmaehl** [comment]
Should be marked as not compatible, one moment

**Comment by rcmaehl** [comment]
Please give it a couple minutes, then download and run the latest dev build: https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

**Comment by EastArctica** [comment]
https://i.eastarcti.ca/ZEBbK.png Looking all good now! Thanks 👍
