### ISSUE TITLE
CPU Compatibility List Discussion

### ISSUE THREAD

**Issue by seiggy** [rcmaehl/WhyNotWin11#33]
The CPU Compatibility list is coming from the Systems Integrator page, not an actual requirement for Windows 11 support. See the same page for Windows 10 - https://docs.microsoft.com/en-us/windows-hardware/design/minimum/windows-processor-requirements Notice how there's a lot of missing CPUs that install Windows 10 just fine? Don't equate Systems Integrator requirements with OS requirements. These are ONLY to receive the "Windows Genuine Badge" for systems integrators - https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors

Ok, this is getting crazy now...story is changing constantly from MS camp. Best to wait?

**Comment by micwoj92** [comment]
Your*

**Comment by seiggy** [comment]
Literally the first line on the page of the first link

![image](https://user-images.githubusercontent.com/1055990/123515886-56baf280-d667-11eb-8f0a-2842700a8fce.png)

**Comment by htcfreek** [comment]
> Literally the first line on the page of the first link
> 
> ![image](https://user-images.githubusercontent.com/1055990/123515886-56baf280-d667-11eb-8f0a-2842700a8fce.png)
> 

See my last post which is updated. An this line you mentioned says that system with the listed processor can run Win11.

**Comment by seiggy** [comment]
This is the official requirements for non-Systems Integrators
https://docs.microsoft.com/en-us/windows/whats-new/windows-11-requirements

**Comment by seiggy** [comment]
Even the "Health Check App" released by MS will report that an 7th gen CPU with PTT, Secure Boot and UEFI turned on is fine to upgrade.

**Comment by Masamune3210** [comment]
Microsoft is releasing a post soon about all the confusion involving the requirements, so would probably just wait until then instead of arguing about specifics.

**Comment by seiggy** [comment]
> Microsoft is releasing a post soon about all the confusion involving the requirements, so would probably just wait until then instead of arguing about specifics.

Absolutely. Agreed.

**Comment by dev-sda1** [comment]
It's likely using the same sources that the PC health app is using. Doesn't make sense as to _why_ the PC health app is using them if the list is only for OEM but we'll have to wait and see if MS can repair the hellshow that's been unleashed because of their poor communication

**Comment by seiggy** [comment]
Yeah, they've totally screwed the messaging on this. All the docs have now been updated in the last hour or so to remove all the soft limit specs they had listed before. They really need to get a handle on this, as the messaging is seriously confusing now. Initial requirements were TPM 1.2+, UEFI, 64bit dual core CPU. Now suddenly that's not going to work?

**Comment by dev-sda1** [comment]
Microsoft's own Director of OS Security isn't having a great time on Twitter either. One tweet [saying skylake-gen processors _are_ supported](https://twitter.com/dwizzzleMSFT/status/1408489288937861125)  only to then say in a reply that[ the 7th gen is below](https://twitter.com/dwizzzleMSFT/status/1408491600443940866?s=20) the requirements and that [8th gen+ is what's supported](https://twitter.com/dwizzzleMSFT/status/1408492463111634945?s=20)(???) and then [tries to go back on the main tweet reply entirely](https://twitter.com/dwizzzleMSFT/status/1408493637575471107?s=20). Really not a great start for Windows as this has completely eclipsed any discussion of the OS itself.

**Comment by rcmaehl** [comment]
This will not change until I see an official report that Microsoft has changed their notably stupid stance and updates https://docs.microsoft.com/en-us/windows-hardware/design/minimum/windows-processor-requirements. Thankfully, I have set the CPU lists to be easily updatable without having to update the application itself once they do.

**Comment by djohannes** [comment]
> Even the "Health Check App" released by MS will report that an 7th gen CPU with PTT, Secure Boot and UEFI turned on is fine to upgrade.

I have a 7th gen CPU with a true TPM chip, Secure Boot and UEFI turned on and the app reports it's not fine to upgrade.

**Comment by htcfreek** [comment]
> > Even the "Health Check App" released by MS will report that an 7th gen CPU with PTT, Secure Boot and UEFI turned on is fine to upgrade.
> 
> I have a 7th gen CPU with a true TPM chip, Secure Boot and UEFI turned on and the app reports it's not fine to upgrade.

WhyNotWin11 or PCHealthCheck from Microsoft?

**Comment by djohannes** [comment]
> > > Even the "Health Check App" released by MS will report that an 7th gen CPU with PTT, Secure Boot and UEFI turned on is fine to upgrade.
> > 
> > 
> > I have a 7th gen CPU with a true TPM chip, Secure Boot and UEFI turned on and the app reports it's not fine to upgrade.
> 
> WhyNotWin11 or PCHealthCheck from Microsoft?

PCHealthCheck by MS, in the "WhyNotWin11" app is everything green except the CPU.

**Comment by htcfreek** [comment]
> > > > Even the "Health Check App" released by MS will report that an 7th gen CPU with PTT, Secure Boot and UEFI turned on is fine to upgrade.
> > > 
> > > 
> > > I have a 7th gen CPU with a true TPM chip, Secure Boot and UEFI turned on and the app reports it's not fine to upgrade.
> > 
> > 
> > WhyNotWin11 or PCHealthCheck from Microsoft?
> 
> PCHealthCheck by MS, in the "WhyNotWin11" app is everything green except the CPU.

So the results of both apps are corect

**Comment by djohannes** [comment]
> So the results of both apps are corect

Correct, just mentioned it because some people say even with a 7th gen CPU the MS app reports the upgrade will work.

**Comment by AGuyNamedJens** [comment]
> > > > Even the "Health Check App" released by MS will report that an 7th gen CPU with PTT, Secure Boot and UEFI turned on is fine to upgrade.
> > > 
> > > 
> > > I have a 7th gen CPU with a true TPM chip, Secure Boot and UEFI turned on and the app reports it's not fine to upgrade.
> > 
> > 
> > WhyNotWin11 or PCHealthCheck from Microsoft?
> 
> PCHealthCheck by MS, in the "WhyNotWin11" app is everything green except the CPU.

Same for me, I have a AMD Ryzen 5 1400 Quad Core, works perfectly fine, yet it's not in the list and get the same error on WhyNotWin11, as well as not supported on the pc health check, the rest is green -.-

**Comment by seiggy** [comment]
The issue is that they're sharing the Hardware Developer documentation as the supported CPU list. Which has never been the full list of CPU's supported by the OS for upgrades / enthusiast builds. Only for System Integrators. So it's seriously a massive misstep by whoever is handling the messaging right now. For example, check out the list of "Supported CPUs" for Windows 10 21H1 - https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-10-21h1-supported-intel-processors notice the fact that Intel 5th Gen and previous are all missing, though they all work fine with 21H1 and are eve listed as supported by Intel - https://www.intel.com/content/www/us/en/support/articles/000006105/processors.html

So I'd seriously expect their messaging to change early next week as communication within MS figures out they've published the wrong support list.

> > > > > Even the "Health Check App" released by MS will report that an 7th gen CPU with PTT, Secure Boot and UEFI turned on is fine to upgrade.
> > > > 
> > > > 
> > > > I have a 7th gen CPU with a true TPM chip, Secure Boot and UEFI turned on and the app reports it's not fine to upgrade.
> > > 
> > > 
> > > WhyNotWin11 or PCHealthCheck from Microsoft?
> > 
> > 
> > PCHealthCheck by MS, in the "WhyNotWin11" app is everything green except the CPU.
> 
> Same for me, I have a AMD Ryzen 5 1400 Quad Core, works perfectly fine, yet it's not in the list and get the same error on WhyNotWin11, as well as not supported on the pc health check, the rest is green -.-

The issue is that they're sharing the Hardware Developer documentation as the supported CPU list. Which has never been the full list of CPU's supported by the OS for upgrades / enthusiast builds. Only for System Integrators. So it's seriously a massive misstep by whoever is handling the messaging right now. For example, check out the list of "Supported CPUs" for Windows 10 21H1 - https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-10-21h1-supported-intel-processors notice the fact that Intel 5th Gen and previous are all missing, though they all work fine with 21H1 and are eve listed as supported by Intel - https://www.intel.com/content/www/us/en/support/articles/000006105/processors.html

So I'd seriously expect their messaging to change early next week as communication within MS figures out they've published the wrong support list.

**Comment by AGuyNamedJens** [comment]
> > > > > > Even the "Health Check App" released by MS will report that an 7th gen CPU with PTT, Secure Boot and UEFI turned on is fine to upgrade.
> > > > > 
> > > > > 
> > > > > I have a 7th gen CPU with a true TPM chip, Secure Boot and UEFI turned on and the app reports it's not fine to upgrade.
> > > > 
> > > > 
> > > > WhyNotWin11 or PCHealthCheck from Microsoft?
> > > 
> > > 
> > > PCHealthCheck by MS, in the "WhyNotWin11" app is everything green except the CPU.
> > 
> > 
> > Same for me, I have a AMD Ryzen 5 1400 Quad Core, works perfectly fine, yet it's not in the list and get the same error on WhyNotWin11, as well as not supported on the pc health check, the rest is green -.-
> 
> The issue is that they're sharing the Hardware Developer documentation as the supported CPU list. Which has never been the full list of CPU's supported by the OS for upgrades / enthusiast builds. Only for System Integrators. So it's seriously a massive misstep by whoever is handling the messaging right now. For example, check out the list of "Supported CPUs" for Windows 10 21H1 - https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-10-21h1-supported-intel-processors notice the fact that Intel 5th Gen and previous are all missing, though they all work fine with 21H1 and are eve listed as supported by Intel - https://www.intel.com/content/www/us/en/support/articles/000006105/processors.html
> 
> So I'd seriously expect their messaging to change early next week as communication within MS figures out they've published the wrong support list.

I honestly hope so lmao this is actual bullshit honestly, You see how they're adding more support to get a raspberry pi and small devices like it to run windows correctly? Yeah.. and a Ryzen 5 1400 quad core appearently wouldn't be supported while a tiny CPU of a pi will.. lol

**Comment by Masamune3210** [comment]
There is a theory that the strict cpu req's are to try to remove support for any cpu that is completely vulnerable to Specter or Meltdown. Also Windows on ARM is still as far as I know not officially licensed for users to put on whatever they want unless they changed it recently, hence open source projects to get it booting and drivers on stuff like the Pi 4

**Comment by seiggy** [comment]
> There is a theory that the strict cpu req's are to try to remove support for any cpu that is completely vulnerable to Specter or Meltdown. Also Windows on ARM is still as far as I know not officially licensed for users to put on whatever they want unless they changed it recently, hence open source projects to get it booting and drivers on stuff like the Pi 4 

Problem with that theory is that the 8th gens are still impacted by Specter and still need the software patch. And there's newer much worse performance impacting vulnerabilities even in the 9th gen (see ZombieLoad patch performance metrics). So I'd take this theory with a giant grain of salt.

**Comment by AGuyNamedJens** [comment]
> There is a theory that the strict cpu req's are to try to remove support for any cpu that is completely vulnerable to Specter or Meltdown. Also Windows on ARM is still as far as I know not officially licensed for users to put on whatever they want unless they changed it recently, hence open source projects to get it booting and drivers on stuff like the Pi 4

According to this site, which has pretty useful posts now and then -> https://www.xda-developers.com/windows-11/#Windows11x64Emulation
It should be supported in the future on Windows 11, I still don't get why my CPU would be vulnerable, because honestly most gamers with CPUs like mine, they're not dumb to install such vulnerabilities in programs and stuff..

**Comment by micwoj92** [comment]
>  because honestly most gamers with CPUs like mine, they're not dumb to install such vulnerabilities in programs and stuff..

I don't see how owning AMD Ryzen 5 1400 would make someone smart. Seeing what some anti cheat software (or any shady software) does with pc (and these gamers still install it) I have to say that your "theory" is false.

**Comment by AGuyNamedJens** [comment]
> > because honestly most gamers with CPUs like mine, they're not dumb to install such vulnerabilities in programs and stuff..
> 
> I don't see how owning AMD Ryzen 5 1400 would make someone smart. Seeing what some anti cheat software (or any shady software) does with pc (and these gamers still install it) I have to say that your "theory" is false.

Well it's still unfair that i would be basically forced to upgrade my CPU just to get windows 11.. which is a shame then

**Comment by Masamune3210** [comment]
What's even worse is I almost guarantee that this is a purely on install check, and that manually applying the install image using DISM will work just fine

**Comment by martinsuchan** [comment]
I got Surface Go 2 with Pentium Gold 4425Y.
This CPU is quite strange - it's listed in [Windows 11 list as supported](https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors), but it's actually [7th gen Pentium Kaby Lake CPU](https://en.wikipedia.org/wiki/Kaby_Lake).
Note the WhyNotWin11 app 2.1.0.0 reports for this CPU "?" on the CPU generation line, I guess this can be fixed?

**Comment by Masamune3210** [comment]
Go make a issue about it so it can properly be looked at, but I would wait a bit since I think a new build is about to come out soon

**Comment by micwoj92** [comment]
> > > because honestly most gamers with CPUs like mine, they're not dumb to install such vulnerabilities in programs and stuff..
> > 
> > 
> > I don't see how owning AMD Ryzen 5 1400 would make someone smart. Seeing what some anti cheat software (or any shady software) does with pc (and these gamers still install it) I have to say that your "theory" is false.
> 
> Well it's still unfair that i would be basically forced to upgrade my CPU just to get windows 11.. which is a shame then

I just ran leaked win11 dev build in VM with unsupported cpu (athlon x4 845) and with 1gb ram (but it was terribly slow) so these requirements are for "certification for oems" I would say.

**Comment by Masamune3210** [comment]
Well just because it ran doesnt mean that the requirement is only for OEM's. Requirements for Windows hardware wise has never been really strictly enforced, see the litany of videos on youtube about installing various versions of Windows in weird ways or on weird hardware configs

**Comment by dev-sda1** [comment]
> so these requirements are for "certification for oems" I would say.
If they were for OEMs why are DIY machines being held up to this bizzare CPU whitelist standard on the PC Health app and the documentation on MS' website?

**Comment by micwoj92** [comment]
> > so these requirements are for "certification for oems" I would say.
> 
> If they were for OEMs why are DIY machines being held up to this bizzare CPU whitelist standard on the PC Health app and the documentation on MS' website?

Look at previous comment "Requirements for Windows hardware wise has never been really strictly enforced, see the litany of videos on youtube about installing various versions of Windows in weird ways or on weird hardware configs"

**Comment by Masamune3210** [comment]
All the recommended specs apply to really is OEM's and Windows automatically upgrading once it comes out. Not much is going to stop someone from installing it on whatever hardware they want short of critical components like the kernal doing the check itself. Right now, the only thing that really does any hardware checks is the Installer and the HAL and its mostly just to make sure you can actually boot correctly

**Comment by gjsman** [comment]
Wrong, Microsoft's Vice President of Product Management has said:

"The supported Windows 11 CPU list I posted applies to both new and upgraded systems."
https://twitter.com/dispensa/status/1408573147285135366

And when asked the following question: 
"Does this mean if a chip, like the 7700k has TPM 2.0 but is not on your list, will not be able to upgrade to Windows 11?"

He responded with:
"Yeah, Windows 11 is only supported on the CPU list I posted above. There are more requirements than just TPM 2.0 support (and all supported chipsets should have  TPM 2.0, so that's not generally a blocking requirement)."
https://twitter.com/dispensa/status/1408580116393848839

**Comment by AGuyNamedJens** [comment]
Wtf "only supported on the list" so I'm like a LOT of users completely fucked pure by having either a new CPU like the newest intel 10th gen or a 2 year old amd cpu.. wtf

**Comment by dev-sda1** [comment]
They are going to completely ruin their market share if they actually push on with this in the final release. Vista but even worse as Windows 10 only has 4 years left unlike XP which had another decade at best

**Comment by AGuyNamedJens** [comment]
I wonder what the difference even does with TPM, Secure Boot, not having a cpu thats on the list etc, people are reporting nothing changed on their leaked windows 11 ISO.. Just look at how a intel 4th gen which isnt on the windows 10 supported list still works perfectly fine..

**Comment by dev-sda1** [comment]
When you run it in a virtual machine (like a Linux KVM) Windows bypasses all the checks that otherwise would be in place. Essentially admitting that none of these "requirements" are necessary. I can run the leaked ISO in a vm just fine and didn't flag any issues in the settings app signing up to the Insider Preview. There's definitely something dodgy going on behind the scenes. imo I smell a lawsuit similar to apple's constant ones with planned obsolescence

**Comment by AGuyNamedJens** [comment]
I'm not talking about the VM, I'm talking about the actual OS, on an actual hard drive

**Comment by gjsman** [comment]
Microsoft said that, because they are _so gracious_, during the testing and development phase the added requirements won't be enforced and anyone can try it, but upon release the requirements will be enforced and anyone with the last testing build on their PC will be forced to wipe their PCs and reinstall Windows 10.

**Comment by AGuyNamedJens** [comment]
But yeah no requirement is axtually needed, just look how old cpus not on the win10 list run win10 just fins

**Comment by AGuyNamedJens** [comment]
@gjsman if they do I'm def going to linux, no games for me i guess but honestly fuck that

**Comment by gjsman** [comment]
You can read all about that here: https://blogs.windows.com/windows-insider/2021/06/24/preparing-for-insider-preview-builds-of-windows-11/

While we recommend that all PCs meet the full hardware requirements for Windows 11, we are allowing some limited exceptions as we apply these new restrictions. All Windows Insiders who have already been installing builds from the Dev Channel on their PCs up through June 24, 2021 will be allowed to continue installing Windows 11 Insider Preview builds even if their PC does not meet the minimum hardware requirements. Insiders with PCs already in the Dev Channel have been installing and giving feedback on builds with Windows 11 features since last year. Our way of saying thanks is to go ahead and give them the opportunity to see everything come together. However, this comes with some important tradeoffs we want to call attention to:
Because these devices do not meet the new hardware requirements, there may be issues and bugs that impact the experience of Windows 11 on these PCs that may not get fixed.
If at any point something goes wrong on one of these PCs that requires having to go back to Windows 10, you can use the media creation tool here to go back to the Windows 10. These PCs will not be given another exception and not allowed to upgrade to Windows 11 Insider Preview builds again. They will be treated as a new PC and the minimum hardware requirements will be enforced as highlighted above.
Once Windows 11 is generally available, these PCs will be opted out of flighting and will not be able to receive future Windows 11 Insider Preview builds. These PCs must clean install back to Windows 10 with the media (ISOs) that we provide and can then join the Release Preview Channel to preview Windows 10 updates.

**Comment by dev-sda1** [comment]
The insider preview check at release won't apply to virtual machines. So technically I can run production Windows 11 if for some reason they keep the stupid requirements on Skylake through one lmao

**Comment by micwoj92** [comment]
> @gjsman if they do I'm def going to linux, no games for me i guess but honestly fuck that

I love you :heart_eyes_cat:

**Comment by EdgarGc026** [comment]
I can't update to windows 11 becase my CPU is a 7ma gen ._.XD
![image](https://user-images.githubusercontent.com/19244335/123528819-6e6a9900-d6b0-11eb-89d4-8b7c6e40bffb.png)

**Comment by ringtailedfox** [comment]
> I can't update to windows 11, because my CPU's to 7yh gen ._.XD
> ![image](https://user-images.githubusercontent.com/19244335/123528819-6e6a9900-d6b0-11eb-89d4-8b7c6e40bffb.png)

same here, but with an i7-7700HQ.... everything else passes quite easily.  guess I'm staying on Windows 10, then moving to Linux once support runs out if microsoft is stupid and stubborn enough to do this...

**Comment by Okwizi** [comment]
@ringtailedfox , Adding to the referenced Microsoft document, your CPU (as at the moment) won't support Windows 11 according to the Microsoft document (which happened to be updated as soon as the official checker was also updated.) Before the update on the document however, it stated that PCs with older CPUs could upgrade but it wasn't "recommended". Your CPU came out at 2015 which is considered old but doesn't not necessarily mean you can't run Windows 11. Most CPUs that pass the check are >7th Generation. I use a i5-6300U CPU and it didn't pass either the check in this thread nor the official one at Microsoft. I have seen You Tube videos where people install the Win 11 Build version on older machines and works fine.  The scenario is similar to a prompt error that warns you not to root your phone but you go ahead and root it anyway.

**Comment by gjsman** [comment]
@Okwizi Doesn't matter, Microsoft actually said in their blog post that the requirements for Windows 11 won't be effectively enforced until the Release To Manufacturing. Your ability to install Windows 11 today from a leaked build or an Insider build, according to Microsoft, doesn't matter compared to the final.

**Comment by djjstew** [comment]
WhyNotWin11 reports that I don't have DirectX 12 but in fact according to dxdiag I do?  Anyway....

Fail because 6th gen i7.  Dell computer will be 4 years old when Win 11 gets released ftw. I have seen nothing announced about Win 11 that would make me want to spend $'s to upgrade my desktop - it works great for what I do at home.  My work laptop is eligible so I guess in theory I could buy a really nice monitor for at home use.  

So here is the thing MSFT.  If I do want to upgrade my home rig you just gave me a reason to look at Apple - not along ago I would not have even thought this.  But recently for work reasons (company is Apple centric) I have an iPhone (android for personal use), Apple watch, iPad pro (no Android gadget comes close) so why not on the desktop?  In fact, for the things, I do at home why not a Chromebook?  Linux?  

Why would you piss off 1,000's if not 1MM's of loyal customers who would likely be ready to upgrade their rig in the next few years anyway?  BTW I'm not sure pissed off is correct since I did state earlier that I have seen nothing about Win 11 that is a game changer......

**Comment by Masamune3210** [comment]
I love how people are throwing so much fire at Microsoft for doing this and talking about switching to Apple, when Apple has been doing this shiz since the dawn of freaking time lol. There is even a tool specifically designed to get newer versions of macOS to run on older hardware that isn't in the compat list but works fine just because apple didn't want to support the hardware anymore

Is it a dumb idea and should Microsoft be getting hell for it? Yes
But don't act like Apple is any different, they arent

**Comment by billysielu** [comment]
_Was going to reply in #83 - will put it here instead:_

I agree it would be useful to have links to the requirements within WhyNotWin11.

Note that these links should be culture sensitive.

I think if you strip out the culture code their website takes care of it, so it would be:
Requirements: https://www.microsoft.com/windows/windows-11-specifications 
Intel: https://docs.microsoft.com/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors
AMD: https://docs.microsoft.com/windows-hardware/design/minimum/supported/windows-11-supported-amd-processors

**Comment by gjsman** [comment]
@Masamune3210 This is not true, actually, and is just misinformed Windows users. MacOS Monterey was a recent bump to the specs in requiring 2015 and newer PCs for most models (except for the 2013 Mac Pro and 2014 Mac mini). However, when Apple drops support for old computers in a new MacOS release, a shocking number of Windows users are ignorant that Apple gives an additional 2-3 years of security updates to previous releases of MacOS. 

So, let's say I had a MacBook Pro from Late 2013. I got Big Sur in November 2020. That means I'll have until late 2022 - early 2023 with security updates. On average, about a decade of support. Far more than those people who bought a Surface Studio 2 before the event to learn it will have no major updates and only four years left of security updates. It's more than those users who bought 7th gen chips in 2017, who are hitting the end of the road in 2025 with only eight years of support.

**Comment by chrisn1992** [comment]
> @seiggy
> This is not correct. The list is linked from the official hardware requirements on docs.microsoft.com.
> 
> ~Where do you read that the list is only for getting the badge?~
> 
> MS itself links to the list on docs.microsoft from the official Win11 announcement website.

Those Hardware configuration docs are meant for OEM to make pre-built PC.
No the Product team is using that to judging who can use Windows 11. Fishy and BS.

> Wrong, Microsoft's Vice President of Product Management has said:
> 
> "The supported Windows 11 CPU list I posted applies to both new and upgraded systems."
> https://twitter.com/dispensa/status/1408573147285135366
> 
> And when asked the following question:
> "Does this mean if a chip, like the 7700k has TPM 2.0 but is not on your list, will not be able to upgrade to Windows 11?"
> 
> He responded with:
> "Yeah, Windows 11 is only supported on the CPU list I posted above. There are more requirements than just TPM 2.0 support (and all supported chipsets should have TPM 2.0, so that's not generally a blocking requirement)."
> https://twitter.com/dispensa/status/1408580116393848839

Literally it is the soft-blocking for OEM, not enduser, the Product team messes this sh!t up. And he said "not blocking requirement".

> > so these requirements are for "certification for oems" I would say.
> > If they were for OEMs why are DIY machines being held up to this bizzare CPU whitelist standard on the PC Health app and the documentation on MS' website?

Literally product team behind the app messes up everything, they don't even know how to identify pre-built and self-built, OEM and End-user. The docs sites are literally for Windows ADK.

> Even the "Health Check App" released by MS will report that an 7th gen CPU with PTT, Secure Boot and UEFI turned on is fine to upgrade.

Many 7th CPU is not passing the check. 6th is not passing the check. Many unsupported CPU is passing the test.
That app is the whole mess.
WhyNotWin11 only gives me Yellow CPU Compatibility, which the app in turn should give me the passing status. No. MS says no!

**Comment by Masamune3210** [comment]
> @Masamune3210 This is not true, actually, and is just misinformed Windows users. MacOS Monterey was a recent bump to the specs in requiring 2015 and newer PCs for most models (except for the 2013 Mac Pro and 2014 Mac mini). However, when Apple drops support for old computers in a new MacOS release, a shocking number of Windows users are ignorant that Apple gives an additional 2-3 years of security updates to previous releases of MacOS.
> 
> So, let's say I had a MacBook Pro from Late 2013. I got Big Sur in November 2020. That means I'll have until late 2022 - early 2023 with security updates. On average, about a decade of support. Far more than those people who bought a Surface Studio 2 before the event to learn it will have no major updates and only four years left of security updates. It's more than those users who bought 7th gen chips in 2017, who are hitting the end of the road in 2025 with only eight years of support.
> 
> In total, if you look at the averages, if you buy an Apple machine you get about a decade of support on average. My grandparents bought an iMac in 2011 and it just lost official support this year. And frankly, considering it's been a decade and it has 4GB of 1333mhz memory, a very old dual-core Core i5, a 512MB Radeon and a spinning hard drive, I'm OK. And if I really wanted it, I could use the tool, but I can fully understand why Apple wouldn't push us higher versions of MacOS because it truly is old.

its only recently that Microsoft has started dropping support for windows versions in short timeframes, xp and 7 both were supported weeeellll after the newer versions of windows were out

**Comment by micwoj92** [comment]
> its only recently that Microsoft has started dropping support for windows versions in short timeframes, xp and 7 both were supported weeeellll after the newer versions of windows were out

Let's see:

Windows xp support: 2001-2014
windows vista support: 2006-2017
Windows 7 support: 2009-2020
windows 8 support: 2012-2023
windows 10 support: 2015-2025 (actually LTSB/LTSC versions even longer, but still 10 years, so 2019 version till 2029 etc)

Your statement is false.

**Comment by rcmaehl** [comment]
> _Was going to reply in #83 - will put it here instead:_
> 
> I agree it would be useful to have links to the requirements within WhyNotWin11.
> 
> Note that these links should be culture sensitive.
> 
> I think if you strip out the culture code their website takes care of it, so it would be:
> Requirements: https://www.microsoft.com/windows/windows-11-specifications
> Intel: https://docs.microsoft.com/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors
> AMD: https://docs.microsoft.com/windows-hardware/design/minimum/supported/windows-11-supported-amd-processors

Will do.

**Comment by Okwizi** [comment]
@gjsman , whatever will come out won't be that different from the build, and like other users here have said, Win 11 features aren't outstanding from Win 10, the UI is the only significant change in my opinion. Also, there will always be ways to install Win 11 on older PCs, doesn't really matter if it's a build or final software. What does matter though is what you get from Win 11, is it really an upgrade or downgrade?
I personally run Linux Ubuntu on dual boot, so if Win 11 still doesn't make a big difference from Win 10 after the expiration of security updates, I'll just stick to Win 10 or replace the OS with another one if I really wanted to.

**Comment by Masamune3210** [comment]
Im confused how supporting an OS that game out in 2009 until 2020, when its successor came out in 2012 makes that statement false but whatever, you seem very set in your belief. Would you want to support old versions of a software as complicated as Windows until the end of time? Because I wouldn't

**Comment by micwoj92** [comment]
> Im confused how supporting an OS that game out in 2009 until 2020, when its successor came out in 2012 makes that statement false but whatever, you seem very set in your belief. Would you want to support old versions of a software as complicated as Windows until the end of time? Because I wouldn't

Because Windows 10 came out in 2015, and will be supported up to 2029, when successor came will come out in 2021/2022.

That's about the same timeframe, so your statement "its only recently that Microsoft has started dropping support for windows versions in short timeframes" is false.

**Comment by gjsman** [comment]
@micwoj92 Windows 10 is only supported until 2025, not 2029.

**Comment by micwoj92** [comment]
@gjsman Isn't 2019 LTSC up to 2029?

**Comment by gjsman** [comment]
@micwoj92 LTSC, when licensed as part of Windows 10 Enterprise, is licensed until 2029. Every other Windows 10 version, including Enterprise, dies in 2025.

https://docs.microsoft.com/en-us/lifecycle/products/windows-10-home-and-pro

https://docs.microsoft.com/en-us/lifecycle/products/windows-10-enterprise-and-education

**Comment by micwoj92** [comment]
Oh, thanks for the info. Wasn't aware of that.
