### ISSUE TITLE
Exiting from Main()

### ISSUE THREAD

**Issue by mlipok** [rcmaehl/WhyNotWin11#335]
### Discussed in https://github.com/rcmaehl/WhyNotWin11/discussions/334

<div type='discussions-op-text'>

<sup>Originally posted by **mlipok** July  2, 2021</sup>
after Main()
there should be used:

```
Switch @OSVersion
	Case "WIN_7", "WIN_VISTA", "WIN_XP", "WIN_XPe"
		MsgBox($MB_ICONWARNING, _Translate(@MUILang, "Not Supported"), @OSVersion & " " & _Translate(@MUILang, "Not Supported"))
	Case Else
		;;;
EndSwitch
Global $__g_hModule = _WinAPI_GetModuleHandle(@SystemDir & "\ntdll.dll")
If @OSBuild >= 22000 Or _WinAPI_GetProcAddress($__g_hModule, "wine_get_host_version") Then
	MsgBox($MB_ICONWARNING, _Translate(@MUILang, "Your Windows 11 Compatibility Results are Below"), _Translate(@MUILang, "You're running the latest build!"))
EndIf

```

but:
this part 
```
			Case $hMsg = $GUI_EVENT_CLOSE Or $hMsg = $hExit
				GUIDelete($hGUI)
				Exit

```
with the Exit functions determines that all after Main() will not be called.

Please correct me if I'm wrong.
</div>

**Comment by billysielu** [comment]
You click exit, it exists. Why is this a problem?

**Comment by rcmaehl** [comment]
> You click exit, it exits. Why is this a problem?

He's referring to the operating system check that doesn't actually get run because I'm big dumb

**Comment by mlipok** [comment]
`He's referring to the operating system check that doesn't actually get run`
Exactly

**Comment by mlipok** [comment]
Could you remove InProgress tag ?

**Comment by mlipok** [comment]
hey... I just notice.
We omnit some code part.

Why do you still use some code after Main()

```
Main()

Global $__g_hModule = _WinAPI_GetModuleHandle(@SystemDir & "\ntdll.dll")
If @OSBuild >= 22000 Or _WinAPI_GetProcAddress($__g_hModule, "wine_get_host_version") Then
	MsgBox($MB_ICONWARNING, _Translate(@MUILang, "Your Windows 11 Compatibility Results are Below"), _Translate(@MUILang, "You're running the latest build!"))
EndIf

```
It is never called, or I'm wrong ?
