### ISSUE TITLE
WhyNotWin11_x86.exe v. 2.3.0.3 flagged as malicious by 6 security vendors in VirusTotal

### ISSUE THREAD

**Issue by adrianolabate** [rcmaehl/WhyNotWin11#339]
The application has been flagged as malicious by Cisco Security Endpoint (AMP).
It has also been flagged as malicious by 6 security vendors in VirusTotal.
See online report below:
https://www.virustotal.com/gui/file/1495ee7fd04c699abe22d3fb1c51233b0250a745091749f2f1fc01df394b9953/detection

Workstation on Windows 10 20H2 (19042.1055).

**Comment by micwoj92** [comment]
Duplicate of #49 

Will need to change title (32 bit build usually get more false positives)

**Comment by micwoj92** [comment]
In short: report to vendors as fp and then hope for best.

**Comment by mlipok** [comment]
https://www.autoitscript.com/forum/topic/34658-are-my-autoit-exes-really-infected/
