### ISSUE TITLE
SSL certificate on https://www.whynotwin11.org

### ISSUE THREAD

**Issue by mlipok** [rcmaehl/WhyNotWin11#345]
after going to: https://www.whynotwin11.org

I get this information:

Error 526 Ray ID: 6689ae571942c83b • 2021-07-02 17:44:15 UTC
Invalid SSL certificate

**Comment by micronine24** [comment]
I have the same issue
![imagen](https://user-images.githubusercontent.com/27899139/124312543-dce2a780-db45-11eb-9d3a-701d22fa864c.png)

**Comment by micwoj92** [comment]
Adding as bug, works fine without www. I think it needs to be changed in program + all translations

**Comment by rcmaehl** [comment]
Give it a bit for DNS to propagate and try again

**Comment by rcmaehl** [comment]
Give it a bit for DNS to propagate and try again

**Comment by mlipok** [comment]
Now I get: NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by rcmaehl** [comment]
Attempted another fix, give it a few minutes

**Comment by mlipok** [comment]
`https://www.whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/whynotwin11.org/`

**Comment by micwoj92** [comment]
Works for me @mlipok could you confirm?

**Comment by rcmaehl** [comment]
Should be fixed now, you may need to clear browser cache as 301s are cached

**Comment by billysielu** [comment]
looks good

**Comment by mlipok** [comment]
> Should be fixed now, you may need to clear browser cache as 301s are cached

Confirmed as fixed, thanks
