### ISSUE TITLE
Secureboot need to be capable, not required to be enabled

### ISSUE THREAD

**Issue by troysjanda** [rcmaehl/WhyNotWin11#35]
As in the image states that UEFI/Secure Boot **capable** I have it enabed but from some reason Windows reports it as off
![secureboot](https://user-images.githubusercontent.com/24624945/123516633-f2d9ff00-d651-11eb-94e1-326a81106c6d.PNG)

**Comment by rcmaehl** [comment]
Added in 6ba805b33098f45b009694f2e23c348d39073df8, will be released in a bit
