### ISSUE TITLE
UI text unreadable because of dark theme

### ISSUE THREAD

**Issue by rvane** [rcmaehl/WhyNotWin11#357]
**Describe the bug**
A dark theme is used in the program which currently makes user interface texts unreadable

**To Reproduce**
1. Download the program
2. Start the program
3. Observe the dark theme

**Expected behavior**
Readable texts regardless of used theme

**Screenshots**
![ui](https://user-images.githubusercontent.com/27134869/124345753-03065700-dbdb-11eb-8d09-192acdfa9d0d.png)

**Desktop**
 - OS: Windows 10 build 21H1
 - Version 2.3.0.4

**Comment by rcmaehl** [comment]
Yep, was trying to fix #314. Give it a couple minutes and then download https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

**Comment by doktornotor** [comment]
Works fine now.

**Comment by harakiwi** [comment]
yes, same here on my Win 10 install. (21H1 19043.1081)
the provided zip file works fine (https://github.com/rcmaehl/WhyNotWin11/issues/357#issuecomment-873358385)
