### ISSUE TITLE
Error: Subscript used on non-accessible variable

### ISSUE THREAD

**Issue by kermittheboi** [rcmaehl/WhyNotWin11#359]
Whenever I use a dev build or a stable one I get the exact same error.

Line 1606 (File "C:\Users\<name>\Downloads\WNW11\WhyNotWin11.exe"):
Error: Subscript used on non-accessible variable.

Opening it as an admininstrator does nothing, removing the folder WhyNotWin11 from %localappdata% also doesn't fix the issue. Probably something not used? No idea. Hopefully this helps, if more information is needed I will be happy to provide them. 

![Screenshot_113](https://user-images.githubusercontent.com/73022467/124350383-2215e080-dbfd-11eb-90e6-b2387063da3e.png)

**Comment by mlipok** [comment]
do you use current dev version ?

**Comment by rcmaehl** [comment]
@kermittheboi give it a couple minutes then download and run https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

Looks like there's a case where it crashes if it doesn't detect any bootable disks

**Comment by kermittheboi** [comment]
Seems to be working now, thanks for addressing the issue so quick. CPU Frequency and Core Counts isn't displayed (says 0 in everything) but all and all it opens so that's good enough.
