### ISSUE TITLE
gpedit changes seems to stop PC Health Check

### ISSUE THREAD

**Issue by Grabou** [rcmaehl/WhyNotWin11#37]
Hello,

Great tool. But it seems you're missing the gpedit.msc check. Because the only thing I can remember is having modified one single setting in gpedit.msc for my VPN to work correctly. 🙃

![mmc_qNtRjyx8bd](https://user-images.githubusercontent.com/33343310/123520787-c73b3100-d6b2-11eb-9206-e1e30273fdb7.png)

![WhyNotWin11_cN6ua0ZA7D](https://user-images.githubusercontent.com/33343310/123520329-7aeef180-d6b0-11eb-8486-3043ec66fe66.png)

![PCHealthCheck_m3BCLVGq5s](https://user-images.githubusercontent.com/33343310/123520337-86421d00-d6b0-11eb-86f7-0b99a6d97973.png)

**Comment by htcfreek** [comment]
Imo it a great addition that WhyNotWin11 works regardless of GPO changes.

**Comment by rcmaehl** [comment]
I won't prevent GPO changes from running the check. Any user on a GPO/Domain managed computer with the Admin rights needed for WhyNotWin11, likely has permission to run the script anyway or at least is held to an acceptable use policy
