### ISSUE TITLE
In the file "GetDiskInfo.au3" there are typos in the word "Partition"

### ISSUE THREAD

**Issue by Oleg-Chashko** [rcmaehl/WhyNotWin11#386]
**Describe the bug**
In the file "GetDiskInfo.au3" there are typos in the word "Partition".

**Comment by htcfreek** [comment]
> **Describe the bug**
> In the file "GetDiskInfo.au3" there are typos in the word "Partition".

Great find. But false repo for the issue. I will transfer your issue.

**Comment by htcfreek** [comment]
@rcmaehl 
Can be closed as resolution external.
