### ISSUE TITLE
Theme definition file

### ISSUE THREAD

**Issue by htcfreek** [rcmaehl/WhyNotWin11#388]
As I asked/suggest in another issue, we should add an Theme interface like this:

Dark.stylecfg
```
[Global]
Name=
Version=
Authors=

[Colors]
Background=
Footer=
Sidepanel.Left=
Rectangle.Error=
Rectangle.Warn=
Rectangle.Okay=
Rectangle.CheckRunning=
Text.Header=
Text.Default=
Text.Warning=
Text.Link=blue      => URL to WNW11-Homepage
Text.CheckName=
Text.CheckResult=

[Image] => if we need different ones for dark/light theme.
Github=
Donate=
Discord=
LTT=
Settings=
```

**Comment by micwoj92** [comment]
I think it should just be light/dark and users with custom themes should figure it out.
Ideally there should be just 2 sets of icons and rest should be done automatically

**Comment by micwoj92** [comment]
Or maybe replace icons with svg, would be much easier to change colours.
Does autoit support svg?

W dniu niedziela, 4 lipca 2021 Heiko ***@***.***> napisał(a):
> As I asked/suggest in another issue, we should add an Theme interface
like this:
>
> Dark.stylecfg
>
> [Global]
> Name=
> Version=
> Authors=
>
> [Colors]
> Background=
> Footer=
> Sidepanel.Left=
> Rectangle.Error=
> Rectangle.Warn=
> Rectangle.Okay=
> Rectangle.CheckRunning=
> Text.Header=
> Text.Default=
> Text.Warning=
> Text.Link=blue => URL to WNW11-Homepage
> Text.CheckName=
> Text.CheckResult=
>
> [Image] => if we need different ones for dark/light theme.
> Github=
> Donate=
> Discord=
> LTT=
> Settings=
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/HE0R2HHsbp-ZHltBfWGC8GOy8sUjTSwpNQCn9P64WkldI2BEqqIt2lLBfOUe7Mlcy60GG3LggAI6vsOn_wZILIiPln-ogbFEk1z5I5Z3m3mtNdYrQhYou0OrhTAJqSy_qFb9DCFBaI7pqhOd4Q7FFfUss7svXna1rOYExyFEOnnN2m_Bil1bcUAtksZCMiLEnNK_XwDLqNOLQ9aEdELIQTqRP1Y=s0-d-e1-ft#https://github.com/notifications/beacon/AK3YG4UFH74BBVUSB7QPJULTV6JBZA5CNFSM47YR6A2KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4N6PNFQQ.gif>

**Comment by htcfreek** [comment]
> Or maybe replace icons with svg, would be much easier to change colours. Does autoit support svg? 

No. Only by using embedded IE 🤮.

**Comment by xz00311** [comment]
WinAPISysWin.au3  The library file was not found

**Comment by micwoj92** [comment]
What are you trying to do @xz00311?

**Comment by htcfreek** [comment]
@micwoj92
Can you please add "In-progress" lable.

**Comment by htcfreek** [comment]
We should add the color of "Results based on known requirements."-Note to theme definition file. => Then we can switch based on dark/light theme (yellow/red).

**Comment by rcmaehl** [comment]
Added 2.0 theme example. Just need to finish some coding on it when I have the chance.

**Comment by d1stru3t0r** [comment]
W11 won't have 32bit, but WhyNotWin11 recommends to reinstall and wipe disk to install 32bit W11

**Comment by micwoj92** [comment]
And how is any of this related to theme definition file?

**Comment by d1stru3t0r** [comment]
> And how is any of this related to theme definition file?

nothing, but where elsewhere can I report this? It's just a suggestion, not something important lmao

**Comment by micwoj92** [comment]
![image](https://user-images.githubusercontent.com/45581170/127348120-9787db61-88cc-4a88-9179-1a303c9a7bf7.png)
