### ISSUE TITLE
In the file "SupportedProcessorsIntel.txt" there are typos

### ISSUE THREAD

**Issue by Oleg-Chashko** [rcmaehl/WhyNotWin11#391]
**Describe the bug**
In the file "SupportedProcessorsIntel.txt" there are typos

Line 441: Xeon(R) Gold Gold 5218 -> Xeon(R) Gold 5218
Line 442: Xeon(R) Gold Gold 6238R -> Xeon(R) Gold 6238R

Line 443: Xeon(R) Gold6246 -> Xeon(R) Gold 6246
Line 444: Xeon(R) Goldv 6234 -> Xeon(R) Gold 6234

Line 523: Xeon(R) Gold Gold 5318Y -> Xeon(R) Gold 5318Y

**Comment by billysielu** [comment]
The 'typos' are in the [Windows 11 Supported Intel Processors](https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors ) list.
No way of knowing if they're intentional or not, so I wouldn't 'fix' them.

**Comment by Oleg-Chashko** [comment]
@billysielu 
I double-check myself, on the Intel manufacturer's website.
Intel writes the correct processor names.
And Microsoft is wrong, it happens.

Link: https://ark.intel.com/content/www/us/en/ark.html#@Processors

**Comment by micwoj92** [comment]
Please report this to microsoft.

**Comment by Oleg-Chashko** [comment]
@micwoj92 
_Please report this to Microsoft._
I take it you didn't write this to me?

**Comment by micwoj92** [comment]
I wrote this in general. In words of billysielu "No way of knowing if they're intentional or not"

**Comment by Oleg-Chashko** [comment]
@micwoj92 
Got it, thanks for the clarification.
