### ISSUE TITLE
Add a page to show requirements system is being checked against

### ISSUE THREAD

**Issue by htcfreek** [rcmaehl/WhyNotWin11#395]
Let's add one of the following suggestions to show the requirements we check against:
- Info icon on the right side (after check info text) with an tooltip.
- Column with text about requirement per check.
- On every check a third line in lighter background color with the requirement.

**Comment by rcmaehl** [comment]
![image](https://user-images.githubusercontent.com/716581/124505601-dea3a980-dd97-11eb-9f83-13d16ed2e415.png)

Not sure if I like the icon approach with how little room is left. One moment

**Comment by rcmaehl** [comment]
![image](https://user-images.githubusercontent.com/716581/124505949-9a64d900-dd98-11eb-8c6b-f81614871adb.png)

**Comment by micwoj92** [comment]
Why not make it show if you hover mouse over your current specs?

**Comment by htcfreek** [comment]
> Why not make it show if you hover mouse over your current specs?

Who should know this?

**Comment by htcfreek** [comment]
> ![image](https://user-images.githubusercontent.com/716581/124505949-9a64d900-dd98-11eb-8c6b-f81614871adb.png)
> 

Im sure the hover note gets lost.

**Comment by rcmaehl** [comment]
Please review the latest dev build and advise on tips.

**Comment by htcfreek** [comment]
The plan was to show the minimum requirements and not to help user to fox check.

Where could we place the requirements?

**Comment by rcmaehl** [comment]
Added in Guides section of testing.
