### ISSUE TITLE
Report Incorrectly Reported Processors Here

### ISSUE THREAD

**Issue by martinsuchan** [rcmaehl/WhyNotWin11#40]
I got Surface Go 2 with Pentium Gold 4425Y.
This CPU is quite strange - it's listed in [Windows 11 list as supported](https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors), but it's actually [7th gen Pentium Kaby Lake CPU](https://en.wikipedia.org/wiki/Kaby_Lake).
WhyNotWin11 app 2.2.0.0 reports for this CPU "?" on the CPU generation line, I guess this can be fixed?

![image](https://user-images.githubusercontent.com/3041397/123524726-83552580-d6cc-11eb-8775-4a0446b0e95b.png)

**Comment by micwoj92** [comment]
Hmm, weird, it is included in the check file, I think the problem might be that it reports without "gold" in name
https://github.com/rcmaehl/WhyNotWin11/blob/f354885c7629ef577f6325f0af2c47e68f67ec28/includes/SupportedProcessorsIntel.txt#L274

**Comment by htcfreek** [comment]
> Hmm, weird, it is included in the check file, I think the problem might be that it reports without "gold" in name
> https://github.com/rcmaehl/WhyNotWin11/blob/f354885c7629ef577f6325f0af2c47e68f67ec28/includes/SupportedProcessorsIntel.txt#L274

the question is if there are different version of the cpu. 🤔

**Comment by rcmaehl** [comment]
I've updated the list. It'll be included in 2.2.1 along with some other fixes. 

In the meantime you can put the attached file at the bottom of this message in %temp% and it'll pass
![image](https://user-images.githubusercontent.com/716581/123525926-51c76480-d6a2-11eb-8783-33a6cc9e5465.png)

----
[SupportedProcessorsIntel.txt](https://github.com/rcmaehl/WhyNotWin11/files/6720706/SupportedProcessorsIntel.txt)

**Comment by billysielu** [comment]
Suggestion:
Microsoft will be updating their list and you'll just want to copy-paste it into your app without overwriting the fixes.
If you put corrections in a different file you don't have that problem.

**Comment by micwoj92** [comment]
I think it would be much better approach to create script that would "fix" the problems, for example now it would just need to replace all gold occurences with cpu

**Comment by rcmaehl** [comment]
> Suggestion:
> Microsoft will be updating their list and you'll just want to copy-paste it into your app without overwriting the fixes.
> If you put corrections in a different file you don't have that problem.

Already possible. 2.2.1 is mainly because NVidia 3000 Series owners are getting fails

**Comment by EarlyMon** [comment]
WhyNotWin11 passed my hp laptop w/ AMD Ryzen 7 2700U but PC Health Check did not. The Microsoft CPU list does not include the Ryzen 2xxxU versions, but the 3xxxU versions and above are fine. The U series is the low-power laptop processor. The 2xxxU series is included in the Win10 update compatibility list so Microsoft does recognize them separately there. No clue if it's a Microsoft oversight or if the laptop versions just aren't making the grade. Thought I ought to report it, thanks for the great work on the cool tool!

**Comment by rcmaehl** [comment]
> WhyNotWin11 2.2.1 passed my hp laptop w/ AMD Ryzen 7 2700U but PC Health Check did not. The Microsoft CPU list does not include the Ryzen 2xxxU versions, but the 3xxxU versions and above are fine. The U series is the low-power laptop processor. The 2xxxU series is included in the Win10 update compatibility list so Microsoft does recognize them separately there. No clue if it's a Microsoft oversight or if the laptop versions just aren't making the grade. Thought I ought to report it, thanks for the great work on the cool tool!

I _should_ be able to fix this. Can you post the screenshot of your results. Does it have `AMD Ryzen 7 2700U Processor` for CPU or something else?

**Comment by EarlyMon** [comment]
![ryzen2700u,png](https://user-images.githubusercontent.com/16929133/123530193-c069e980-d6c5-11eb-8f0e-bedb09c455cc.png)

**Comment by rcmaehl** [comment]
> AMD Ryzen 7 2700U with Radeon Vega Mobile Gfx

Thank you!

**Comment by EarlyMon** [comment]
Also excluded are:

AMD Ryzen 3 2200U
AMD Ryzen 3 2300U
AMD Ryzen 3 PRO 2300U
AMD Ryzen 5 2600U
AMD Ryzen 5 PRO 2600U
AMD Ryzen 7 2700U
AMD Ryzen 7 PRO 2700U

Although I don't know how the others would return their IDs, I used the Microsoft Win10 update list to build that one.

**Comment by EarlyMon** [comment]
![ryzen2700u-2](https://user-images.githubusercontent.com/16929133/123553292-521a3b00-d748-11eb-86cd-cfe46e0b303a.png)

Confirming changed behavior. (thumbs up)
