### ISSUE TITLE
Update GetDiskInfoFromWmi to 1.4.1

### ISSUE THREAD

**Issue by micwoj92** [rcmaehl/WhyNotWin11#400]
WhyNotWin11 currently includes 1.2, 1.3 released 10 hours ago.

**Comment by htcfreek** [comment]
I will do this by myself when updating the check. 😉 ()

To fix some typos v1.4 will be released soon.

**Comment by micwoj92** [comment]
Ok, gonna assign this one to you then.

**Comment by htcfreek** [comment]
@micwoj92 
I hope I have the time to work on it this week.

**Comment by htcfreek** [comment]
work in  progress
