### ISSUE TITLE
Font for Asian characters

### ISSUE THREAD

**Issue by pklion** [rcmaehl/WhyNotWin11#402]
**Describe the bug**
It looks weird because of fonts...
![image](https://user-images.githubusercontent.com/78145811/124454092-09efbe00-ddc3-11eb-842a-558474d87a22.png)

**To Reproduce**
Simply open the application in Japanese.

**Expected behavior**
How about changing 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 21H1 19043.1081 Windows Feature Experience Pack 120.2212.3530.0
 - Version 2.3.1.0(dev 07/05)

**Additional context**

**Comment by rcmaehl** [comment]
What font would you recommend?

**Comment by krystian3w** [comment]
See these:
```css
font-family: "Segoe UI", "Calibri",  "Verdana", "Ubuntu", "Noto Sans CJK", "Hiragino Maru Gothic Pro W4", "ヒラギノ丸ゴ W4", "Hiragino Maru Gothic Pro W3", "ヒラギノ丸ゴ W3", "Meiryo", "メイリオ", "Ume Gothic", "Ume UI Gothic"
```

Based on: https://github.com/DandelionSprout/adfilt/blob/master/JapaneseTextSoftener.txt

**Comment by pklion** [comment]
Sorry for late reply.
I recommend Meiryo(メイリオ) or Yu Gothic(游ゴシック) because they are used widely and installed by default.
Also Noto Sans CJK and M+ fonts are good choices.

**Comment by rcmaehl** [comment]
Please test the latest dev build.

**Comment by pklion** [comment]
@rcmaehl I can't test it because there is an error when running...
![image](https://user-images.githubusercontent.com/78145811/124917170-77535700-e02e-11eb-8a6a-be7f35ba090a.png)

**Comment by pklion** [comment]
Should I make a new issue?

**Comment by rcmaehl** [comment]
No. Let me make changes

**Comment by pklion** [comment]
@rcmaehl Thank you so much.
It looks really good! :-)
But it doesn't work without admin permission though....
Thank you for implementing!
![image](https://user-images.githubusercontent.com/78145811/124922674-aff62f00-e034-11eb-8a98-83b0de352e5b.png)
(image when run as admin)
![image](https://user-images.githubusercontent.com/78145811/124922961-f64b8e00-e034-11eb-94ea-16863f744d3a.png)
(image when run not as admin)

**Comment by rcmaehl** [comment]
Odd, I'll look into that admin issue

**Comment by pklion** [comment]
I would like to know how the task is going if I may.
