### ISSUE TITLE
version 2.3.1.0, still showing incorrect information

### ISSUE THREAD

**Issue by nichog** [rcmaehl/WhyNotWin11#406]
Upon starting the new build, the 2 I reported on before are still showing incorrect displays
**To Reproduce**
Double click on EXE file, 
app appears with incorrect information for Boot Method, Secure Boot and Now the Disk part ion is NOT reading the M.2e drives correctly
**Expected behavior**
1.Should show boot partition as non legacy, since it is encrypted by the secure boot hardware included on this board
2.Disk Partition only shows one of the 2 M.2e drives available, since last build at least showed the C drive as GPT
3.Secure boot still shows as Disabled/Not detected.
4.Second screen shot shows the output of previous app
**Screenshots**
Incorrect_display_upon_opening_app](https://user-images.githubusercontent.com/36136819/124488048-404a2080-dd64-11eb-8e05-ff88a0aa3ba1.jpg)
**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version 21H1 19043.1081
 - Windows Feature Experience Pack 120.2122.3920.0
**Additional context**
I will not argue about the app not showing my CPU as Not listed , listed as Compatible since Microsoft has yet to put anything out on this, but the others ae NOT reading the bios correctly since the screen shots I upload on the last post show both as on and working. Second screen shot shows pervious build output

**Comment by nichog** [comment]
![Shows_1_particon_as_GPT](https://user-images.githubusercontent.com/36136819/124490122-991ab880-dd66-11eb-82fd-e663e31a6b03.jpg)

**Comment by rcmaehl** [comment]
> 1.Should show boot partition as non legacy, since it is encrypted by the secure boot hardware included on this board

Please run `Confirm-SecureBootUEFI` in admin powershell

> 2.Disk Partition only shows one of the 2 M.2e drives available, since last build at least showed the C drive as GPT

2.3.0.1 showed 1/2 drives bootable AND gpt, it did not specify C:

> 3.Secure boot still shows as Disabled/Not detected.

Please see 1.

> I will not argue about the app not showing my CPU as Not listed , listed as Compatible since Microsoft has yet to put anything out on this, but the others ae NOT reading the bios correctly since the screen shots I upload on the last post show both as on and working. Second screen shot shows pervious build output

The official release requirements are here: https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-amd-processors

WhyNotWin11 does not show results for dev, insider, or leaked builds currently. If the CPU list changes for Windows 11 release, WhyNotWIn11 will be updated.
