### ISSUE TITLE
[Question] How does cmd line otput looks like?

### ISSUE THREAD

**Issue by htcfreek** [rcmaehl/WhyNotWin11#407]
Can you give me an example how cmd line output should look like?

**Comment by micwoj92** [comment]
I think just a list with all requirements present in GUI + check mark

**Comment by htcfreek** [comment]
The point is, I the script code isn't really organized and commented.

**Comment by mlipok** [comment]
> The point is, I the script code isn't really organized and commented.

To which specyfic part you are refiering in this issue ?

**Comment by htcfreek** [comment]
Ignore it. I found the things I searched. Will make a PR to improve code layout
