### ISSUE TITLE
Inaccurate SecureBoot detection

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [rcmaehl/WhyNotWin11#414]
SecureBoot check gives me "Supported" result marked in green, despite the fact that it's currently disabled in my system.
Shouldn't it be "Supported/Disabled", marked in yellow?

Windows 8.1.

**Comment by rcmaehl** [comment]
Per testing with the official app. Secure Boot does not need to be enabled, just supported. Why?

![image](https://user-images.githubusercontent.com/716581/124537441-e55a0d00-dde7-11eb-90d9-96d249d4f8e6.png)

**Comment by rcmaehl** [comment]
If this changes I'll make the change in WhyNotWin11. Otherwise closing for now.

**Comment by nbmrjuhneibkr** [comment]
If it doesn't need to be enabled, then it may as well not be there at all. This requirement doesn't make a lot of sense to me - just like many other things regarding Windows 11.

**Comment by rcmaehl** [comment]
> This requirement doesn't make a lot of sense to me - just like many other things regarding Windows 11.

Absolutely. CPU support list is insane. 2023 requirements are stupid. The entire update is a mess.

**Comment by nbmrjuhneibkr** [comment]
It was bad enough when it only said "Supported" without mentioning that it was disabled, but now this is just wrong.

![Untitled1](https://user-images.githubusercontent.com/8460563/125412042-34470a00-e3c7-11eb-8e0b-89cc580cd666.png)
![Untitled2](https://user-images.githubusercontent.com/8460563/125412064-e8ed1681-294f-4ce3-b67c-77fe5bfc499f.png)

**Comment by rcmaehl** [comment]
May be an issue with the recent code refactoring. It still passes as the device is compatible but isn't showing full details
