### ISSUE TITLE
The exact list of compatible CPUs :)

### ISSUE THREAD

**Issue by HideakiAtsuyo** [rcmaehl/WhyNotWin11#416]
https://www.ginjfo.com/actualites/logiciels/windows-11/windows-11-voici-la-liste-exacte-des-processeurs-intel-et-amd-pris-en-charge-20210703

**Comment by micwoj92** [comment]
Please link to direct microsoft sources, not some magazine. https://github.com/rcmaehl/WhyNotWin11/discussions/165
