### ISSUE TITLE
Erroneous result "No DirectX 12, but WDDM2"

### ISSUE THREAD

**Issue by Wgrahamt** [rcmaehl/WhyNotWin11#419]
Running on my Dell Lattitude E6520 (Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz) laptop with an Nvidia NVS 420 graphics card running Windows 10 Build 19043.1081  - I get this result 
![image](https://user-images.githubusercontent.com/87027325/124625354-a1154e00-de75-11eb-89fc-c18152ab7fdf.png)

Whereas if I run dxdiag.exe I get the result in the text file:- 
[DxDiag(1).txt](https://github.com/rcmaehl/WhyNotWin11/files/6771055/DxDiag.1.txt)

--- so WhyNotWinn1 is incorrectly reporting "No DirectX 12, but WDDM2" because on my laptop, the dxdiag shows both DirectX 12 and WDDM.

The Nvidia  Control Panel Detaile Information shows:-
[NVIDIA System Information 07-06-2021 16-26-45.txt](https://github.com/rcmaehl/WhyNotWin11/files/6771114/NVIDIA.System.Information.07-06-2021.16-26-45.txt)

Regards

Graham

**Comment by rcmaehl** [comment]
You have DX12 software installed but per your Direct3D, DDI, and Feature level your card does not support DX 12. This is supported per TechPowerUp

https://www.techpowerup.com/gpu-specs/quadro-nvs-420.c1448

**Comment by Wgrahamt** [comment]
Hi Robert,

 

Thanks for your prompt reply.  I must apologise since I have quoted you the wrong Nvidia card … my laptop has a NVS 4200M.

 

I’ve just found a more recent driver, so I’m going to install that first.   

 

Regards

 

Graham

**Comment by rcmaehl** [comment]
Ah, you have another one of the darn DirectX 12 "API" cards. These cards partially support DirectX 12 but not all of it. This will be resolved by #58

**Comment by Wgrahamt** [comment]
Got hold of the latest Windows 10 driver for the NVS 4200M and installed it - WhyNotWin11 gives a green pass for DirectX 12 & WDDM



 

 

Although the NVS 4200M still says DirectX 11 Support



 



 



 

 

Now, I’ll hopefully fix TPM by enabling in BIOS and plan change from MBR to UEFI in BIOS.

 

Thanks for your time and attention.

 

Graham

**Comment by rcmaehl** [comment]
Closing per confirmed resolution
