### ISSUE TITLE
[Translation] Allow multi replacement

### ISSUE THREAD

**Issue by htcfreek** [rcmaehl/WhyNotWin11#421]
Improve translate function to allow multi replacement.

**Comment by htcfreek** [comment]
in progress

**Comment by micwoj92** [comment]
Why close?

**Comment by krystian3w** [comment]
Maybe Transifex or Crowdin.

**Comment by htcfreek** [comment]
@micwoj92 
Because I wan't first do the other implementations and don't need it for this.
