### ISSUE TITLE
[Code] Translation function not working correctly

### ISSUE THREAD

**Issue by htcfreek** [rcmaehl/WhyNotWin11#422]
The translation function not working correctly and isn't parameterized very well. 

See my hopefully working fix here: https://github.com/htcfreek/WhyNotWin11/commit/d55c4f51cced510b42e399f87283d0afff0ff30b

**Comment by Dragon1573** [comment]
I'm currently using **v2.3.0.5**. It's installed via my private [**Scoop Bucket**](https://github.com/Dragon1573/Scoop-Bucket/blob/main/bucket/whynotwin11.json). After installation, it only shows an _English Interface_ for me when I lauch this application. 

How can I switch to _Simplified Chinese_? I can't find any button for this language setting. 

![image](https://user-images.githubusercontent.com/49941141/124713432-23b01300-df33-11eb-98b9-9269331f8bb0.png)

**Comment by micwoj92** [comment]
@Dragon1573 is your operaring system in Simplified Chinese?

W dniu środa, 7 lipca 2021 べ断桥烟雨ミ ***@***.***> napisał(a):
> I'm currently using v2.3.0.5. It's installed via my private Scoop Bucket.
After installation, it only shows an English Interface for me when I lauch
this application.
>
> How can I switch to Simplified Chinese? I can't find any button for this
language setting.
>
> <
https://ci5.googleusercontent.com/proxy/0J3CJvojODFyx9fGYB-svZB-VkXOvdvQWqJ5wbMrIrH6IlTjsgG7bR4ewoEDyUNvZxeu8rz2EBb0uhzU7x5MWtZqpoZljTxDpsLjY7T6pCf_8JszE0MCeAKSH3clEmIlNpyz9-M02dKH3TCh3YgdqtCL6-o3d9Pa=s0-d-e1-ft#https://user-images.githubusercontent.com/49941141/124713432-23b01300-df33-11eb-98b9-9269331f8bb0.png
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/XmK6cnEkMX-2xEDDUo95ECy_7B7_r_FkEReyLvasNQcvLOT0hQbKTC9cAHohwoFiX_7lYk49JuZQGt5nzuXJwk8XEOrZ6mmnRI9r5455WBWJzefR1iThtXU6VeLKq2yBZmZNbmG8lreAnJ_shZ1XdGAKbICHst3A648KrdDVA7jPONSPNHz6fQQr8DSCowiTjwSKhgvNyb5cKEuCHwNwb6nmK9OE5gaai8sNa-FGWA=s0-d-e1-ft#https://github.com/notifications/beacon/AK3YG4QGOCPXZPLPCNSPGYLTWP3AHA5CNFSM475O46U2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGQWJXZA.gif>

**Comment by htcfreek** [comment]
@Dragon1573
Do you running a dev build?

For me in last build (Fork from yesterday evening German time.) I can't get the updated lang file to work.

**Comment by Dragon1573** [comment]
> @micwoj92: Is your operating system in Simplified Chinese? 

Yes, it is! I'm currently using: 

-  **Windows 10 Home China** (家庭中文版) 21H1 (19043.1081)
- Windows Feature Experience Pack 120.2212.3530.0. 

And here are the system language configurations of my device. All of them are displayed in Simplified Chinese. 

![image](https://user-images.githubusercontent.com/49941141/124726802-ad1a1200-df40-11eb-9f8a-bc4aa2ae4014.png)

**Comment by Dragon1573** [comment]
> @htcfreek: Do you running a dev build? 

Sorry, I can't make sure which build (stable & dev) am I currently running. Maybe I'm currently running a stable version? 

The Auto-Update features of that [_Scoop Bucket_](https://github.com/Dragon1573/Scoop-Bucket) was enabled with [_GitHub Actions_](https://github.com/Dragon1573/Scoop-Bucket/actions/workflows/checkver.yaml). According to my [configurations](https://github.com/Dragon1573/Scoop-Bucket/blob/2d6558ed46ca152c8af08ed8ac2972b5957af6eb/bucket/whynotwin11.json#L48), the latest version will be checked through the [_Releases_](https://github.com/rcmaehl/WhyNotWin11/releases) page of this repository (currently [v2.3.0.5](https://github.com/rcmaehl/WhyNotWin11/releases/tag/2.3.0.5)) and the download link will be the same in _GitHub Releases_ page (configured [here](https://github.com/Dragon1573/Scoop-Bucket/blob/2d6558ed46ca152c8af08ed8ac2972b5957af6eb/bucket/whynotwin11.json#L6-L29)).

**Comment by rcmaehl** [comment]
![image](https://user-images.githubusercontent.com/716581/124763562-1af31900-df02-11eb-848d-0269cea35343.png)
I'm unable to reproduce. When is it not working properly @htcfreek

**Comment by htcfreek** [comment]
> ![image](https://user-images.githubusercontent.com/716581/124763562-1af31900-df02-11eb-848d-0269cea35343.png)
> I'm unable to reproduce. When is it not working properly @htcfreek 

Let me make the PR and then you can check my branch. (I startet the non-cumpiled after adding strings on an English system.)

**Comment by htcfreek** [comment]
@rcmaehl 
Which id does your language have? I found a 0407.lang and an empty 407.lang in `%localappdata% ` folder yesterday.

If I am right it can be the problem that on integer trailing 0 gets lost. Then we should chang the input parameter to String.

**Comment by rcmaehl** [comment]
> @rcmaehl
> Which id does your language have? I found a 0407.lang and an empty 407.lang in `%localappdata% ` folder yesterday.
> 
> If I am right it can be the problem that on integer trailing 0 gets lost. Then we should chang the input parameter to String.

0409 is English. I renamed 0408 to 0409 to test, but I'll install a locale pack to test if there's still an issue

**Comment by htcfreek** [comment]
Offtopic: 
How can I rebase a feature branch of my fork against your main branch?

**Comment by micwoj92** [comment]
@htcfreek 

![image](https://user-images.githubusercontent.com/45581170/124805418-c41a2d80-df5b-11eb-9fe7-67446cf01079.png)

**Comment by htcfreek** [comment]
> @htcfreek 
> 
> ![image](https://user-images.githubusercontent.com/45581170/124805418-c41a2d80-df5b-11eb-9fe7-67446cf01079.png)
> 

So I have to fetch and metge into my main and from there into my feature branch?

**Comment by micwoj92** [comment]
No, you can do it directly into your feature branch, just go to that branch and then click on it, when there are conflicts it will show you editor where you can fix these.

**Comment by Dragon1573** [comment]
# Reproduce steps

1. First make sure a **Powershell** distribution is installed on your device. The following steps are based on it. The latest **Powershell Core 7** (`pwsh.exe` should be included in your `%PATH%`) is recommended. 
2. Install the latest **[Scoop](https://github.com/lukesampson/Scoop)** distribution. 
3. Attach my [private bucket](https://github.com/Dragon1573/Scoop-Bucket) to **Scoop**. 
4. Install the latest _WhyNotWin11_ via **Scoop**. 
5. Launch the application after successful installation. The application will ONLY displayed in ENGLISH. 

# Solutions

After the succesful installation of _WhyNotWin11_, it creates an **empty** `0804.lang` file with `UTF-16 LE` located in `%LOCALAPPDATA%\WhyNotWin11\Langs`. 

Download and overwrite the `0804.lang` file from this repository DOES solve the problem.

**Comment by Dragon1573** [comment]
I think it's my fault ≧ ﹏ ≦

I previously installed _v2.2.x_ and _v2.3.0.1_, they release several resources to `%LOCALAPPDATA%\WhyNotWin11`. But this is the key point! In the JSON (un)install configuration file of my private Scoop Bucket, I didn't configure a step to remove the whole `%LOCALAPPDATA%\WhyNotWin11` folder after uninstallation. These files will simply stored in my device as some "garbage files". When installing and launching a later version of _WhyNotWin11_, it will check if there already have those resources. The resources didn't refreshed by _WhyNotWin11_ and cause the previous problem. 

I removed the whole folder and reinstall _WhyNotWin11_ v2.3.0.5 via Scoop again. Now all resources are correctly created and the interface is Simplified Chinese as I expected now. Thanks @micwoj92, @htcfreek and @rcmaehl a lot (✿◡‿◡)

**Comment by htcfreek** [comment]
@rcmaehl 
Today it is working for me.

**Comment by htcfreek** [comment]
I closed zhe issue because it's working at the moment.
