### ISSUE TITLE
warning, $hInfo: declared, but not used in func.

### ISSUE THREAD

**Issue by micwoj92** [rcmaehl/WhyNotWin11#428]
Log from CI:
```autoit
"D:\a\WhyNotWin11\WhyNotWin11\WhyNotWin11.au3"(402,18) : warning: $hInfo: declared, but not used in func.
	Local $hInfo[11]
	~~~~~~~~~~~~~~~~^
WhyNotWin11.au3 - 0 error(s), 1 warning(s)
```

https://github.com/rcmaehl/WhyNotWin11/blob/24b5ff99a715d22afc941ea01cf7db7b2a2cfcff/WhyNotWin11.au3#L402

**Comment by rcmaehl** [comment]
> Log from CI:
> 
> ```autoit
> "D:\a\WhyNotWin11\WhyNotWin11\WhyNotWin11.au3"(402,18) : warning: $hInfo: declared, but not used in func.
> 	Local $hInfo[11]
> 	~~~~~~~~~~~~~~~~^
> WhyNotWin11.au3 - 0 error(s), 1 warning(s)
> ```
> 
> https://github.com/rcmaehl/WhyNotWin11/blob/24b5ff99a715d22afc941ea01cf7db7b2a2cfcff/WhyNotWin11.au3#L402

It's used in line 414 and 417 ¯\\_(ツ)\_/¯

**Comment by micwoj92** [comment]
Does this warning also happen on autoit beta?

**Comment by rcmaehl** [comment]
> Does this warning also happen on autoit beta?

Yes

**Comment by mlipok** [comment]
> > Log from CI:
> > ```autoit
> > "D:\a\WhyNotWin11\WhyNotWin11\WhyNotWin11.au3"(402,18) : warning: $hInfo: declared, but not used in func.
> > 	Local $hInfo[11]
> > 	~~~~~~~~~~~~~~~~^
> > WhyNotWin11.au3 - 0 error(s), 1 warning(s)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/rcmaehl/WhyNotWin11/blob/24b5ff99a715d22afc941ea01cf7db7b2a2cfcff/WhyNotWin11.au3#L402
> 
> It's used in line 414 and 417 ¯\_(ツ)_/¯

Will check this. 
Please open and assign to me.

**Comment by mlipok** [comment]
Current version does not have this problem
