### ISSUE TITLE
New CPU Requirements

### ISSUE THREAD

**Issue by Prometheus1400** [rcmaehl/WhyNotWin11#438]
It seems Microsoft has updated the CPU requirements to:
<html>
<body>

Processor: | 1 gigahertz (GHz) or faster with 2 or more cores on a compatible 64-bit processor or System on a Chip (SoC)
-- | --

</body>
</html>

found on: https://www.microsoft.com/en-us/windows/windows-11-specifications

**Comment by rcmaehl** [comment]
`compatible 64-bit processor` links to http://aka.ms/CPUlist which are

https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-amd-processors
https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors
https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-qualcomm-processors

Which are checked currently. I'm not seeing any other changes that aren't already accounted for.

**Comment by Prometheus1400** [comment]
Sorry, I could be wrong then.
Would you happen to have any insight why my processor, "Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz, 3096 Mhz, 4 Core(s), 8 Logical Processor(s)", is not listed as it meets the 1 GHz, 2 core, and 64 bit requirements?

**Comment by rcmaehl** [comment]
> Sorry, I could be wrong then.
> Would you happen to have any insight why my processor, "Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz, 3096 Mhz, 4 Core(s), 8 Logical Processor(s)", is not listed as it meets the 1 GHz, 2 core, and 64 bit requirements?

It appears not to be listed in the official intel supported list. 
![image](https://user-images.githubusercontent.com/716581/124939650-4a278a00-dfd7-11eb-9211-2ed9b9a3f62e.png)

To be fair, the list is completely arbitrary and a lot of the tech media is upset at where Microsoft has cut off CPUs. I wouldn't be surprised if this changes before release.

**Comment by JohnLGalt** [comment]
Those 'requirements' in the OP are not new, they are the same as listed the day of the announcement.

That is the hard floor also mentioned 2 days after the original Win11 announcements.

@rcmaehl already has the actual lists that M$ is saying they support.

**Comment by JohnLGalt** [comment]
Furthermore, realize 2 things:

The CPU chosen to run Windows 11 must meet, at the very least, the requirements in the OP.  In order to be **supported** by M$, they must be on the list.

But all of this is still subject to change, as it's only been a couple of weeks.

**Comment by Prometheus1400** [comment]
Ah okay, it makes sense to me now. Thank you both for explaining!
