### ISSUE TITLE
Who does update the accessibility version?

### ISSUE THREAD

**Issue by htcfreek** [rcmaehl/WhyNotWin11#443]
The strings and checks in accessibility are hardcoded. Who will update them?

Is it possible to get mouse focus and ready values from control to translate them?

**Comment by rcmaehl** [comment]
Accessibility code will be changed from a message box to a setting in the settings menu, strings updated to be in translations, and other fixes come 2.3.2

**Comment by htcfreek** [comment]
> Accessibility code will be changed from a message box to a setting in the settings menu, strings updated to be in translations, and other fixes come 2.3.2

I mean can we get the strings from control. Because at the moment we do the check in accessibility version again. And I don't if I have to update them?!

**Comment by rcmaehl** [comment]
Accessibility was merged in because I got tired of the PR being open. Accessibility is WIP and not implemented in active code right now.
