### ISSUE TITLE
Icons / Taskbar corner overflow

### ISSUE THREAD

**Issue by RgA59** [rcmaehl/WhyNotWin11#446]
Why am I seeing this under Personalization > Taskbar > Taskbar corner overflow? if turned ON nothing shows in the Taskbar. Can't find any reference in Apps or Services. What is your app installing that we're not aware of?

![Screenshot 2021-07-08 172729](https://user-images.githubusercontent.com/82942602/124986464-0140f700-e012-11eb-800e-234d81a9a4e8.png)

**Comment by rcmaehl** [comment]
Taskbar icon is hidden because it's not needed. You can see this here:
https://github.com/rcmaehl/WhyNotWin11/blob/main/WhyNotWin11.au3#L64

Feel free to remove the line and compile per the instructions in README if you want a version with the icon.

**Comment by RgA59** [comment]
how do I remove the line from there? I have no idea how to compile anything

**Comment by RgA59** [comment]
I just want that message out of Settings, please guide how to get rid of it. TIA

**Comment by rcmaehl** [comment]
> I just want that message out of Settings, please guide me how to get rid of it. TIA

Looking up how to remove that now. It'll be just a bit.

**Comment by RgA59** [comment]
ok thanks

**Comment by micwoj92** [comment]
@RgA59 It installs Linux 11

**Comment by rcmaehl** [comment]
You can remove the listing by

1. Open Regedit
2. Navigate to HKEY_CURRENT_USER\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\TrayNotify
3. Delete IconsStream and PastIconsStream

Then

4. Log out and back in

or 

4. Run cmd
5. Run taskkill /f /im explorer.exe
6. Run explorer.exe

This is per Windows 10. Your original question seems that you may be on Windows 11, but it hasn't changed much so the instructions should be the same.

**Comment by RgA59** [comment]
ok I'll give a try and let you know, thanks!

**Comment by RgA59** [comment]
didn't work

**Comment by rcmaehl** [comment]
Give me a bit too look into clearing it manually. Alternatively, if you use ccleaner at all just clear all the caches using it.

**Comment by RgA59** [comment]
I'd rather wait for you, I don't use nor trust cccleaner. Wonder if you can insert a line in the script, run the app again and the message's gone, possible?

**Comment by RgA59** [comment]
I used Partition Wizard to clean the icons cache and that got rid of it, however it also deleted others that i still have in RecycleBin. Can you tell which iconcache belongs to your app?

![Screenshot 2021-07-08 183936](https://user-images.githubusercontent.com/82942602/124994371-2175b380-e01c-11eb-85b1-1655b4d437ac.png)
