### ISSUE TITLE
NVIDIA GeForce RTX 2080 - No WDDM2?

### ISSUE THREAD

**Issue by kingmustard** [rcmaehl/WhyNotWin11#45]
![eb_w11wddm2-1](https://user-images.githubusercontent.com/1947304/123527026-ebf3d080-d6d3-11eb-9bbb-6550e040b084.png)

Running the latest 471.11 (June 22, 2021) drivers and Windows 10 build 21390 (May 26, 2021 dev channel).

Any ideas?

**Comment by micwoj92** [comment]
You probably have wddm3, check latest dev version https://github.com/rcmaehl/WhyNotWin11/actions/runs/974999445

**Comment by kingmustard** [comment]
> You probably have wddm3, check latest dev version https://github.com/rcmaehl/WhyNotWin11/actions/runs/974999445
> (download is under "Artifacts")
I do indeed have WDDM3 it appears, as I'm running build 21390 👍🏻
