### ISSUE TITLE
Symantec Endpoint Protection blocking app

### ISSUE THREAD

**Issue by Scrotos** [rcmaehl/WhyNotWin11#451]
Just a heads up that a prior version got blocked.  I downloaded the latest version and no block yet.  I don't know if anyone else has run into this but if you do:

https://symsubmit.symantec.com/
https://community.broadcom.com/symantecenterprise/communities/community-home/librarydocuments/viewdocument?DocumentKey=bf76e9b6-157b-4246-acf7-e4535b958018&CommunityKey=1ecf5f55-9545-44d6-b0f4-4e4a7f5f5e68&tab=librarydocuments

![image](https://user-images.githubusercontent.com/80605830/125009981-df03a500-e022-11eb-8239-37557cb1a850.png)

**Comment by rcmaehl** [comment]
Yep. Releases used to happen to often no reputation could be made. Releases are coming out about once a week now. #49
