### ISSUE TITLE
Should ignore virtual display driver from Citrix

### ISSUE THREAD

**Issue by Scrotos** [rcmaehl/WhyNotWin11#452]
If you find Citrix Indirect Display Adaptor, you should ignore that entirely for any checks or reporting.  I'm unsure what it may be called in other versions of Citrix Workspace or Citrix Receiver.  (check lower right of pic)

![image](https://user-images.githubusercontent.com/80605830/125011194-3276f280-e025-11eb-8049-d90001fbd5d7.png)

**Comment by htcfreek** [comment]
Oops. This is definitely a bug in our check. 😅

**Comment by rcmaehl** [comment]
@Scrotos can you attach "save all information" from dxdiag on that machine?

**Comment by Scrotos** [comment]
[DxDiag-citrix.txt](https://github.com/rcmaehl/WhyNotWin11/files/6805479/DxDiag-citrix.txt)

Here ya go!

**Comment by rcmaehl** [comment]
@Scrotos That has been excluded. It appears the adapter is issuing the same DDI and Feature level as the physical hardware so hopefully it shouldn't have any issues with DirectX detection but I don't have a lot of citrix machines to verify this. Should work in the latest dev build
