### ISSUE TITLE
Nvidia Geforce GTX1080Ti  Grafikkarte DirectX + WDDM2 rot

### ISSUE THREAD

**Issue by NordinMarkow** [rcmaehl/WhyNotWin11#455]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. 2.3.0.0]

**Additional context**

**Comment by NordinMarkow** [comment]
Nvidia Geforce GTX1080Ti Grafikkarte DirectX + WDDM2 rot

vermutlich liegt das hier auch am zusätzlich vorhanden Citrix Indirect Display  Adapter

![image](https://user-images.githubusercontent.com/87181725/125065252-e45c0080-e0b1-11eb-903d-1f304e747e54.png)

![image](https://user-images.githubusercontent.com/87181725/125065280-ecb43b80-e0b1-11eb-8259-30ff301fe404.png)

**Comment by micwoj92** [comment]
Duplicate #452
