### ISSUE TITLE
Add Internet connection check

### ISSUE THREAD

**Issue by Oleg-Chashko** [rcmaehl/WhyNotWin11#456]
Add Internet connection check.
Windows 11 Home edition requires internet connectivity and a Microsoft account to complete device setup on first use.

**Comment by micwoj92** [comment]
I don't think it's necessary. How else would you download this application?

**Comment by Oleg-Chashko** [comment]
@micwoj92 
That's an option you didn't consider?
What makes you think I downloaded it from the Internet. An acquaintance gave it to me on a usb flash drive.

**Comment by micwoj92** [comment]
Yes, and then you also got windows 11 bootable usb.
I understand your point, but there is such low probability of that.

**Comment by Oleg-Chashko** [comment]
@micwoj92 

Are you sure that all the computers where Windows 11 will be installed will be connected to the Internet?
I'm not so sure about that.

_Yes, and then you also got windows 11 bootable usb._
As surprising as this may sound. But, I all my software on my server. And I exchange a lot, via USB flasher.

_I understand your point, but there is such low probability of that._
It depends on what country you live in and whether it is a city or a village. Some residents are only connected to ADSL, and some have only 3G. If you and I do not have problems with the Internet, it does not mean that others do not have them too.

P.S.: But it's up to you, it's still your project, not mine. ;)

**Comment by Oleg-Chashko** [comment]
I will say this, I am in Germany and here in some villages there is no wired Internet and no mobile normal, people have to go up the mountain to make a call. Deutsche Telekom does not want to install cable because it is not profitable. There is a private satellite Internet for the whole village. With a gigabyte fee for Internet traffic.

**Comment by micwoj92** [comment]
It's not my project.

**Comment by JohnLGalt** [comment]
A simple warning stating that Internet is required should suffice.

**Comment by Oleg-Chashko** [comment]
> It's not my project.

Oh, I'm sorry, I didn't know that.

**Comment by krystian3w** [comment]
@JohnLGalt and maybe detect exist license.

**Comment by Oleg-Chashko** [comment]
> @JohnLGalt and maybe detect exist license.

Yeah, that's a good idea. The program checks the current license and if the Home version of Windows is installed. It displays a warning that the Internet is required.

**Comment by rcmaehl** [comment]
Check has been added, although I'll likely mark it as a warn instead of a failure as it's something that can be fixed with an install of Win 11 Pro instead of Home

**Comment by rcmaehl** [comment]
Check code and disabled GUI elements have both been added. Advanced checks UI, Summary Screen, and Requirements Screen will ironed out be added around 2.5. Closing for now

**Comment by krystian3w** [comment]
May need change to medium/high: https://blogs.windows.com/windows-insider/2022/02/16/announcing-windows-11-insider-preview-build-22557/

In Poland as breaking  news: https://www.instalki.pl/aktualnosci/software/52594-windows-11-instalacja-bez-internetu-konta-microsoft.html

**Comment by rcmaehl** [comment]
> May need change to medium/high: https://blogs.windows.com/windows-insider/2022/02/16/announcing-windows-11-insider-preview-build-22557/
> 
> In Poland as breaking news: https://www.instalki.pl/aktualnosci/software/52594-windows-11-instalacja-bez-internetu-konta-microsoft.html

JOY
