### ISSUE TITLE
Black background in Windows 8.1

### ISSUE THREAD

**Issue by TieLay** [rcmaehl/WhyNotWin11#458]
**Fonts and backgrounf are black**
So in Windows 8.1 x64 any type of tool 

**To Reproduce**
run tool

**Screenshots**
https://disk.yandex.ru/i/f0hA9Y5OW-ixZA

**Desktop (please complete the following information):**
 - OS: Windows 8.1 x64 with .NET 4.8 & updates on 09 july 2021
 - Version 2.3.0.5

**Comment by micwoj92** [comment]
This is already resolved, please check latest dev version.
