### ISSUE TITLE
Direct X & WDDM2 Error

### ISSUE THREAD

**Issue by ccsnet** [rcmaehl/WhyNotWin11#46]
I have the red X for Directx/WDDM2 but a good machine.

Using dxdiag (which might be good to link to on your app for others) I was able to confirm that I am in fact running on Direct X 12 but only WDDM1.2

If these could be seperated it might mean more when 'soft' requirments are better understood.

Finally a key to the errors or a tool tip for each might help others less techy.

Good work though.

T

**Comment by micwoj92** [comment]
Application should already tell you that you have one, but not another. I think that microsoft removed the soft/hard requirement from their page. Could you post screenshot of the application window and your dxdiag.txt?

**Comment by valentyn-l** [comment]
I am running the Windows 11 leaked build with WDDM 3.0 and this app is giving me a red error for that section, lol

**Comment by rcmaehl** [comment]
> I am running the Windows 11 leaked build with WDDM 3.0 and this app is giving me a red error for that section, lol

Known issue, fixed in 2.2.1 shortly

**Comment by micwoj92** [comment]
@ccsnet could you post your dxdiag?
