### ISSUE TITLE
Vulnerability-Disclosure WhyNotWin11, the ReadySunValley app an alternative?

### ISSUE THREAD

**Issue by ed-br** [rcmaehl/WhyNotWin11#460]
Hi,
I read your [Vulnerability-Disclosure](https://github.com/rcmaehl/WhyNotWin11/wiki/Vulnerability-Disclosure-07-09-2021) and also use the open source alternative app [ReadySunValley](https://github.com/builtbybel/ReadySunValley)

It also features a function built in to download WhyNotWin11 and to compare results between these two apps.

If your app is insecure, then that app should not be able to download yours. am i correct?  I would also want to share this with the developer

Regards
Edo

**Comment by micwoj92** [comment]
> If your app is insecure, then that app should not be able to download yours. am i correct? I would also want to share this with the developer

That vulnerability has been fixed and there are many alternatives to this application. Feel free to use whichever fits your needs best.
