### ISSUE TITLE
Improvents - How to use CR/LF in strings

### ISSUE THREAD

**Issue by bovirus** [rcmaehl/WhyNotWin11#465]
**Describe the bug**

IOn the language strings there are some strings that are multiperiod.
How can add CR/LF to teh strings to separate period?

**Comment by micwoj92** [comment]
It doesn't matter if it's CR or LF but newline support for strings is being worked on

**Comment by bovirus** [comment]
@micwoj92

LF and CR has a differnt function.

Example about this strings

A security module used by Windows. All modern AMD CPUs contain one; Some modern Intel CPUs contain one. Check your BIOS/UEFI settings. Refer to your motherboard manual.

How can make add newlines

A security module used by Windows.
All modern AMD CPUs contain one; Some modern Intel CPUs contain one. Check your BIOS/UEFI settings. 
Refer to your motherboard manual.

or using special code like "\n"

A security module used by Windows.\nAll modern AMD CPUs contain one; Some modern Intel CPUs contain one.\nCheck your BIOS/UEFI settings. Refer to your motherboard manual.

**Comment by rcmaehl** [comment]
Currently for Descriptions new lines are added after every period. I don't believe any language uses multiple periods.

**Comment by bovirus** [comment]
@rcmaehl 

Please take care that I'm talkinhg about single long string with multiperiod phrases. 
Not about newlinw between different string.
 
How can check it? I didn't see newline in the string then I cannot see th result.
The strings that I explained has no new line.
The enwline help teh suer to check the info well.
If the string is too long without newline the user attetion is securely less.

**Comment by bovirus** [comment]
Some example aabout long strings multiperiod without newline

RAM=The amount of fast memory installed in your computer. Physically upgradeable in Desktops; Physically upgradeable in high end Laptops.
Secure Boot=A method your motherboard uses to load Windows. If not detected, can be fixed on newer motherboards in your BIOS/UEFI settings. Refer to your motherboard manual.
Storage=The amount of space for data on your disk. Physically upgradeable in high end Laptops.
TPM=A security module used by Windows. All modern AMD CPUs contain one; Some modern Intel CPUs contain one. Check your BIOS/UEFI settings. Refer to your motherboard manual.
