### ISSUE TITLE
WhyNotWin11 2.3.1.0 - GUI Issues

### ISSUE THREAD

**Issue by bovirus** [rcmaehl/WhyNotWin11#466]
@rcmaehl 

**Describe the bug**

Please check screenshot.

"Check update" translated is truncated as text.
I proposse to move this string in the new position on bottom and icnrease text string width

"Architecture" string is not translated and not available in language file.
Please add to the language file.

CPU/GPU on bottom right for me is not reported right (the strings about CPU seems in English).
For me the info should be reported as
CPU = CPU model
GPU = GPU mdoel

**Original screen**
![image](https://user-images.githubusercontent.com/1262554/125187218-c962cb00-e22e-11eb-9772-5f14239c73a2.png)

New GUI with my proposals
![image](https://user-images.githubusercontent.com/1262554/125187395-bac8e380-e22f-11eb-8e6a-23417850bb14.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. 2.3.0.0]

**Additional context**

**Comment by micwoj92** [comment]
1 issue per ticket please. And for general UI improvements see https://github.com/rcmaehl/WhyNotWin11/issues/271
