### ISSUE TITLE
Please Update the Japanese translation of "Boot Method".

### ISSUE THREAD

**Issue by arigayas** [rcmaehl/WhyNotWin11#489]
**Describe the bug**
In the English version, it is "Boot Method".
In Japanese translation, it is "BIOSの種類".

If you translate the Japanese translation of "BIOSの種類" into English, it becomes "BIOS Type", so it feels a little strange. 
I think it is better to change to the Japanese translation of "起動方式".

It may be strange English because I used Google Translate.

**ScreenShots**
Japanese Version [2.3.1.0]  **BIOSの種類**
![image](https://user-images.githubusercontent.com/11251874/125212274-2f128e00-e2e7-11eb-8779-aea063f39976.png)
English Version [2.3.1.0]  **Boot Method**
![image](https://user-images.githubusercontent.com/716581/125180558-507d5800-e1c9-11eb-8f0d-106f660f5528.png)

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Version [2.3.1.0]

**Comment by micwoj92** [comment]
@yuki-gh @goahi @syobon-tech @arakim

Could you guys discuss? Thanks.

**Comment by yuki-gh** [comment]
I first translated it literally as 起動方式, but I don't stick to it.
BIOSの種類 is also understandable enough, and it doesn't break alphabetical order :-)

**Comment by arigayas** [comment]
> I first translated it literally as 起動方式, but I don't stick to it.

Thank you for understanding.

**Comment by micwoj92** [comment]
#491 was merged, closing
