### ISSUE TITLE
Multiple Vendors False Positives

### ISSUE THREAD

**Issue by llacb47** [rcmaehl/WhyNotWin11#49]
FYI -- The [most recent artifact](https://github.com/rcmaehl/WhyNotWin11/actions/runs/975038145) of `WhyNotWin11_x86.exe` is flagged as a virus (`Program:Win32/Wacapew.C!ml`) by Microsoft/Windows Defender.

https://www.virustotal.com/gui/file/d93b3da670d96e80d2a3ec0bbea61f7b33b974604a723f3791b515204cc41337/detection

----------------
More info on autoit forums
https://www.autoitscript.com/forum/topic/34658-are-my-autoit-exes-really-infected/

**Comment by micwoj92** [comment]
These false positives are known issues, just report file as safe and hope that they fix it.

**Comment by rcmaehl** [comment]
It appears both of these vendors only accept FPs via email.

[Contact BKav](mailto:bkav@bkav.com.vn?subject=False%20Positive%20Submission&amp;body=The%20sample%20is%20in%20a%20password%20protected%207z%20file%0A%0AThe%20password%20for%20the%20attachment%20is%20infected) - Attachment must be .7z file with password "infected"
[Contact Sophos](mailto:detections@spybot.info?subject=False%20Positive%20Submission&amp;body=The%20sample%20is%20in%20a%20password%20protected%20zip%20file%0A%0AThe%20password%20for%20the%20attachment%20is%20infected)  - Attachment must be .zip file with password "infected"

**Comment by rcmaehl** [comment]
This should be partially improved with the removal of requiring admin rights

**Comment by XUTOS83** [comment]
Bkav Pro
W32.FamVTAppLQNE.Trojan

Sophos
Generic ML PUA (PUA)

Palo Alto Networks
Generic.ml



https://www.virustotal.com/gui/file/4505a6ed4a5f8a7401d17f76ee8ba73340de5e2905fee2c6c8551d0852d29e9c/detection

**Comment by testermania** [comment]
v2.3.04
https://www.virustotal.com/gui/file/348a2d60ce747aa5d61f58693a335f16b839fc930b19c3ef5160b33a1f1c1ea3/detection

**Comment by micwoj92** [comment]
The issue will stay pinned but I'll close it, because it's not really something that can be fixed. Just report as false positives. Also the releases will be less often, so the executables from releases will have more time to get unflagged and get good scores on virustotal.

**Comment by TruongTanLuc201270** [comment]
Version 2.6.0.0, 2 virus found
![Screenshot_20240119-134847_Samsung Internet](https://github.com/rcmaehl/WhyNotWin11/assets/145727083/75ed0360-5c1b-4d9a-976c-44865cd25cfc)
![Screenshot_20240119-134919_Samsung Internet](https://github.com/rcmaehl/WhyNotWin11/assets/145727083/6ee94e3a-f659-4333-9db7-d58795634c7c)
