### ISSUE TITLE
UI Display issue - Tickboxes not displaying corectly on v2.3.1.0/2.3.1.1 , was ok on 2.3.0.3

### ISSUE THREAD

**Issue by garfin-au** [rcmaehl/WhyNotWin11#490]
![2 3 1 0](https://user-images.githubusercontent.com/8000828/125216117-7e18ed00-e300-11eb-810c-783a8769bf34.JPG)

Not sure what further to add.. machine is currently on Win10 Pro x64 Ver 1909.

**Comment by micwoj92** [comment]
Maybe you are missing some fonts or have them setup inproperly? checkmark is "10003" you can find how it should look like online.

**Comment by garfin-au** [comment]
![h81m](https://user-images.githubusercontent.com/8000828/125216442-86bdf300-e301-11eb-8308-4d6380d1409d.JPG)
Ahh.. its just the 'Green' Checkbox it seems. (re-tested on a lesser system.)

**Comment by micwoj92** [comment]
My first guess would be to check the first build that introduced this checkmark to see if the issue is since beginning or since some other update https://github.com/rcmaehl/WhyNotWin11/runs/3025663646 (click on artifact and download)

And then check Windows character map for that symbol, maybe try different font in lang files?

**Comment by garfin-au** [comment]
Yes, issue is in first build also. If nobody else is reporting issue, then maybe its just (some of) my pc's.  I just tried a 3rd machine and that one is displaying ok.  (Green is good , Red is bad... that's all that matters.)

**Comment by htcfreek** [comment]
Which OS. I thought the char was available since unicode ??.

**Comment by htcfreek** [comment]
Symbol should be available 1993 (Unicode 1.1): https://www.compart.com/de/unicode/U+2713

Could it be a missing font?

**Comment by krystian3w** [comment]
Similar source: https://www.fileformat.info/info/unicode/char/2713/index.htm

**Comment by rcmaehl** [comment]
Yeah, likely a font issue: https://www.fileformat.info/info/unicode/char/2713/fontsupport.htm

**Comment by Oleg-Chashko** [comment]
@rcmaehl 
In order not to have problems with fonts. It is better to draw an icon. And show the icon instead of the font.

**Comment by rcmaehl** [comment]
Resolved.
