### ISSUE TITLE
Version 2.3.1 - Github/Discord/LTT has no translation

### ISSUE THREAD

**Issue by bovirus** [rcmaehl/WhyNotWin11#496]
@rcmaehl 

**Describe the bug**
<br>A clear and concise description of what the bug is.

The baloon help about Github/Discord/LTT has not translation

Proposal for baloon help

GitHub -> WhynotWin11 repository on Github
Discord -> WhyNotWin11 on Discord
LTT -> WhyNotWin11 on Linux Tech Tips

and explain better about donate link
 
Donate -> Donate to WhynotWin11 via Paypal

Thanks.

**To Reproduce**
<br>Steps to reproduce the behavior:

**Expected behavior**
<br>A clear and concise description of what you expected to happen.

**Screenshots**
<br>If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - Version [e.g. 2.3.0.0]

**Additional context**
<br>Add any other context about the problem here.

**Comment by micwoj92** [comment]
Maybe that's because "Github/Discord/LTT" are the same word in each language?
