### ISSUE TITLE
Use supported CPU list from Microsoft

### ISSUE THREAD

**Issue by mondagotjl** [rcmaehl/WhyNotWin11#5]
I know you've already got an item for Supported CPUs on your to-do list, but in case you haven't found it already here is the official list from Microsoft: https://docs.microsoft.com/en-us/windows-hardware/design/minimum/windows-processor-requirements

Thanks for your nice tool btw!

**Comment by Erisa** [comment]
Tagging onto this since I don't want to create a new issue where it's not needed, my Ryzen 2700X entirely passes the requirements published by Microsoft yet this tool shows a question mark:
![image](https://user-images.githubusercontent.com/14004943/123429656-16079e80-d5bf-11eb-924e-c1e805087e3d.png)

**Comment by bastianfbr** [comment]
Same for my Ryzen 5 3500U
![image](https://user-images.githubusercontent.com/29505634/123429938-d72a1680-d5c7-11eb-9bca-48abaeb4e36e.png)

**Comment by Erisa** [comment]
Same is also true for Snapdragon: 8cx:
![image](https://user-images.githubusercontent.com/14004943/123430136-bc53a400-d5bf-11eb-8d01-2213f9724d9b.png)
Which is also on Microsoft's list

**Comment by Sumitdhiman** [comment]
Same for Core i5 10th generation.

**Comment by bl-ue** [comment]
+1, Intel i5-8500 & i9-9900K not recognized though they're listed [here](https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors).

**Comment by rcmaehl** [comment]
Yep. Same issue with #3. Will get started on this shortly!

**Comment by bscout9956** [comment]
Also, please do a check for the Ryzen 5 1600 AF variant, this variant is now being manufactured and sold under a 12nm process node, so it is essentially a Zen+ processor and should work with Windows 11.
In fact the Windows 11 tool tells me I have full compatibility.
![image](https://user-images.githubusercontent.com/24628639/123457637-7fd17980-d5ba-11eb-90cb-6ee8f731aa22.png)

**Comment by GTAXL** [comment]
Do you know if the CPU is a requirement, or just a recommendation? Does this just affect i series Intel CPUs or is there specific Xeon's and up? The supported CPU support list is not really complete. My CPU for example, Intel Xeon E5-1650 v3 isn't even listed on Windows 7 or Windows 10 supported CPU list, yet works just fine on both operating systems. No peep of another CPU I use, Intel Xeon E5-2689 v4 on ANY of the Windows operating systems. I don't trust the list.

**Comment by rcmaehl** [comment]
> Do you know if the CPU is a requirement, or just a recommendation? Does this just affect i series Intel CPUs or is there specific Xeon's and up? The supported CPU support list is not really complete. My CPU for example, Intel Xeon E5-1650 v3 isn't even listed on Windows 7 or Windows 10 supported CPU list, yet works just fine on both operating systems. No peep of another CPU I use, Intel Xeon E5-2689 v4 on ANY of the Windows operating systems. I don't trust the list.

CPU is a recommendation as long as all other factors are met. Closing the issue as this has been added in 2.1.0

**Comment by matacoder** [comment]
Ryzen 3700X is not passing (but should)
