### ISSUE TITLE
[Regex Expert Needed] WDDM not recognized

### ISSUE THREAD

**Issue by saadibadr** [rcmaehl/WhyNotWin11#51]
![image](https://user-images.githubusercontent.com/21370630/123529921-0c7c5480-d6ed-11eb-9e19-b77822fd8130.png)

**Comment by rcmaehl** [comment]
Can you post your `Save All Information` file from dxdiag. I believe I've added a patch for this for next release but I'd like to be sure.

**Comment by saadibadr** [comment]
Of course, here you go
[DxDiag.txt](https://github.com/rcmaehl/WhyNotWin11/files/6720950/DxDiag.txt)

**Comment by micwoj92** [comment]
Are you using the latest version?

**Comment by saadibadr** [comment]
Yes
![image](https://user-images.githubusercontent.com/21370630/123532433-e9f63580-d704-11eb-8190-e94cd2125508.png)

**Comment by micwoj92** [comment]
Not driver, latest version of WhyNotWin11

**Comment by rcmaehl** [comment]
![image](https://user-images.githubusercontent.com/716581/123533408-49434e00-d6e3-11eb-95ea-83c0bf8894b5.png)
Remind me to kill the dxdiag devs

**Comment by rcmaehl** [comment]
Please try the latest action build once it completes
https://github.com/rcmaehl/WhyNotWin11/actions/runs/975587123

**Comment by dheeraj-rn** [comment]
For me its taking forever to do that test.
![image](https://user-images.githubusercontent.com/7339353/123535383-23e52d00-d741-11eb-8a25-b7dd07efd789.png)

**Comment by rcmaehl** [comment]
> For me its taking forever to do that test.
> ![image](https://user-images.githubusercontent.com/7339353/123535383-23e52d00-d741-11eb-8a25-b7dd07efd789.png)

It may take up to 60 seconds longer than any other test to complete. You can check the status by seeing if dxdiag is still running in taskmgr.

**Comment by dheeraj-rn** [comment]
> n any other test to complete. You can check the status by seeing if dxdiag is still running in taskmgr.

Still having the same issue.
![image](https://user-images.githubusercontent.com/7339353/123535640-a91d1180-d742-11eb-953d-c9b12722a756.png)

**Comment by rcmaehl** [comment]
> > n any other test to complete. You can check the status by seeing if dxdiag is still running in taskmgr.
> 
> Still having the same issue.
> ![image](https://user-images.githubusercontent.com/7339353/123535640-a91d1180-d742-11eb-953d-c9b12722a756.png)

Are you using https://github.com/rcmaehl/WhyNotWin11/suites/3095113623/artifacts/70721107 ?

If so, can you post your Save All Information file from dxdiag?

**Comment by bzhmaddog** [comment]
I have the same issue with my RX480 from Asus. DXDIAG says WDDM2.7
-----------------------------------------------
Display Devices
---------------
           Card name: Radeon (TM) RX 480 Graphics
        Manufacturer: Advanced Micro Devices, Inc.
           Chip type: AMD Radeon Graphics Processor (0x67DF)
            DAC type: Internal DAC(400MHz)
         Device Type: Full Device (POST)
          Device Key: Enum\PCI\VEN_1002&DEV_67DF&SUBSYS_04FB1043&REV_C7
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
 Device Problem Code: No Problem
 Driver Problem Code: Unknown
      Display Memory: 16332 MB
    Dedicated Memory: 8171 MB
       Shared Memory: 8161 MB
        Current Mode: 1920 x 1080 (32 bit) (60Hz)
         HDR Support: Not Supported
    Display Topology: Extend
 Display Color Space: DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
     Color Primaries: Red(0.648438,0.338867), Green(0.282227,0.602539), Blue(0.142578,0.070312), White Point(0.313477,0.329102)
   Display Luminance: Min Luminance = 0.500000, Max Luminance = 270.000000, MaxFullFrameLuminance = 270.000000
        Monitor Name: Generic PnP Monitor
       Monitor Model: PLB2712HDS
          Monitor Id: IVM6602
         Native Mode: 1920 x 1080(p) (60.000Hz)
         Output Type: DVI
Monitor Capabilities: HDR Not Supported
Display Pixel Format: DISPLAYCONFIG_PIXELFORMAT_32BPP
      Advanced Color: Not Supported
         Driver Name: C:\WINDOWS\System32\DriverStore\FileRepository\u0367492.inf_amd64_dc9dba40afc0f9b5\B367342\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\u0367492.inf_amd64_dc9dba40afc0f9b5\B367342\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\u0367492.inf_amd64_dc9dba40afc0f9b5\B367342\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\u0367492.inf_amd64_dc9dba40afc0f9b5\B367342\amdxc64.dll
 Driver File Version: 27.20.21003.8013 (English)
      Driver Version: 27.20.21003.8013
         DDI Version: 12
      Feature Levels: 12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1
        Driver Model: WDDM 2.7
 Hardware Scheduling: Supported:False Enabled:False 
 Graphics Preemption: Primitive
  Compute Preemption: DMA
            Miracast: Not Supported
      Detachable GPU: No
 Hybrid Graphics GPU: Not Supported
      Power P-states: Not Supported
      Virtualization: Paravirtualization 
          Block List: DISABLE_HWSCH
  Catalog Attributes: Universal:False Declarative:True 
   Driver Attributes: Final Retail
    Driver Date/Size: 11/05/2021 02:00:00, 1959392 bytes
         WHQL Logo'd: Yes
     WHQL Date Stamp: Unknown
   Device Identifier: {D7B71EE2-249F-11CF-BE6C-F0767CC2D635}
           Vendor ID: 0x1002
           Device ID: 0x67DF
           SubSys ID: 0x04FB1043
         Revision ID: 0x00C7
  Driver Strong Name: oem19.inf:cb0ae414b19b97d1:ati2mtag_Polaris10:27.20.21003.8013:PCI\VEN_1002&DEV_67DF&REV_C7
      Rank Of Driver: 00CF2000
         Video Accel: Unknown
         DXVA2 Modes: DXVA2_ModeMPEG2_VLD  DXVA2_ModeMPEG2_IDCT  DXVA2_ModeH264_VLD_NoFGT  {4245F676-2BBC-4166-A0BB-54E7B849C380}  {6719B6FB-5CAD-4ACB-B00A-F3BFDEC38727}  {9901CCD3-CA12-4B7E-867A-E2223D9255C3}  DXVA2_ModeHEVC_VLD_Main  {EA72396A-67EC-4781-BEDE-56F498F04EF2}  {C152CA8F-738C-461B-AD89-FC292CF8F162}  {514A356C-7027-4AFF-8A60-AFD2C1F672F1}  DXVA2_ModeH264_VLD_Stereo_Progressive_NoFGT  DXVA2_ModeH264_VLD_Stereo_NoFGT  DXVA2_ModeVC1_VLD  {CA15D19A-2B48-43D6-979E-7A6E9C802FF8}  {7C74ADC6-E2BA-4ADE-86DE-30BEABB40CC1}  DXVA2_ModeMPEG4pt2_VLD_AdvSimple_NoGMC  {D1C20509-AE7B-4E72-AE3B-49F88D58992F}  {103473E4-10EA-11DF-9A92-2BA055D89593}  {84AD67F6-4C21-419A-9F0B-24F0578906C1}  {725AD240-786C-471E-AD3C-38F739936517}  {95664FF5-9E03-4C74-BB4F-9178D6035E58}  DXVA2_ModeHEVC_VLD_Main10  {65D1FA41-58AF-453A-9CAB-5D981156DA9F}  {2DB154B6-DBB2-4079-A3FF-60D7A898A6AB}  {C74A3FD0-D713-4581-A02E-8EDFB112ACE3}  {603A4756-A864-4F91-BB62-2C935B7A1391}  {C58B9A06-7E89-11E1-BB00-70B34824019B}  
      Deinterlace Caps: n/a
        D3D9 Overlay: Not Supported
             DXVA-HD: Not Supported
        DDraw Status: Enabled
          D3D Status: Enabled
          AGP Status: Enabled
       MPO MaxPlanes: 1
            MPO Caps: Not Supported
         MPO Stretch: Not Supported
     MPO Media Hints: Not Supported
         MPO Formats: Not Supported
    PanelFitter Caps: Not Supported
 PanelFitter Stretch: Not Supported

**Comment by dheeraj-rn** [comment]
> If so, can you post your Save All Information file from dxdiag?

Yes. I tried with both the links you shared, got the same output.
[DxDiag.txt](https://github.com/rcmaehl/WhyNotWin11/files/6721181/DxDiag.txt)

**Comment by rcmaehl** [comment]
Please try the latest action build
https://github.com/rcmaehl/WhyNotWin11/suites/3096312388/artifacts/70750372

**Comment by bzhmaddog** [comment]
> Please try the latest action build
> https://github.com/rcmaehl/WhyNotWin11/suites/3096312388/artifacts/70750372

Works for me with this one !

**Comment by rcmaehl** [comment]
Marking as resolved in 2.2.3

**Comment by dheeraj-rn** [comment]
Unfortunately the fix didn't work for me. Tried the build you linked above and v2.2.4.0
![image](https://user-images.githubusercontent.com/7339353/123548753-c2927d80-d783-11eb-9785-459a6c913680.png)

**Comment by rcmaehl** [comment]
> Unfortunately the fix didn't work for me. Tried the build you linked above and v2.2.4.0
> ![image](https://user-images.githubusercontent.com/7339353/123548753-c2927d80-d783-11eb-9785-459a6c913680.png)

DXDIAG is going to be the death of me

**Comment by rcmaehl** [comment]
Hi all, I'm attempting to fix this with regex is which is not really my strong suit. If you are a regex expert, you can read the AutoIt Regex documentation here: https://www.autoitscript.com/autoit3/docs/functions/StringRegExp.htm

**Comment by saadibadr** [comment]
> Please try the latest action build
> https://github.com/rcmaehl/WhyNotWin11/suites/3096312388/artifacts/70750372

I confirm, it works

![image](https://user-images.githubusercontent.com/21370630/123549116-7c2b2780-d75f-11eb-8e68-886bd98e5192.png)

**Comment by saadibadr** [comment]
> Unfortunately the fix didn't work for me. Tried the build you linked above and v2.2.4.0
> ![image](https://user-images.githubusercontent.com/7339353/123548753-c2927d80-d783-11eb-9785-459a6c913680.png)

Can you post your **_Save All Information file_** from dxdiag

Also, can you please try this build https://github.com/rcmaehl/WhyNotWin11/suites/3096312388/artifacts/70750372

**Comment by dheeraj-rn** [comment]
@saadibadr 
Yes I tried it. Getting the same. I've uploaded the dxdiag.txt file above

**Comment by dheeraj-rn** [comment]
@rcmaehl Turns out the DDI Version you are checking is Unknown for me `DDI Version: Unknown` .
Removing my old dxdiag output and attaching new one. 
[DxDiag.txt](https://github.com/rcmaehl/WhyNotWin11/files/6721814/DxDiag.txt)
https://github.com/rcmaehl/WhyNotWin11/blob/808a9e1eefafe3d1737970a590303952a0887635/WhyNotWin11.au3#L417

**Comment by rcmaehl** [comment]
@dheeraj-rn Closing this one then and merging with #58 as that will fix the issue

**Comment by saadibadr** [comment]
> Hi all, I'm attempting to fix this with regex is which is not really my strong suit. If you are a regex expert, you can read the AutoIt Regex documentation here: https://www.autoitscript.com/autoit3/docs/functions/StringRegExp.htm

I just started autoit coding so, here is a sample you can work on it :

`#include <MsgBoxConstants.au3>

; Extract dxdiag log in XML : dxdiag /whql:off /x dxdiag.xml
Local $oXML = ObjCreate("Microsoft.XMLDOM")
$oXML.setProperty("SelectionLanguage", "XPath")
$oXML.load("dxdiag.xml")

Local $oWDDMs = $oXML.selectNodes("//DxDiag/DisplayDevices/DisplayDevice/DriverModel")
For $oWDDM In $oWDDMs
   Local $vWDDM_v = StringTrimLeft($oWDDM.text, 5)  ;Get only the version number
Next

If $vWDDM_v > 2 Then
    MsgBox($MB_SYSTEMMODAL, "WDDM", "OK")
ElseIf $vWDDM_v < 0 Then
    MsgBox($MB_SYSTEMMODAL, "WDDM", "KO")
Else
    MsgBox($MB_SYSTEMMODAL, "WDDM", "ERROR")
EndIf

; You can do the same with DirecX version
Local $oDirectXs = $oXML.selectNodes("//DxDiag/SystemInformation/DirectXVersion")
For $oDirectX In $oDirectXs
   Local $vDirectX_v = StringTrimLeft($oDirectX.text, 8)
Next

If $vDirectX_v > 2 Then
    MsgBox($MB_SYSTEMMODAL, "DirectX", "OK")
ElseIf $vDirectX_v < 0 Then
    MsgBox($MB_SYSTEMMODAL, "DirectX", "KO")
Else
    MsgBox($MB_SYSTEMMODAL, "DirectX", "ERROR")
EndIf`

**Comment by rcmaehl** [comment]
I'll take a look at this shortly. 😄
