### ISSUE TITLE
Intel UHD 620 -> (1) compatible and (2) not compatible

### ISSUE THREAD

**Issue by tawissus** [rcmaehl/WhyNotWin11#511]
**Describe the bug**
<br>PC1: **Intel UHD 620** is **compatible** - Lenovo X390 Yoga - Driver 27.20.100.9168 (2021-01-08)
<br>PC2: **Intel UHD 620** is **not compatible** - Asus Zenbook 14 - Driver 27.20.100.9466 (2021-03-30)

**To Reproduce**
<br>Steps to reproduce the behavior:
1. Check PC1 / PC2
2. See error

**Expected behavior**
<br>Same device should get the same result

**Screenshots**
**Desktop (please complete the following information):**
 - OS: Win10 21H1
 - V. 2.3.1.0

**Additional context**
![Asus Zenbook](https://user-images.githubusercontent.com/1453423/125624167-b799eccc-f14e-43c6-82fb-88a81b44962c.png)
![Lenovo Thinkpad](https://user-images.githubusercontent.com/1453423/125624171-5984e12e-86c2-475f-8361-eec2d752cd96.jpg)

**Comment by rcmaehl** [comment]
Can you post the `Save All Information` file from dxdiag in both machines?

**Comment by tawissus** [comment]
When calling dxdiag for the first time, some error messages appeared. Now the check is successful on both PCs.  Thank you!
