### ISSUE TITLE
Can't read all of the comment in Japanese

### ISSUE THREAD

**Issue by pklion** [rcmaehl/WhyNotWin11#516]
**Describe the bug**
We can't read all of the comment the "architecture (CPU + OS)" in Japanese.

**To Reproduce**
Open the app in Japanese

**Expected behavior**
Resize comment to fit to the textbox size

**Screenshots**
![image](https://user-images.githubusercontent.com/78145811/125778572-89a5d6d5-09a3-406b-bcb6-07d6191a0b07.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [v2.3.1.1 dev 07/15]

**Additional context**

**Comment by PriitUring** [comment]
The Architecture (CPU + OS) text was recommended to be removed long ago according to latest 0000.lang file, to be just Architecture, but many language files translations still haven't been updated by developer or current translators.

You can edit and update the .lang file both locally and later in GitHub.

Here's little bit written about translations and also how to check translation locally:
https://github.com/rcmaehl/WhyNotWin11/blob/main/Langs/0000-translating-guidelines.md

**Comment by micwoj92** [comment]
https://github.com/rcmaehl/WhyNotWin11/commit/c2d27f9ab07a8bd7fc6f6477bf8f7049bd537b31
