### ISSUE TITLE
Bug-in-a-feature: WDDM checks fail on non-Windows 10 operating systems

### ISSUE THREAD

**Issue by SigmaTel71** [rcmaehl/WhyNotWin11#517]
**Describe the bug**
<br>GTX 1660 is detected as a videocard that does not support WDDM 2.0

**To Reproduce**
<br>Steps to reproduce the behavior:
1. Run a program on Windows 8.1.
2. Wait till the checks will be completed

**Expected behavior**
<br>WDDM version will be looked up online to get correct data or at least warning about false-positive version detection appears.

**Screenshots**
![image](https://user-images.githubusercontent.com/17989678/125821630-40eff07d-fb00-4295-8878-88134b7076f9.png)
![image](https://user-images.githubusercontent.com/17989678/125821657-6e5384ea-ffd3-44ae-9288-576b06c771c7.png)

**Desktop (please complete the following information):**
 - OS: Windows 8.1 Pro
 - Version 6.3.9600

**Additional context**
<br>NVIDIA GeForce GTX 1660 supports WDDM >=2.0 drivers on Windows 10 and higher, why don't create some form of database to store info about hardware information and make the program look up info there to avoid false-positive unsupported hardware errors on **non-Windows 10** operating systems?

**Comment by rcmaehl** [comment]
Yep. I'll see of I can start work on #58 here in a bit

**Comment by micwoj92** [comment]
duplicate #58, I'll close when I get on pc


W dniu czwartek, 15 lipca 2021 SigmaTel71 ***@***.***>
napisał(a):
