### ISSUE TITLE
Does not check if already on Win11

### ISSUE THREAD

**Issue by JoKalliauer** [rcmaehl/WhyNotWin11#518]
**Expected behavior**

Schould check if already on Win11

**Screenshots**

![WhyNotWin11](https://user-images.githubusercontent.com/15687581/125989390-4ce6de9b-0c9b-469a-8b04-3cf902b068be.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 21H2 (Build 22000.71)

**Comment by JohnLGalt** [comment]
You can not meet the full hardware requirements and still be running Windows 11, as the Insiders Dev channel builds will install on all sorts of machines - too low CPU, MBR (thus no secure boot) and TPM 1.2, too, have been reported as still allowing install to go forward.  

Pretty sure any user who is using Windows 11 also already knows they are on it.

**Comment by krystian3w** [comment]
We have pop-up: https://github.com/rcmaehl/WhyNotWin11/blob/1c72f3d55c757cabcd169caff91365312234241a/WhyNotWin11.au3#L77-L79

see `_Translate(@MUILang, "You're running the latest build!"))`.

**Comment by rcmaehl** [comment]
Won't fix. See @krystian3w's reply above.
