### ISSUE TITLE
Got "False GB" RAM in a IPC with 2GB integrated RAM

### ISSUE THREAD

**Issue by Ronnier33** [rcmaehl/WhyNotWin11#527]
![捕获](https://user-images.githubusercontent.com/43734592/126864970-342f025e-e943-447c-bdbb-074adad1d004.PNG)
just like the snap.

**Comment by rcmaehl** [comment]
I'll take a look but it might be a Windows 11 specific issue

**Comment by rcmaehl** [comment]
Please try https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

**Comment by Ronnier33** [comment]
> Please try https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

yeap, it is ok now.
