### ISSUE TITLE
Secure Boot incorrectly detected

### ISSUE THREAD

**Issue by AwlsomeAlex** [rcmaehl/WhyNotWin11#529]
Attached is the latest nightly build of WhyNotWin11. As you can see it reports that Secure Boot is enabled.
I can confirm from inside my BIOS that it is not enabled.
System Information and the Registry Check also confirm Secure Boot is not enabled.
Confirm-SecureBootUEFI also returns False.

![WNWIN11](https://user-images.githubusercontent.com/11639639/126882217-632f3dd6-19aa-48ea-baa3-6c605aaddcbf.PNG)
![Reg](https://user-images.githubusercontent.com/11639639/126882218-cd2b22ab-d342-49be-b772-19a1c6b7bc5c.PNG)
![SecureBoot](https://user-images.githubusercontent.com/11639639/126882219-647c1e6d-1e45-4bf7-be06-fd0c68637522.PNG)

**Comment by rcmaehl** [comment]
Will fix when I get back home.

**Comment by rcmaehl** [comment]
Please wait a few minutes for CI to compile the dev build then download and run it.

**Comment by AwlsomeAlex** [comment]
@rmcpantoja Cool it says supported now. Quick question, is there solid Microsoft Documentation that says Secure Boot won't need to be enabled for Windows 11 GA? I know the requirements say "Secure Boot capable", but it sounds like poor languages as to how they're enforcing it.

**Comment by rcmaehl** [comment]
> @rmcpantoja Cool it says supported now. Quick question, is there solid Microsoft Documentation that says Secure Boot won't need to be enabled for Windows 11 GA? I know the requirements say "Secure Boot capable", but it sounds like poor languages as to how they're enforcing it.

Yeah, the requirements are still a mess
