### ISSUE TITLE
Powershell Commands Not Parsing on Some Non-English Systems

### ISSUE THREAD

**Issue by 97I8TOE47K** [rcmaehl/WhyNotWin11#53]

**Comment by MisakaSakura** [comment]
Me too, secure boot status detection is inaccurate
![image](https://user-images.githubusercontent.com/30547550/123533135-8a6c4a00-d745-11eb-9a28-99feeff95faa.png)
![image](https://user-images.githubusercontent.com/30547550/123533140-948e4880-d745-11eb-9f43-4a3e0cdd4d67.png)

**Comment by rcmaehl** [comment]
I'm going to assume this is some issue with Localization. 

Can you all try `Get-Partition -DriveLetter C | Get-Disk | Select-Object -Property PartitionStyle` as well?

**Comment by MisakaSakura** [comment]
> I'm going to assume this is some issue with Localization.
> 
> Can you all try `Get-Partition -DriveLetter C | Get-Disk | Select-Object -Property PartitionStyle` as well?

For your proposal.
![image](https://user-images.githubusercontent.com/30547550/123533625-66ab0300-d749-11eb-8ff9-fddbe14e3050.png)

**Comment by rcmaehl** [comment]
Needs to be ran as one command
![image](https://user-images.githubusercontent.com/716581/123533649-04b8b200-d6e5-11eb-88df-f688d8531db9.png)

**Comment by MisakaSakura** [comment]
> Needs to be ran as one command
> ![image](https://user-images.githubusercontent.com/716581/123533649-04b8b200-d6e5-11eb-88df-f688d8531db9.png)

Obviously it's still gpt.
![image](https://user-images.githubusercontent.com/30547550/123533737-75de8080-d74a-11eb-99d8-7f56c71ca0d5.png)

**Comment by rcmaehl** [comment]
Odd

**Comment by maksimus256** [comment]
I have this problem too, I have a GTP system drive and two other MBRs.
![1](https://user-images.githubusercontent.com/17926337/123539146-7256f380-d762-11eb-95cc-72ca096e692a.png)
![2](https://user-images.githubusercontent.com/17926337/123539147-72ef8a00-d762-11eb-8563-b11ee158c4dd.png)
![3](https://user-images.githubusercontent.com/17926337/123539148-73882080-d762-11eb-983e-f568f50a1c5c.png)

**Comment by rcmaehl** [comment]
I'll need to install a few locales and language packs to try to reproduce this. It seems to mainly occur on Non-English Systems.

**Comment by billysielu** [comment]
May be failures to read the temp file.

**Comment by rcmaehl** [comment]
> May be failures to read the temp file.

Good point. Boot Method is failing as well. Odd

**Comment by billysielu** [comment]
The dxdiag file seems to be working, the obvious difference being the way it's defined. 
Maybe try: 
`$hFile = _TempFile(@TempDir, "wnw11")`
@ WhyNotWin11.au3 line 176

**Comment by rcmaehl** [comment]
@maksimus256 @MisakaSakura

Can you all run the file in the attached zip?
[Test.zip](https://github.com/rcmaehl/WhyNotWin11/files/6721944/Test.zip)

**Comment by MisakaSakura** [comment]
> @maksimus256 @MisakaSakura
> 
> Can you all run the file in the attached zip?
> [Test.zip](https://github.com/rcmaehl/WhyNotWin11/files/6721944/Test.zip)

![image](https://user-images.githubusercontent.com/30547550/123570269-6dde1980-d7fa-11eb-8afb-ae0178d964bb.png)
What does that mean?

**Comment by MisakaSakura** [comment]
> I'll need to install a few locales and language packs to try to reproduce this. It seems to mainly occur on Non-English Systems.

Maybe not necessarily this problem, because your software is very useful in coolapk, a Chinese community, like me, which is actually in the minority.

**Comment by rcmaehl** [comment]
> > @maksimus256 @MisakaSakura
> > Can you all run the file in the attached zip?
> > [Test.zip](https://github.com/rcmaehl/WhyNotWin11/files/6721944/Test.zip)
> 
> ![image](https://user-images.githubusercontent.com/30547550/123570269-6dde1980-d7fa-11eb-8afb-ae0178d964bb.png)
> What does that mean?

Means powershell output is failing :\, Doesn't even create an output file.

**Comment by barbarajoost** [comment]
Same issue here. System Locale is "German (Germany)".

**Comment by maksimus256** [comment]
> @maksimus256 @MisakaSakura
> 
> Can you all run the file in the attached zip?
> [Test.zip](https://github.com/rcmaehl/WhyNotWin11/files/6721944/Test.zip)

![image](https://user-images.githubusercontent.com/17926337/123623140-51140700-d837-11eb-82c1-375f38d60429.png)

**Comment by htcfreek** [comment]
@rcmaehl 
Two thoughts:
- It may be goid to define encodeing in Powershell and AutoIt to avoid encoding bugs.
- It may be good to use `-Force` in Powershell for overwrite read-only files.
- With `(command).Property` you get the value insted the table. `(Get-Partition -DriveLetter C: | Get-Disk | Select-Object -Property PartitionStyle).PartitionStyle`
- You sould add `-ExecutionPolicy Bypass` to all Powershell commands.


https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-5.1#parameters

**Comment by SaltyMonkey** [comment]
@rcmaehl just solved same issue for myself - issue was in incorrect powershell.exe 0Kb binary in `C:\Windows\System32\powershell.exe
` (found by cmd.exe -> where powershell.exe)
And, most likely, its why powershell in your example above for user did fail too.
Found discussion https://stackoverflow.com/questions/34912830/windows-8-1-cant-start-powershell-from-a-cmd-or-powershell-prompt-this-app-c

**Comment by rcmaehl** [comment]
> @rcmaehl just solved same issue for myself - issue was in incorrect powershell.exe 0Kb binary in `C:\Windows\System32\powershell.exe ` (found by cmd.exe -> where powershell.exe)
> And, most likely, its why powershell in your example above for user did fail too.
> Found discussion https://stackoverflow.com/questions/34912830/windows-8-1-cant-start-powershell-from-a-cmd-or-powershell-prompt-this-app-c
> I believe you can firstly just try to call `powershell.exe` without parameters and if it fails then call it by absolute path `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe `

If this fixes it, I swear

**Comment by rcmaehl** [comment]
We've moved away from powershell completely. So this can be resolved as a result.
