### ISSUE TITLE
testing release 2.3.2 - missing symbols of the result boxes 

### ISSUE THREAD

**Issue by speedy-pc** [rcmaehl/WhyNotWin11#531]
missing symbols of the result boxes - I am using Windows 11 Pro 64 Bit - Bulild 21H1
In the last stable version 2.3.1 everything was ok.  Is it a mistake or is it on purpose? 

![V2-3-2-0](https://user-images.githubusercontent.com/86987678/126892872-95c490dd-d078-4b37-b5e4-59626fc0bc23.JPG)

**Comment by rcmaehl** [comment]
It's intentional.
