### ISSUE TITLE
Direct X12 does not show as compatible

### ISSUE THREAD

**Issue by master3395** [rcmaehl/WhyNotWin11#541]
**All Checks**
- Download and run the latest build https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip
- Attach a picture of your WhyNotWin11 Results
- Attach required information based on the category:

**Architecture, CPU Compatibility, CPU Core Count, and CPU Frequency**
- Please run `taskmgr`, select Performance, then CPU, and attach a screenshot of the output
- Please run `gwmi win32_processor | Format-List -Property MaxClockSpeed,Name,NumberOfCores,NumberOfLogicalProcessors,AddressWidth` in Powershell and attach a screenshot of the output

![image](https://user-images.githubusercontent.com/4199669/127580978-d1f05767-dd10-4ac3-94b1-3c68a041a2f4.png)

![image](https://user-images.githubusercontent.com/4199669/127580923-938e4910-63dd-41b4-b49d-1db77c342e48.png)

**Boot Method**
- Please run `bcdedit` in an *Admin* Powershell and attach a screenshot of the output
- Please run ` $env:firmware_type` in Powershell and attach a screenshot of the output

![image](https://user-images.githubusercontent.com/4199669/127581001-9596f496-6316-4ff6-8160-f8743db319af.png)

**DirectX**
- Please [download and run GPU-Z](https://www.techpowerup.com/download/techpowerup-gpu-z/) and attach a screenshot of the "Graphics Card" tab
- Please run `dxdiag`, select `Save All Information` and upload the file it generates

![image](https://user-images.githubusercontent.com/4199669/127580761-829d998c-4189-423f-905e-f05c11b5bf04.png)

[DxDiag.txt](https://github.com/rcmaehl/WhyNotWin11/files/6904321/DxDiag.txt)

**Disk Partition Type, Storage Available**
- Please run `diskmgmt.msc`, maximize the window, and attach a screenshot of the output

![image](https://user-images.githubusercontent.com/4199669/127581068-b4bc1a8b-ada4-4511-9c4e-241c3f9ae6a6.png)

**RAM Installed**
- Please run `gwmi Win32_PhysicalMemory | Format-List -Property BankLabel,Capacity,PartNumber` in Powershell and attach a screenshot of the output

![image](https://user-images.githubusercontent.com/4199669/127581083-92d9f3a9-527e-497f-8970-c5c5be3483ee.png)

**Secure Boot**
- Please run `reg query HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecureBoot\State` in Powershell and attach a screenshot of the output

![image](https://user-images.githubusercontent.com/4199669/127581102-a79f20bc-a98c-4758-9fa9-0f863c97e7ad.png)

**TPM**
- Please run `windowsdefender://devicesecurity`, Select `Security Processor Details`, and attach a screenshot of the output

![image](https://user-images.githubusercontent.com/4199669/127581240-4ddaa5fd-cccb-4af6-8286-e6c4b8124a99.png)

**Comment by rcmaehl** [comment]
I guess I need to clarify when you need to run the specific commands in the issue template.

For some reason your dxdiag isn't reporting feature or DDI levels:
![image](https://user-images.githubusercontent.com/716581/127582106-24517a3b-5bba-420d-adfc-9a3d10f131fa.png)

![image](https://user-images.githubusercontent.com/716581/127582139-26bdaf77-cb1c-4e4c-8abe-279662a3c8b5.png)

This will be improved in #58. It looks like your device is a laptop and that may have something to do with it.

**Comment by micwoj92** [comment]
I am closing this because it is basically the same issue as #58
