### ISSUE TITLE
Windows Defender detects Update 2.3.2 as Trojan!

### ISSUE THREAD

**Issue by Soumyadeep98O** [rcmaehl/WhyNotWin11#542]
![Screenshot 2021-07-30 183324](https://user-images.githubusercontent.com/30073064/127657249-3d27cc67-1f98-4e3b-8572-2fee6e548849.png)
![Screenshot 2021-07-30 185822](https://user-images.githubusercontent.com/30073064/127659973-4a110958-6029-4404-9f7e-2e1e7424e948.png)

**Comment by micwoj92** [comment]
#49
