### ISSUE TITLE
McAfee WebAdvisor thinks this is a virus

### ISSUE THREAD

**Issue by noneofyourbusiness1415252** [rcmaehl/WhyNotWin11#543]
**Describe the bug**
Apparently, WhyNotWin11 is a virus?? I know it isn't (or at least wasn't), because I installed it before and it worked perfectly, and McAfee didn't block it from installing.

**To Reproduce**
<br>Steps to reproduce the behavior:
1. Make sure that McAfee WebAdvisor is installed
1. Open Microsoft Edge
2. Install WhyNotWin11 2.3.2 from Releases page
3. Skip Defender smartscreen warning by clicking the 3 dots, then click 'keep'.
4. It says 'Couldn't download - virus detected'

**Expected behavior**
It should download and open straight away, as it did before

**Screenshots**
![Screenshot of problem](https://db5pap001files.storage.live.com/y4p5RyZVi0rdA6TvlUeIX4SFckevb7u2q_CX1PGQkoxTaf0O4WWnu3IULNgGocxC9z4Wv_blgjzm_sMgiclA385I02eaGbQHsDNak1xJi0X4JVGbnRWCzFng19adSDsbphLFZZbPu2hwqH_0iED_vriOtFtV7v7TYaKo9fqGFVt1oZcb8sVeBtXpNEwmQfjeQM0qcxdNp22G0_WMrA4jqyzBAwzufNuBRmWKhI2SSY4lCg/2021-07-30%20%281%29.png?psid=1&width=456&height=257)

**Desktop (please complete the following information):**
Windows 10 version 21H1 (Build 19043.1110)

**Additional context**
<br>Add any other context about the problem here.

**Comment by micwoj92** [comment]
#49
