### ISSUE TITLE
Regarding "Removed Checkmark and Cross from Pass/Fail"

### ISSUE THREAD

**Issue by deus-e-x** [rcmaehl/WhyNotWin11#548]
Perhaps this design decision isn't that fortunate for people with certain sight restrictions like color-blindness or color vision deficiencies.

A better approach might be adding an option to toggle the display of the checkmarks/crosses, which defaults to enabled.

**Comment by rcmaehl** [comment]
I'm looking into converting them to Icons in a future release

![image](https://user-images.githubusercontent.com/716581/128199464-77dcc772-1680-4c6e-a6f8-1167280da25f.png)

**Comment by deus-e-x** [comment]
Thank you for your feedback. I think this issue thread has run its course, therefor I'm closing it.
