### ISSUE TITLE
UI Scaling on WIndows 10 causes program interface to clip.

### ISSUE THREAD

**Issue by WolvenSpectre** [rcmaehl/WhyNotWin11#55]
Not a huge issue for me but people using higher scaling than me for higher res monitors are likely going to have issues with the UI being a set size and not adjusting to scaling.  [This is what it looks like at 120%]https://i.imgur.com/3oAViaV.png(url)

**Comment by micwoj92** [comment]
@WolvenSpectre could you check how it works with 150%? I have too small screen and it doesn't fit :(

**Comment by rcmaehl** [comment]
Please try the latest action once it completes

**Comment by WolvenSpectre** [comment]
Still same issue on last version and the 2 new versions you had me download.  Here are the 2 64bit versions side by side. https://i.imgur.com/FJBO1cX.png

**Comment by WolvenSpectre** [comment]
Sorry guys... forgot I had a custom 115% scaling and didn't try testing standard scaling before I said scaling didn't work because I forgot I wasn't on 125 anymore.

It isn't working on Custom scales (Tried 110, 115, 120) but on scalings that are standard but set through the custom feature work fine except for a end line of the left and bottom of the table on the right of the UI (I assume that is as intended).

Also I tested all three versions of the UI and they are all displaying similarly.

**Comment by micwoj92** [comment]
Could you test latest dev build just to be 100% sure that it works?

**Comment by WolvenSpectre** [comment]
Got latest.  Works great at 100, 115, and 150%.
Also I discovered weirdly enough a utility I am using that was having a display issue is now working at 150 and for some reason after my recent Nvidia Driver Update they are recommending I run at 150% default.  Strange... going to have to look into those two.

Thanks for the great utility I have been recommending it across YT comments and my socials so I hope you get more support.
