### ISSUE TITLE
DirectX + WDDM2 detected and then not detected

### ISSUE THREAD

**Issue by Slacknote** [rcmaehl/WhyNotWin11#553]
Bit odd aye? Did not change my hardware.
![v2 3 0 5](https://user-images.githubusercontent.com/88526498/128461243-f326388c-500d-4376-bd94-3c68bb26e82f.png)
![v2 3 1 0](https://user-images.githubusercontent.com/88526498/128461396-04820be8-6935-4354-ad32-2b3eef86bb17.png)
![DxDiag1](https://user-images.githubusercontent.com/88526498/128461419-983a07ea-07ba-4c6d-bdfd-f78f8f793e62.png)
![DxDiag2](https://user-images.githubusercontent.com/88526498/128461424-06eecd39-7f2d-4ce5-a893-be9824be6f71.png)
<img width="290" alt="GPU-Z" src="https://user-images.githubusercontent.com/88526498/128461430-01a51d74-b9b8-49b7-a9a3-a79e668eef3c.png">
[DxDiag.txt](https://github.com/rcmaehl/WhyNotWin11/files/6943249/DxDiag.txt)

**Comment by micwoj92** [comment]
That 2.3.1.0 is unofficial, unsupported and outdated version.

**Comment by Slacknote** [comment]
Can you please look at the rest of my post?

**Comment by micwoj92** [comment]
> Can you please look at the rest of my post?

I did.
Version 2.3.0.5 from **THIS** repo is okay.
Version 2.3.1.0 that was made by **someone else** shows it wrong.

Not only you are using old version, but also you don't understand that issues on this repo are not made for some unofficial fork.

**Comment by micwoj92** [comment]
Resolved, won't fix. Your problem is occurring in different software.
