### ISSUE TITLE
CPU speed misdetected

### ISSUE THREAD

**Issue by Anaerin** [rcmaehl/WhyNotWin11#56]
My CPU is being detected as 800MHz, which is it's minimum frequency with power saving:
![image](https://user-images.githubusercontent.com/989271/123533701-c87d5580-d6d4-11eb-8aff-1fffa592d39b.png)
This might be related to Hyper-V being enabled.

**Comment by rcmaehl** [comment]
Are you running the application in the Hyper-V VM?

**Comment by billysielu** [comment]
Maybe this will help:
`Get-CimInstance Win32_Processor | Select-Object -Expand MaxClockSpeed`

**Comment by rcmaehl** [comment]
> Maybe this will help:
> `Get-CimInstance Win32_Processor | Select-Object -Expand MaxClockSpeed`

Pretty sure I'm already getting this value in Line 22 of `\includes\WMIC.au3`

**Comment by Anaerin** [comment]
I'm not running it in a Hyper-V VM, but because of the way Hyper-V works, the "Host" OS is still a Guest, albeit one with a lot more access.

And for reference:
```
PS C:\WINDOWS\system32> Get-CimInstance Win32_Processor | Select-Object -Expand MaxClockSpeed
801
PS C:\WINDOWS\system32> Get-CimInstance Win32_Processor

DeviceID Name                                     Caption                              MaxClockSpeed SocketDesignation
-------- ----                                     -------                              ------------- -----------------
CPU0     Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz Intel64 Family 6 Model 60 Stepping 3 801           SOCKET 1150


PS C:\WINDOWS\system32>
```

The reason I mentioned Hyper-V is: https://www.hanselman.com/blog/windows-task-manager-shows-wrong-cpu-speed-when-using-hyperv

**Comment by billysielu** [comment]
Hypervisor detection: 
`Get-CimInstance Win32_ComputerSystem | Select-Object -Expand HypervisorPresent`
https://devblogs.microsoft.com/scripting/use-powershell-to-detect-if-hypervisor-is-present/

**Comment by mooms06** [comment]
> 
> 
> Maybe this will help:
> `Get-CimInstance Win32_Processor | Select-Object -Expand MaxClockSpeed`

This incorrectly detect 2101 MHz, my CPU can reach 4.8 GHz

![image](https://user-images.githubusercontent.com/25405517/123628071-fe285880-d812-11eb-8fd1-182ad64e3fb3.png)

![image](https://user-images.githubusercontent.com/25405517/123627940-dfc25d00-d812-11eb-8b67-f37437311b8b.png)

**Comment by billysielu** [comment]
Spent a bit of time looking for a good solution to this and pretty sure there isn't one.
Removing the CPU Frequency check is probably fine, nobody legitimately fails it, all the complaints are either because the printed number is wrong or because of virtualisation. The CPU Compatibility check indirectly covers it anyway.

**Comment by mooms06** [comment]
Maybe
https://www.dell.com/community/Rack-Servers/Wmic-command-to-get-cpu-current-clock-speed-is-same/td-p/6108886

**Comment by rcmaehl** [comment]
> Maybe
> https://www.dell.com/community/Rack-Servers/Wmic-command-to-get-cpu-current-clock-speed-is-same/td-p/6108886

Nope

**Comment by rcmaehl** [comment]
What I'll do is grab the @ <speed> from the CPU string and report that if there's a discrepancy. Although this will only work for Intel CPUs

**Comment by mooms06** [comment]
> 
> 
> What I'll do is grab the @ from the CPU string and report that if there's a discrepancy. Although this will only work for Intel CPUs

And only for non overclocked CPU. Look at mine, it report 2.10 GHZ, it actually runs between 800-4800 MHz.

**Comment by micwoj92** [comment]
In my opinion only stock speeds should be supported, sure, you can oc many cpus to 5ghz but have fun trying to run that.
