### ISSUE TITLE
WNW11 says supported on Disabled Secure Boot rather than a note that it's disabled.

### ISSUE THREAD

**Issue by My1** [rcmaehl/WhyNotWin11#563]
**For an Issue with ANY Check**
- Download and run the latest build 

- Attach a picture of your WhyNotWin11 Results

![Neue Bitmap](https://user-images.githubusercontent.com/6696524/130201206-166d1bf9-31f7-441a-9f7c-ee06c72cc1fd.png)

- Attach required information based on the category:

**For an Issue with Secure Boot**
- Please run `reg query HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecureBoot\State` in Powershell and attach a screenshot of the output

![Unbenannt](https://user-images.githubusercontent.com/6696524/130201572-59f9133b-038e-427b-823c-1ccbb83c8a5c.png)

Secureboot is currently disabled and while WNW11 says supported (which is not wrong) it should inform that it needs to be enabled

msinfo32 also says Secure Start State (or whatever it might be called in english in that line) as "off"

**Comment by micwoj92** [comment]
This was discussed many times already 
https://github.com/rcmaehl/WhyNotWin11/search?q=secureboot&type=issues

Microsoft official documentation still only says "Secure Boot capable" nothing about having it enabled 
https://docs.microsoft.com/en-us/windows/whats-new/windows-11-requirements

**Comment by My1** [comment]
oh okay, but doesnt quite make sense for force support but not enabling it

**Comment by My1** [comment]
by now there's an insider update that mentions secureboot so it can be tested how it runs on systems with just disabled secureboot
