### ISSUE TITLE
Export Results Feature

### ISSUE THREAD

**Issue by AlexanderEDavis** [rcmaehl/WhyNotWin11#564]
A lot of my clients are wanting to use this tool so they can check if they need to replace anything. One of them tells me their's is not compatible but due to their lack of PC knowledge, I cannot view the results without being physically there and they are unable to screenshot (daft I know!)

It would be great if there was a button to export the results, whether that's an image or a text/pdf file. Then the client can email it over 😄

**Comment by micwoj92** [comment]
Export results will be finished when https://github.com/rcmaehl/WhyNotWin11/issues/106 completes, hence I am marking this as duplicate
