### ISSUE TITLE
Display CPU in "CPU Compatibility" box

### ISSUE THREAD

**Issue by Ronsss** [rcmaehl/WhyNotWin11#568]
Nice work. Better than MS!
.
I see you already display the CPU type and graphics type at the bottom of the window.  Good. 
It would be nice if you displayed the CPU in the "CPU Compatibility" output box. 
You could do the same with Video support, put the video card in the DirectX output box.
OR
Put both of them at the top, rather than the bottom of the output list to make them easier to find. 
.
As an additional tweak, you could display CPU's not supported in Red, as an additional visual reminder. 
.
Additional tweak, add a hyperlink to MS's approved list of CPU's so people have direct access to the list.  It's kinda hard to find otherwise unless you know exactly where to look.

**Comment by micwoj92** [comment]
It was moved there because some names get really long
https://github.com/rcmaehl/WhyNotWin11/issues/147
