### ISSUE TITLE
Use Standard "Application Title Bar" layout

### ISSUE THREAD

**Issue by Ronsss** [rcmaehl/WhyNotWin11#570]
**Describe the bug**
Dual monitor setup, laptop 1080p screen and 4K external monitor

App launches on "Main" screen

App is truncated, part of top and bottom of app window is displayed off screen:
![image](https://user-images.githubusercontent.com/33688532/130502474-6320ab72-8f34-46a3-b8cf-c1ec4cf9a92f.png)

I suspect that may be because I have move my Win taskbar to the top of the monitor. Windows doesn't handle that very gracefully. 

**Desktop (please complete the following information):**
Win 10 21H1 Build 19043.1165

**Comment by micwoj92** [comment]
@Ronsss could you give another title to this issue? Application can be moved.

**Comment by Ronsss** [comment]
I'm going to close this issue, it has merged with another issue I raised, which I renamed today to: App does not have standard
