### ISSUE TITLE
App does not have standard 

### ISSUE THREAD

**Issue by Ronsss** [rcmaehl/WhyNotWin11#571]
**Describe the bug**
App does not have the "standard" application window controls.
Normally they display by clicking on the app icon in the upper left corner of the application title bar, or by using <ALT><Spacebar> shortcut, ie

![image](https://user-images.githubusercontent.com/33688532/130503475-41ea6db7-1063-43af-aa82-147c6c2cd394.png)
.
I wanted to use the "Move" command to move the application around on my screen to a more convenient location on screen. 
.
It actually appears that the screen location is hard coded in the application.
.
**Desktop (please complete the following information):**
Win 10 Ver 21H1 Build 19043.1165

**Comment by micwoj92** [comment]
> It actually appears that the screen location is hard coded in the application.

I'm pretty sure you can move it around

**Comment by Ronsss** [comment]
My mistake.
.
I tried again. I found that if I click and drag on the very top of the application window, where the "application title bar" area is, I can drag it. But since it is the same color as body there is no visual indication that the title bar area is distinct from the body, like there is in most applications. The text you have at the top of the application is NOT the title. 
.
I was "tricked" because the text at the top is NOT written in the application title bar area.  My screen capture tool picks up different parts of the application window. This is what it picks up for the application title bar:
![image](https://user-images.githubusercontent.com/33688532/130544527-9729532a-68a6-46c6-a485-01378ba19ec5.png)
. 
Move that "Your Windows 11 ..." text down, completely into the body of the application. 
.
But I still would like to see the standard application menu so that I could activate it using the shortcut
.
You would have to move the version information. Put it in Application title bar. Many other applications do it that way
.
Here is a fast and dirty dummied up version showing a more "traditional" layout with the application dropdown menu displayed. The green 1 is stand in for app icon used to trigger the drop down
.
![image](https://user-images.githubusercontent.com/33688532/130546879-05cb2036-6cac-4531-9c71-722fa9982275.png)
.
Here is an example of another small utility
![image](https://user-images.githubusercontent.com/33688532/130546949-4fa62da8-2ffa-4201-9e9e-ac2831a8aecb.png)

**Comment by micwoj92** [comment]
I am closing this because of this comment
https://github.com/rcmaehl/WhyNotWin11/issues/24#issuecomment-868949468
"I'll add in dragging in a later version. The Windows 10 title bars aren't the best and I'd like to have a slightly different experience than default. Many applications do this, Discord, Chrome, Telegram."

@rcmaehl Reopen if you changed your mind since when you wrote that comment
