### ISSUE TITLE
Veresion 2.3.2 will not download in Firefox latest version (91.0.2 - 64)

### ISSUE THREAD

**Issue by NavyBill** [rcmaehl/WhyNotWin11#572]
**Describe the bug**
<br>Clicking either the 'latest version' or the 2.3.2 links will not produce a download.
**To Reproduce**
<br>Steps to reproduce the behavior:
1. Go to '2.3.2 web page'
2. Click on 'latest version' or '2.3.2' links
3. nothing happens

**Expected behavior**
<br>Expected to down load latest version

**Comment by rcmaehl** [comment]
I'm unable to reproduce. Can you provide the exact page you're using?

**Comment by krystian3w** [comment]
Look like [ISP](# "Internet service provider") lost bits and this break page, now latest open 2.4.0.

https://github.com/rcmaehl/WhyNotWin11/releases/latest

```
Result

https://github.com/rcmaehl/WhyNotWin11/releases/latest
302 Found
https://github.com/rcmaehl/WhyNotWin11/releases/tag/2.4.0
200 OK
```

**Comment by micwoj92** [comment]
Closing, this also isn't really something that we can control anyway.
