### ISSUE TITLE
Have Direct X 12+ WDDM WDDM 2.7 but says not compliant

### ISSUE THREAD

**Issue by DJB2-GitHub** [rcmaehl/WhyNotWin11#574]
Using WhyNotWin11 - My Dell Inspiron 5406 qualifies for all Win11 requirements except graphic card.
Checking PC with DxDiag it says I have  Direct X 12+ WDDM WDDM 2.7  which qualifies.

<img width="590" alt="Win11_fail" src="https://user-images.githubusercontent.com/67865230/130734956-79e9f55e-e425-46a7-b38d-f2c8663c5890.png">

[DxDiag.txt](https://github.com/rcmaehl/WhyNotWin11/files/7044031/DxDiag.txt)

**Comment by micwoj92** [comment]
That 2.3.1.0 is unofficial, unsupported and outdated version.
