### ISSUE TITLE
Windows 11 supports 7th-generation Xeon W-series

### ISSUE THREAD

**Issue by nguyenminh-phuc** [rcmaehl/WhyNotWin11#580]
Microsoft just updated their supported Intel processor list in their [website](https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors).

>There are some modest changes coming with Intel seventh-generation processors. From that generation, you’ll be able to run Windows 11 with a Core X-series or a Xeon W-series CPU. That’s not all though. The Core i7-7820HQ is going to be supported.

<html><body>

Manufacturer | Brand | Model
-- | -- | --
Intel® | Xeon® | W-2102
Intel® | Xeon® | W-2104
Intel® | Xeon® | W-2123
Intel® | Xeon® | W-2125
Intel® | Xeon® | W-2133
Intel® | Xeon® | W-2135
Intel® | Xeon® | W-2145
Intel® | Xeon® | W-2155
Intel® | Xeon® | W-2175
Intel® | Xeon® | W-2195

</body>
</html>

**Comment by micwoj92** [comment]
Added, feel free to open new issue if more are added in future.

**Comment by speedy-pc** [comment]
SupportedProcessorsIntel.txt = 583 Intel CPUs
Microsoft Website = 537 Intel CPUs

Where is the mistake?
Source: https://docs.microsoft.com/de-de/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors

**Comment by micwoj92** [comment]
Mistake is microsoft not being consistent, see my comment on the commit.

**Comment by krystian3w** [comment]
Possible test in new:

https://aka.ms/GetPCHealthCheckInsidersX64

>
> ARM - https://aka.ms/GetPCHealthCheckInsidersX86
>

S Mode (like by downloaded from MS Store) - https://aka.ms/GetPCHealthCheckInsidersMSIX

**Comment by micwoj92** [comment]
> Possible test in new:
> 
> https://aka.ms/GetPCHealthCheckInsidersX64
> 
> > ARM - https://aka.ms/GetPCHealthCheckInsidersX86
> 
> S Mode (like by downloaded from MS Store) - https://aka.ms/GetPCHealthCheckInsidersMSIX

?

**Comment by krystian3w** [comment]
If translated pages lays, maybe updated app have the most updated list.

**Comment by micwoj92** [comment]
Still, microsofts fault. App should use same list as documentation, doesn't matter if it's in German or in English

**Comment by krystian3w** [comment]
Worse if this is pro bono publico, so who shuld be fired (not employeed MS fan or real employee).

**Comment by micwoj92** [comment]
As far as I know most (if not all) pages under docs.microsoft.com are on https://github.com/microsoftdocs organization, so feel free to find right repo and complain there.
