### ISSUE TITLE
no directx12 but directx12 in dxdiag

### ISSUE THREAD

**Issue by aor2021** [rcmaehl/WhyNotWin11#581]
Hi guys so when i was going to check when i can run windows 11 it said no directX 12 was detected

My gpu is a GTX 1650 TI max-q laptop

When i checked at dxdiag i see that i have directx 12

![Screenshot (104)](https://user-images.githubusercontent.com/89691337/131217878-5d85f057-44da-402b-8896-e2cd19a72db9.png)

![Screenshot (106)](https://user-images.githubusercontent.com/89691337/131217901-f8b35d8b-18a8-4925-8a80-a58622666bba.png)

Is this a problem  or its just my gpu???

**Comment by aor2021** [comment]
![Screenshot (109)](https://user-images.githubusercontent.com/89691337/131218140-5caea612-0f53-4483-af91-bc05ce9c4e31.png)

**Comment by aor2021** [comment]
- [ ]

**Comment by micwoj92** [comment]
@aor2021 Any reason for reopening and closing multiple times?

**Comment by rcmaehl** [comment]
Please try the latest build, the build in your screenshot is out of date.

**Comment by aor2021** [comment]
Ok its fix
![Screenshot (133)](https://user-images.githubusercontent.com/89691337/134763331-401da2f9-87d1-429e-b105-16dc010ba6eb.png)

**Comment by aor2021** [comment]
Its Fix.
