### ISSUE TITLE
Incorrect labeled 7th generation Intel processors

### ISSUE THREAD

**Issue by Nocir** [rcmaehl/WhyNotWin11#583]
In the "SupportedProcessorsIntel.txt" the Intel Core i9-7900X, i9-7920X, i9-7940X, i9-7960X and i9-7980XE are incorrectly labeled as i7 processors. So for example my i9-7980XE is now reported as unsupported.

Since WhyNotWin11 2.4.0.0

**Comment by micwoj92** [comment]
Fixed, blame  @dongle-the-gadget lol
