### ISSUE TITLE
Windows Defender finds Trojan:Win32/Spursint.Q!cl in the executable

### ISSUE THREAD

**Issue by Wandrer** [rcmaehl/WhyNotWin11#584]
Windows Defender finds "Trojan:Win32/Spursint.Q!cl" in the executable and in the zip file. The option to keep the file or report the falseflagging does not work. Windows Defender immediately deletes the file.

Malware-Clientversion:  4.18.2107.4
Module-Version: 1.1.18400.5
Antivirus-Version: 1.347.611.0
Antispyware-Version: 1.347.611.0
Windows-Version: Windows 10 Version 21H2 Build 19044.1165

**Comment by micwoj92** [comment]
Duplicate #49
