### ISSUE TITLE
Xeon W-2123 is on the W11 support list

### ISSUE THREAD

**Issue by ferryperry** [rcmaehl/WhyNotWin11#585]
Hi, 

This processor is on the MS list: https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors

This might be a slight (yet a bit ;-) disturbing) oversight?

Hint: Virtualisation Support is turned off on the device, might that help with the issue?

Kind regards, Ferry
![whynotW11 Xeon W-2123](https://user-images.githubusercontent.com/51911616/131241030-cd008e37-9085-4ad9-9681-3b0b9448bc4c.JPG)

**Comment by micwoj92** [comment]
It should be supported, could you download this file https://github.com/rcmaehl/WhyNotWin11/blob/main/includes/SupportedProcessorsIntel.txt and then place it in `%localappdata%\WhyNotWin11`? When asking about overwriting you should confirm.

**Comment by micwoj92** [comment]
Solution: Clear all files inside `%localappdata%\WhyNotWin11` and then download latest dev version
https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip
