### ISSUE TITLE
Now i9-9920X and i9-9940X can run win 11.

### ISSUE THREAD

**Issue by luigicolo** [rcmaehl/WhyNotWin11#587]
Hi! please check:
https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors
Now i9-9920X and i9-9940X can run win 11.
In whynotwin11.exe v. 2.4.0.0 is still not included.
Thanks a lot for your attention.
Bye.
Luigi

**Comment by micwoj92** [comment]
Fixed, thanks for reporting.
