### ISSUE TITLE
Processors list not up-to-date

### ISSUE THREAD

**Issue by trattnerE** [rcmaehl/WhyNotWin11#589]
Dear Sirs,

Thanks for having made available this utility for all of us :)

Still, it appears that the list of compatible processors for v. 2.4.0.0 is not really up-to-date ..

Case in point, while the i7-9800x processor IS listed by MS at < https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors >, it is missing from your list ...

You may wish to check.

Repeated thanks,

Sincerely,

Eric T.

**Comment by micwoj92** [comment]
Fixed, thank you for reporting.

**Comment by trattnerE** [comment]
Thanks, but …

 

*	I renamed the list of processors created by your app in %localappdata% and tried to run v. 2.4.0.0 again
*	Odd as it may be, it recreated that list with the first line suggesting that it belonged to v. 2.3.1.0 … (which, obviously, didn’t include my CPU)

 

Any ideas?

 

Thanks,

 

Eric

**Comment by micwoj92** [comment]
Did you try latest dev build?
https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

**Comment by trattnerE** [comment]
Actually, assuming a change might have been incorporated in the distro, I did check from the v. 2.4.0.0 executable downloaded earlier today whether an update might be available, and the result came up negative.

 

I now tried the version you pointed me to, and here are the results:

 

*	My CPU finally shows to be Win11 compatible (all items green 😊 )
*	The version of the executable remained unchanged (2.4.0.0), which explains why no update was allegedly found … You may wish to make it 2.4.0.1 so that the semi-auto-update would work.

 

Thanks again for the very prompt actions & replies,

 

All the best,

 

Eric

**Comment by micwoj92** [comment]
> Actually, assuming a change might have been incorporated in the distro, I did check from the v. 2.4.0.0 executable downloaded earlier today whether an update might be available, and the result came up negative. 

All executables/files on the 2.4.0.0 will stay the same. When new stable version releases it will included all changes.


The version of the executable remained unchanged (2.4.0.0), which explains why no update was allegedly found … You may wish to make it 2.4.0.1 so that the semi-auto-update would work. 

This mechanism works using GitHub release tags and it will not work until Robert creates new release. What I linked you to is dev/testing version.
