### ISSUE TITLE
Windows 7 not supported to check?

### ISSUE THREAD

**Issue by capsload2** [rcmaehl/WhyNotWin11#591]
Hey, is there really no chance to check if my Windows 7 System is eligable for Windows 11?

**Comment by micwoj92** [comment]
You should be able to check, but checks may be not accurate https://github.com/rcmaehl/WhyNotWin11/issues/127

**Comment by TheQuickFox** [comment]
> 
> 
> You should be able to check, but checks may be not accurate #127

Not at this time. Windows 7 is hardcoded not supported with an error message.
![notsupported](https://user-images.githubusercontent.com/30596092/131730285-bdb744b5-4cd5-4eb9-a348-2b07e6ebc330.jpg)

**Comment by micwoj92** [comment]
Oh that's new, I thought that you could just x and have main window pop up. @rcmaehl what to do with this?
