### ISSUE TITLE
Update list of supported CPUs

### ISSUE THREAD

**Issue by matt-pan** [rcmaehl/WhyNotWin11#593]
The list of supported Intel CPUs seems to not be up to date after the last update from Microsoft (08/27/21) https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors
E.g. Intel® | Core™ | i7-8809G is missing

**Comment by micwoj92** [comment]
Yes, I know. Microsoft's list isn't 100% the same as ours (some names differ, because they are detected under slightly different names for example) so I just admit of doing half assed approach by adding each cpu when it's reported.
