### ISSUE TITLE
WhyNotWin11 thinking my CPU with two cores isn't compatible

### ISSUE THREAD

**Issue by justkamiii** [rcmaehl/WhyNotWin11#599]
**For an Issue with ANY Check**
- Download and run the latest build https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip
- Attach a picture of your WhyNotWin11 Results
![image](https://user-images.githubusercontent.com/84019509/132097420-c3357d84-9748-42e5-81a2-80a3a8b1176e.png)
- Attach required information based on the category:

**For an Issue with Architecture, CPU Compatibility, CPU Core Count, and CPU Frequency**
- Please run `taskmgr`, select Performance, then CPU, and attach a screenshot of the output
![image](https://user-images.githubusercontent.com/84019509/132097516-5266deef-1eb6-4513-880a-befe9b48657a.png)
- Please run `gwmi win32_processor | Format-List -Property MaxClockSpeed,Name,NumberOfCores,NumberOfLogicalProcessors,AddressWidth` in Powershell and attach a screenshot of the output
![image](https://user-images.githubusercontent.com/84019509/132097536-c8efbafc-81e0-49c5-8851-42f5c35f8ab4.png)

**Comment by micwoj92** [comment]
Do you see your CPU somewhere on this list? https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors

**Comment by justkamiii** [comment]
Wait what? What did I do wrong?

**Comment by justkamiii** [comment]
ah

**Comment by justkamiii** [comment]
> Do you see your CPU somewhere on this list? https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors

No, but I can see it here https://www.microsoft.com/en-us/windows/windows-11-specifications

**Comment by justkamiii** [comment]
![image](https://user-images.githubusercontent.com/84019509/132097764-d91217c1-63dd-4185-94d6-0b6a248139c6.png)

**Comment by micwoj92** [comment]
If it's not on supported processor list then it will be labelled as Not Supported.

**Comment by justkamiii** [comment]
Oh, I see. In that case, yes, my issue was stupid
