### ISSUE TITLE
Issues flagged by https://www.virustotal.com/gui/

### ISSUE THREAD

**Issue by red-ray** [rcmaehl/WhyNotWin11#60]
Thank you for the utility, but can you try and address https://www.virustotal.com/gui/ issues please?

![WhyNotWin11](https://user-images.githubusercontent.com/25452387/123537963-39029180-d72a-11eb-9cd8-619165f3483d.png)

**Comment by rcmaehl** [comment]
Issue has been reported to both vendors as False Positive.
