### ISSUE TITLE
Unsupported Message while starting silently via CLI

### ISSUE THREAD

**Issue by ChrisNbg** [rcmaehl/WhyNotWin11#602]
**Describe the bug**
<br>
Hi, I wanted to make a script to check some computer about there compatibility. 
Following Command did I use:
WhyNotWin11.exe /silent /export csv win11.txt

I assumed that this line would start the tool without any prompt and creates the CSV-File in the same folder.
But there is always a message when starting the command line

Title: not supportet
Text: You are running the newest Version!

Perhaps the message appears because I am starting the script on a Windows 11 machine. This is only the machine where I create the script...

**To Reproduce**
<br>Steps to reproduce the behavior:
Run the command 
WhyNotWin11.exe /silent /export csv win11.txt
under Windows 11

**Expected behavior**
<br>
there should be not that output wenn running via CLI with Silent-Switch.
Perhaps there should be a more clear message what is not supportet. Perhaps: Not supportet operating system or something else.

**Screenshots**
<br>
![whynotwin11](https://user-images.githubusercontent.com/8652401/132506870-1d7cdaa7-74f5-4f16-a8f6-91d05d0d5bba.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 / 22000.168 Insider-Beta
 - Version 2.4.1.0

**Comment by micwoj92** [comment]
Duplicate #595
