### ISSUE TITLE
Processor definition

### ISSUE THREAD

**Issue by LunarResearch** [rcmaehl/WhyNotWin11#607]
Good day!
Your utility determines the processor name from the registry branch HKEY_LOCAL_MACHINE \ HARDWARE \ DESCRIPTION \ System \ CentralProcessor by string value ProcessorNameString.
This is wrong because when change this value, your utility incorrectly detects compatibility with Windows 11.
Take the name of the processor from EAX (__cpuid).

**Comment by rcmaehl** [comment]
While the number of people modifying this string should be extremely low, I'll look into adding this for additional checks

**Comment by rcmaehl** [comment]
Actually, after review it appears I'm not currently using that, only WMIC still. 

![image](https://user-images.githubusercontent.com/716581/135187184-024f1434-6eb0-4169-8f2d-fb3a5f955ff2.png)

The only CentralProcessor registry key I'm using is for CPU Speed

![image](https://user-images.githubusercontent.com/716581/135187245-c95c1261-6882-402f-8f55-711156fc9a7b.png)

**Comment by LunarResearch** [comment]
Ok, my processor is i5-7400
<a href="https://pixs.ru/image/GWOca1"><img src="https://pixs.ru/images/2021/09/29/Test_1.jpg" alt="Test_1.jpg" border="0" /></a>
Next i am change reg value for i5-8400
<a href="https://pixs.ru/image/GWOw2A"><img src="https://pixs.ru/images/2021/09/29/Test_2.jpg" alt="Test_2.jpg" border="0" /></a>
and then again testing your tools
<a href="https://pixs.ru/image/GWO61O"><img src="https://pixs.ru/images/2021/09/29/Test_3.jpg" alt="Test_3.jpg" border="0" /></a>
Cool )) now i can install Windows 11 ?!
Of course NOT!
Because PCHealthCheckApp get processor name from __cpuid
<a href="https://pixs.ru/image/GWOjmR"><img src="https://pixs.ru/images/2021/09/29/Test_4.jpg" alt="Test_4.jpg" border="0" /></a>

**Comment by LunarResearch** [comment]
int CPUInfo[4]{ -1 };

    __cpuid(CPUInfo, 0x80000000);

    unsigned ID = CPUInfo[0];

    char CPUName[MAX_PATH]{};

    for (unsigned i = 0x80000000; i <= ID; ++i)
    {
        __cpuid(CPUInfo, i);

        if (i == 0x80000002)
            memcpy(CPUName, CPUInfo, sizeof(CPUInfo));

        else if (i == 0x80000003)
            memcpy(CPUName + 16, CPUInfo, sizeof(CPUInfo));

        else if (i == 0x80000004)
            memcpy(CPUName + 32, CPUInfo, sizeof(CPUInfo));
    }

    std::wcout << CPUName << std::endl;

**Comment by rcmaehl** [comment]
Please try the latest test build:

https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

**Comment by rcmaehl** [comment]
Won't be fixing this. I'm not aware of anyone that actively changes this for any legitimate reason and the implementation of EAX (__cpuid) for AutoIt I've found is too much a performance hit on slower systems. This can be reopened if there's some legitimate reason the processor may have been renamed.
