### ISSUE TITLE
Win 7 / Force / not supported

### ISSUE THREAD

**Issue by mrkapqa** [rcmaehl/WhyNotWin11#608]
**Describe the bug**
<br>A clear and concise description of what the bug is.

**To Reproduce**
<br>Steps to reproduce the behavior:
 running 

WhyNotWin11.exe /force inside cmd-box

**Expected behavior**
<br>A clear and concise description of what you expected to happen.

would except to run on Windows 7 64bit.

instead getting

box with ]

Win_7 not supported

**Comment by rcmaehl** [comment]
Please try the latest build:

https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

**Comment by mrkapqa** [comment]
thanks, this improved, but now getting error

line 1120> Error ¬ The requested action with this object has failed
![autoit](https://user-images.githubusercontent.com/12947465/135119005-a4c4a5b6-ccd8-4755-8261-87b283ccfaec.png)
.

**Comment by rcmaehl** [comment]
Unfortunately, won't fix. I believe this goes for most tools including the PC Health Check app.
