### ISSUE TITLE
Export txt/csv is not correct 

### ISSUE THREAD

**Issue by DerKiLLa** [rcmaehl/WhyNotWin11#609]
**Trying to use the application with /export txt/csv** 
<br>The Output of DirectX + WDDM2 & Secure Boot is not good

When i use txt-Output, i get the following:
DirectX + WDDM2		-1	-1
Secure Boot	2	0	0

When i use csv, DirectX + WDDM2 is empty and Secure Boot is 2

But everything is green, when i just start the app. 

**Expected behavior**
<br>DirectX + WDDM2 seems not to work properly with /silent and /output and Secure Boot should say True, like the other outputs.

**Comment by rcmaehl** [comment]
Please try the latest build if you haven't already, some command line improvements were made

https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip

**Comment by DerKiLLa** [comment]
Nice, it works with DirectX + WDDM2.

Maybe u can change also the txt output from Secure Boot 
from Secure Boot	2	0	0
to Secure Boot	True	2	0

And in csv True instead of 2?

**Comment by rcmaehl** [comment]
> Nice, it works with DirectX + WDDM2.
> 
> Maybe u can change also the txt output from Secure Boot from Secure Boot 2 0 0 to Secure Boot True 2 0
> 
> And in csv True instead of 2?

Should be fixed now. Same link as before for the latest CI build

**Comment by DerKiLLa** [comment]
Awesome! Thank you very much! 

But in this release there is a bug with "cpu compatibility". It shows "Unable to Check List" but with the current stable release its okay.
