### ISSUE TITLE
WhyNotWin11_x86.exe v2.2.2 - Windows Defender - Trojan:Win32/Wacatac.B!ml 

### ISSUE THREAD

**Issue by grimson73** [rcmaehl/WhyNotWin11#61]
Trojan:Win32/Wacatac.B!ml
Flagged by Windows Defender
https://github.com/rcmaehl/WhyNotWin11/releases/download/2.2.2/WhyNotWin11_x86.exe

**Comment by famo000** [comment]
Autoit softwares are frenquently flaggge as virus.
Take source, compile it, and test again.

**Comment by rcmaehl** [comment]
Duplicate of #49
