### ISSUE TITLE
TPM Version: possible to query even if it is not enabled?

### ISSUE THREAD

**Issue by rubyFeedback** [rcmaehl/WhyNotWin11#612]
Hey folks,

My laptop which I purchased in 2018 or so used to run linux, so I disabled TPM.

Right now it runs Win10. TPM is disabled. I can reboot, change the BIOS and
then resume, but I wondered ... would it be possible to just query the TPM 
status as-is? I don't know if this is possible, but if it were that would be
super-convenient. I am a bit scared of trying TPM and then the computer may
no longer boot, which is why something like this would be useful. (If this is
too much time to write, but still possible otherwise, perhaps you guys could
write one simple reference model? Just to show whether it is possible to do;
other folks could then perhaps use that to add support for more such queries
if it is possible.)

Feel free to close this if it is too much work or not appropriate! I understand lack
of time. Otherwise WhyNotWin11 is really super-helpful. Is there a web 
variant of it too? :D

**Comment by rcmaehl** [comment]
Disabling in BIOS prevents it from being initialized as far as I'm aware and is not detectable which is why #415 exists. Enabling TPM should not brick your Windows unless you enable bitlocker afterwards.

**Comment by rcmaehl** [comment]
I wasn't able to find a solution for this. Windows never loads a driver for the TPM if it's not enabled in BIOS and other functions also fail.
