### ISSUE TITLE
Windows Health and WNW11 says O.K but settings says nope

### ISSUE THREAD

**Issue by GreenMan36** [rcmaehl/WhyNotWin11#615]
**For an Issue with ANY Check**
![image](https://user-images.githubusercontent.com/5887406/136026830-b24d98da-2342-424b-86fa-55f4baeb382e.png)

Is there any known thing that isn't correctly being tested?

In case you need some more info its likely to be in here:
[System information OUTPUT.txt](https://github.com/rcmaehl/WhyNotWin11/files/7286020/System.information.OUTPUT.txt)

**Comment by micwoj92** [comment]
WNW11 gives same result as Health Check application, I don't think this is issue on our part.
