### ISSUE TITLE
%errorlevel% is always 0

### ISSUE THREAD

**Issue by KlausGuth** [rcmaehl/WhyNotWin11#618]
**Describe the bug**
I get always 0 as Exitcode even if the pc is not compatible.

**To Reproduce**
WhyNotWin11.exe /s & echo %errorlevel%

WhyNotWin11.exe /f /s 
echo %errorlevel%

**Expected behavior**
If not compatible Exitcode > 0

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 2.4.2.0

**Comment by rcmaehl** [comment]
I'll look into this but in the meantime I would recommend using the suggested powershell method

**Comment by rcmaehl** [comment]
Try

WhyNotWin11.exe /s
If ERRORLEVEL 1 then echo errored
