### ISSUE TITLE
64GB OK on one system but not OK on another + blank boot method should not be OK

### ISSUE THREAD

**Issue by red-ray** [rcmaehl/WhyNotWin11#62]
I happened to have one of my test systems booted and it said 64GB was not OK, so I booted another one which was happy with 64GB !

Neither system supports UEFI boot so boot method can't be OK.

![RXN](https://user-images.githubusercontent.com/25452387/123539794-5851ec80-d733-11eb-86a0-c724c7309720.png)
![REX](https://user-images.githubusercontent.com/25452387/123539795-5be57380-d733-11eb-93fd-0f3149ac869e.png)

**Comment by htcfreek** [comment]
This is the available free space we check.

**Comment by red-ray** [comment]
It's a lack of rounding for the check and rounding what is displayed, I expect both should be rounded

	If DriveSpaceTotal("C:\")/1024 >= 64 Then
		GUICtrlSetData($hCheck[9][0], "OK")
		GUICtrlSetBkColor($hCheck[9][0], 0x4CC355)
		GUICtrlSetData($hCheck[9][2], Round(DriveSpaceTotal("C:\")/1024, 0) & " GB on C:\")

**Comment by red-ray** [comment]
bfc9057 does not seem to address the DriveSpaceTotal() rounfing issue

**Comment by rcmaehl** [comment]
> [bfc9057](https://github.com/rcmaehl/WhyNotWin11/commit/bfc90576ac31cd76351c5411c158f835db562595) does not seem to address the DriveSpaceTotal() rounding issue

Was 3e2661dcc00fa352e2120853e89b2c26f3e54eb4
