### ISSUE TITLE
Variable error - Line 383, seems to be CPU check

### ISSUE THREAD

**Issue by ICTman1076** [rcmaehl/WhyNotWin11#63]
Here is the issue:

![Line 383 - Variable used without being declared](https://www.hybrid-analysis.com/file-inline/60d85180633a19608f75380a/screenshot/screen_3.png)

This issue only happened on [analysis at hybrid-analysis.com](https://www.hybrid-analysis.com/sample/790a7a3f19625c3dd9e598e38e1920a5862d2490851e8332d48f8d6a98ae72cc/60d85180633a19608f75380a), but I figured I'd report it anyway just in case. As a result, I can't say for sure what specs or quirks this machine will have, but it was a 64-bit analysis.

**Comment by rcmaehl** [comment]
Unfortunately, compiled line numbers don't match up 1:1 with compiled source. A line number that small is likely in one of the includes files and not fixable. If it pops up outside hardened VM use I'll get it fixed but until then this is WON'T FIX

**Comment by deiruch** [comment]
This happens on my Surface Pro (5th gen) as well (i5-7300U)

**Comment by rcmaehl** [comment]
Found the issue, hopefully should be patched shortly

**Comment by rcmaehl** [comment]
> Unfortunately, compiled line numbers don't match up 1:1 with compiled source. A line number that small is likely in one of the includes files and not fixable. If it pops up outside hardened VM use I'll get it fixed but until then this is WON'T FIX

I am dumb and the stripped version does have a 1:1 compiled source line #

**Comment by billysielu** [comment]
$STR_NOCOUNT maybe?
include StringConstants.au3
https://www.autoitscript.com/autoit3/docs/functions/StringSplit.htm

**Comment by deiruch** [comment]
Latest CI build no longer crashes with this error!
