### ISSUE TITLE
Yellow exclamation mark at CPU compatibility

### ISSUE THREAD

**Issue by MaestroDeLaContradiccion** [rcmaehl/WhyNotWin11#64]
I get a yellow exclamation mark at the requierement "CPU compatibility". My CPU is an Intel Core i7-6700HQ CPU @ 2.60 GHz. What's the matter? Will I be able to run Windows 11?

**Comment by shyim** [comment]
Your CPU is not on the official list https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors

**Comment by MaestroDeLaContradiccion** [comment]
OK, thanks for your answer!

**Comment by billysielu** [comment]
@devs
Whilst this may seem like "not a bug", it probably should be improved as this is a common question. 
Maybe use something other than an exclamation mark?
Marybe put links to the cpu lists in the app?

**Comment by Okwizi** [comment]
@MaestroDeLaContradiccion, Adding to what @shyim referenced,  your CPU (as at the moment) won't support Windows 11 according to the Microsoft document (which happened to be updated as soon as the official checker was also updated.) Before the update on the document however, it stated that PCs with older CPUs could upgrade but it wasn't "recommended". Your CPU came out at 2015 which is considered old but doesn't not necessarily mean you can't run Windows 11. Most CPUs that pass the check are >7th Generation.

**Comment by rcmaehl** [comment]
@billysielu You are correct, I've changed it to a yellow ?

**Comment by billysielu** [comment]
I think that's an improvement, but still getting "What does the ? mean" questions.
