### ISSUE TITLE
[wine support?] Does it work via wine?

### ISSUE THREAD

**Issue by rubyFeedback** [rcmaehl/WhyNotWin11#642]
Hello,

Background: my laptop used to have win10 but it has gotten so slow so I installed fedora
on it. Now the speed problem is gone. But I need a windowns machine for testing stuff.
So I decided I should check my second desktop computer for this.

But, I don't know if it works on win11 (I could probably use win10 for now but I don't
want to lag behind once win11 is distributed; but the request here is also applicable
for win10 of course).

Does WhyNotWin11 work via wine on linux? If so, could the readme state so? If not
could the readme also state so? This would be helpful to know whether we can test
it on linux before installing windows - hopefully I managed to explain the use case.
THanks for reading!

**Comment by rcmaehl** [comment]
Unfortunately recent changes prevent it from working on WINE. You could try an early 2.x build as they used less accurate but more available functions but it's not guaranteed to be 100% correct even then

**Comment by micwoj92** [comment]
@rubyFeedback last version to run on wine is  2.3.0.5 and it was tested on wine 6.22.
