### ISSUE TITLE
2.4.3.0 is not working

### ISSUE THREAD

**Issue by dmitriy1980** [rcmaehl/WhyNotWin11#645]
Just downloaded version 2.4.3.0. When opening WhyNotWin11.exe I get the following error message:

Line 1932  (File "C:\Users\[redacted]\WhyNotWin11.exe"):

Error: Subscript used on non-accessible variable.

I'm on Windows 10 with the latest patches

**Comment by htcfreek** [comment]
Same for me:
![image](https://user-images.githubusercontent.com/61519853/145861700-a22f8039-0b8b-4be0-9476-3bf8b75324c9.png)

**Comment by rcmaehl** [comment]
Yep. Have a fix. Just doing UX improvement

**Comment by htcfreek** [comment]
The fixed release has no exe files attached.

**Comment by micwoj92** [comment]
They are built by CI, it takes ~ 5 minutes.
