### ISSUE TITLE
2.4.3.1 no .exe released

### ISSUE THREAD

**Issue by strawbeard** [rcmaehl/WhyNotWin11#646]
Only source code released; cannot run w/o AutoIt, need WhyNotWin11.exe.

**Comment by htcfreek** [comment]
Is there now. Build on CI needs up to 5 min.

**Comment by micwoj92** [comment]
https://github.com/rcmaehl/WhyNotWin11/actions/runs/1574187529

**Comment by strawbeard** [comment]
Correct! I didn't know that release page is built progressively.
