### ISSUE TITLE
UX content invisible

### ISSUE THREAD

**Issue by htcfreek** [rcmaehl/WhyNotWin11#647]
**Describe the bug**
The app is starting in dark mode but some of the text is invisible.

**To Reproduce**
<br>Steps to reproduce the behavior:
1. Open WhyNotWin11.

**Expected behavior**
All text is visible.

**Screenshots**
The result rectangles have no symbols.
![image](https://user-images.githubusercontent.com/61519853/145864281-90901b6b-05d4-46d7-944e-a4999803d9e1.png)

The settings menu has no text on some places.
![image](https://user-images.githubusercontent.com/61519853/145864250-b4bc4f79-a540-4fde-a417-8ca5f376e8ca.png)

**Desktop (please complete the following information):**
 - OS: Win10 21H2
 - Version 2.4.1.3

**Additional context**
_no_

**Comment by rcmaehl** [comment]
There is no text there 😅

![image](https://user-images.githubusercontent.com/716581/145864743-4eb6a2dc-5002-4119-8a6a-facfaa9dae61.png)

**Comment by micwoj92** [comment]
oh..

**Comment by htcfreek** [comment]
But the headers of the group boxes are black on black background

**Comment by rcmaehl** [comment]
> But the headers of the group boxes are black on black background

AH... FRICK

**Comment by WilloIzCitron** [comment]
ugh bugs everywhere
