### ISSUE TITLE
Microsoft Windows Defender flags this as a virus!

### ISSUE THREAD

**Issue by SheetLightning** [rcmaehl/WhyNotWin11#648]
Windows defender flags the .exe version of this app as unknown program and prevents it being downloaded or run. The portable version found here is actually flagged as a virus!

https://amirhosseinhpv.github.io/WhyNotWin11/

There is a hidden option to Run Anyway if one clicks the More but I am not sure whether it is safe to run so have avoided trying to run it.

**Comment by micwoj92** [comment]
Duplicate https://github.com/rcmaehl/WhyNotWin11/issues/49

**Comment by micwoj92** [comment]
No wait, the website you linked does not even belong to this program.
