### ISSUE TITLE
Shriking window size

### ISSUE THREAD

**Issue by jonhp** [rcmaehl/WhyNotWin11#649]
**Describe the bug**
<br>The application window size on version 2.4.3.1 is almost too small to read on my laptop from version 2.4.2.1 which was fine.
Lenovo T14, win10, 1920x1080 with a scale factor of 175%.

**Comment by rcmaehl** [comment]
Please give it about ~5 minutes then download and run the latest dev build: https://nightly.link/rcmaehl/WhyNotWin11/workflows/wnw11/main/WNW11.zip
