### ISSUE TITLE
7f458f7

### ISSUE THREAD

**Issue by ali9069** [rcmaehl/WhyNotWin11#650]
**Describe the bug**
<br>A clear and concise description of what the bug is.

**To Reproduce**
<br>Steps to reproduce the behavior:

**Expected behavior**
<br>A clear and concise description of what you expected to happen.

**Screenshots**
<br>If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - Version [e.g. 2.3.0.0]

**Additional context**
<br>Add any other context about the problem here.

**Comment by ali9069** [comment]
7f458f7

**Comment by micwoj92** [comment]
@rcmaehl could you block him so he doesnt spam anymore? Thanks.

**Comment by rcmaehl** [comment]
> @rcmaehl could you block him so he doesnt spam anymore? Thanks.

Done. They can contact me via the discord if they have any issues.
