### ISSUE TITLE
support for 12th gen Intel core processor

### ISSUE THREAD

**Issue by islercn** [rcmaehl/WhyNotWin11#651]
WhyNotWin11 shows incorrect cpu compatibility for 12th gen Intel core processor (12700KF) under win11

![11](https://user-images.githubusercontent.com/7038562/148045181-1f66a6c7-7de2-4b9b-be1f-b8e7926df3f9.png)

**Comment by rcmaehl** [comment]
Added in f6500e90cb4a69e62b3e39b96342456950575d99

1, Download `SupportedProcessors<name>.txt`
2. Place File in `%localappdata%\WhyNotWin11`
![image](https://user-images.githubusercontent.com/716581/124361960-24c60500-dc00-11eb-9e12-d8a47159e87a.png)
3. Override Existing Files when Prompted
![image](https://user-images.githubusercontent.com/716581/123526705-ae794e00-d6a7-11eb-8ee0-22cb1d18ad9f.png)

https://raw.githubusercontent.com/rcmaehl/WhyNotWin11/2.4.3.1/includes/SupportedProcessorsIntel.txt
