### ISSUE TITLE
Add support for Intel® Celeron® Processor N5095

### ISSUE THREAD

**Issue by ivellioscolin** [rcmaehl/WhyNotWin11#654]
![Capture](https://user-images.githubusercontent.com/6303111/150673525-cedb05cd-fd68-4d1e-bb3b-8437899b0659.PNG)
![CPU](https://user-images.githubusercontent.com/6303111/150673551-cf5d0693-a023-4313-9086-a5717f29a11a.png)
![CPU1](https://user-images.githubusercontent.com/6303111/150673556-600c9dd9-04ca-4bf1-a8d8-88d7bf639bdb.png)

**Comment by micwoj92** [comment]
It's not on the list...
 https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors

**Comment by WilloIzCitron** [comment]
hmm cpu supports and unlisted, hmm interesting

**Comment by ivellioscolin** [comment]
I guess MSFT will soon update the list...
N5095 is basically the desktop variant of N5105, and there is AIO system shipped with N5095.
Let's wait for more time.

**Comment by WilloIzCitron** [comment]
oh this processor is Jasper Lake and released in Q1 2021 its supported

**Comment by rcmaehl** [comment]
I'm sure it'll be added the next time Microsoft gets around to it. I'll add it for now since the Official App shows it's supported.

**Comment by rcmaehl** [comment]
Added in fe0c8c98bc7591f1122d548d9f9fcc4b81ec4bad

1, Download `SupportedProcessors<name>.txt`
2. Place File in `%localappdata%\WhyNotWin11`
![image](https://user-images.githubusercontent.com/716581/124361960-24c60500-dc00-11eb-9e12-d8a47159e87a.png)
3. Override Existing Files when Prompted
![image](https://user-images.githubusercontent.com/716581/123526705-ae794e00-d6a7-11eb-8ee0-22cb1d18ad9f.png)

https://raw.githubusercontent.com/rcmaehl/WhyNotWin11/main/includes/SupportedProcessorsIntel.txt

**Comment by ivellioscolin** [comment]
Confirmed fixed with latest testing release.

**Comment by xCSxXenon** [comment]
I'm using version 2.5.0.5 in a repair shop and the N5095 is showing as unsupported. I see manually downloading a file and putting it into an AppData folder is the workaround, but the standalone portable executable should show this processor as supported. The file linked in this thread shows that processor being added at line 47 but the matching file in the main source code is missing this.
