### ISSUE TITLE
How to cancel display this popup ?

### ISSUE THREAD

**Issue by swordnine** [rcmaehl/WhyNotWin11#666]
![why](https://user-images.githubusercontent.com/61126745/158998472-e9a8c802-f827-434e-ac77-af1e7f266b63.png)

**Comment by rcmaehl** [comment]
If you don't want it to pop-up by default you can run

`reg add "HKLM\Software\Policies\Robert Maehl Software\WhyNotWin11" /v NoPopUp /t REG_DWORD /d 1` from an admin command prompt

**Comment by swordnine** [comment]
> If you don't want it to pop-up by default you can run
> 
> `reg add "HKLM\Software\Policies\Robert Maehl Software\WhyNotWin11" /v NoPopUp /t REG_DWORD /d 1` from an admin command prompt

Thanks.
