### ISSUE TITLE
12700k is not compatible？

### ISSUE THREAD

**Issue by sqdz0728** [rcmaehl/WhyNotWin11#669]
I want to show others how to use this software. But I see it shows that cpu is incompatible.

**Comment by WilloIzCitron** [comment]
pls post screenshot

**Comment by sqdz0728** [comment]
> pls post screenshot
![QQ截图20220326103139](https://user-images.githubusercontent.com/24269087/160222187-7ebd436f-cd68-442d-9045-7f3da4a26f1b.png)

**Comment by rcmaehl** [comment]
Pretty sure this is due to "12th Gen" prefixed. I'll see if I can fix it later today

**Comment by sqdz0728** [comment]
> Pretty sure this is due to "12th Gen" prefixed. I'll see if I can fix it later today

Thanks!

**Comment by epman100** [comment]
> Pretty sure this is due to "12th Gen" prefixed. I'll see if I can fix it later today

are you sure this is truly fixed for 12th gen intel cpus?
check out this recent Askwoody.com article:
[https://www.askwoody.com/2023/microsoft-you-have-made-this-confusing/](https://www.askwoody.com/2023/microsoft-you-have-made-this-confusing/)

the screenshot there says "12th generation i7-12700 is not supported"

**Comment by rcmaehl** [comment]
> > Pretty sure this is due to "12th Gen" prefixed. I'll see if I can fix it later today
> 
> are you sure this is truly fixed for 12th gen intel cpus? check out this recent Askwoody.com article: https://www.askwoody.com/2023/microsoft-you-have-made-this-confusing/
> 
> the screenshot there says "12th generation i7-12700 is not supported"

I was working on CPU family detection to improve this but I'll release an update to be safe.
