### ISSUE TITLE
Serveral malware hits by AV software

### ISSUE THREAD

**Issue by madzodiac** [rcmaehl/WhyNotWin11#67]
Palo Alto Cortex XDR, Sophos and others recognize https://github.com/rcmaehl/WhyNotWin11/releases/download/2.2.0/WhyNotWin11.exe as malware
Serveral Yara rules match as well https://www.virustotal.com/gui/file/c3dbde1e5791e17eced706846eac4abfbc671b3c3e5ce6c1c1cb3097204ee173/detection

**Comment by rcmaehl** [comment]
See #49, already emailed vendors. Instructions for emailing them as well can be found in the issue
