### ISSUE TITLE
Some AMD processors are marked as compatible incorrectly

### ISSUE THREAD

**Issue by eduardoaddad** [rcmaehl/WhyNotWin11#676]
Last version is with some wrong AMD processors

AMD Ryzen 7 2700U is marked as compatible in the program but by Microsoft is not compatible

![image](https://user-images.githubusercontent.com/16819380/168945625-c3eb5487-0698-4d2b-94c6-58cc3afb8d66.png)

**Comment by micwoj92** [comment]
@rcmaehl
https://github.com/rcmaehl/WhyNotWin11/commit/f6500e90cb4a69e62b3e39b96342456950575d99
This change broke it, I think better system is needed. Maybe a blacklist?

**Comment by rcmaehl** [comment]
Should be fixed with #681 improvements
