### ISSUE TITLE
Windows 7 support

### ISSUE THREAD

**Issue by ToddAndMargo** [rcmaehl/WhyNotWin11#678]
Windows 7 Pro SP1
WhyNotWin1-2.4.3.21.exe

Error popup:  "Windows 7 is not supported!"

Dude!  Windows 7 IS THE MOST common OS I upgrade to Windows 10/11

Please support it!

**Comment by rcmaehl** [comment]
You can force WhyNotWin11 to run unsupported OSes using `whynotwin11.exe /force`. You will need to install powershell among other things to get accurate results and I can not provide support for any issues that occur.

**Comment by ToddAndMargo** [comment]
Thank you!  

It ate my qemu-kvm Windows 7's lunch, which was what I am after.

Just out of curiosity, do yo check for the Intel C204 chipset, which won't run on either Windows 10 or 11?

**Comment by rcmaehl** [comment]
> Thank you!
> 
> It ate my qemu-kvm Windows 7's lunch, which was what I am after.
> 
> Just out of curiosity, do you check for the Intel C204 chipset, which won't run on either Windows 10 or 11?

C204 is 2nd gen intel right? It'd be detected based on CPU compatibility.

**Comment by ToddAndMargo** [comment]
The C204 run Intel's  Xeon E3-1200 v5 / v6 processors.  So indeed, the CPU check would catch it.

I was thinking Windows 10, where you have to go through the entire install to get to the very end to find out you are not supported.

An aside,  I adore your graphic design.  Everything you need to know and easy to see.  That took a lot of work.
