### ISSUE TITLE
Add optional check Why Not Windows 11 22H2?

### ISSUE THREAD

**Issue by krystian3w** [rcmaehl/WhyNotWin11#681]
**Describe the feature**

`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\TargetVersionUpgradeExperienceIndicators\NI22H2`

https://winaero.com/how-to-find-if-your-pc-is-compatible-with-windows-11-22h2-in-registry/

**To Reproduce**

May need some KB on Windows 11 if not created by WU itself.

**Expected behavior**

Implement or reject feature

**Screenshots**

![image](https://user-images.githubusercontent.com/35370833/176320929-97e1bb32-0ecc-44d4-9095-8c099dba4392.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 21H1
 - Version 2.4.3.2

**Additional context**

Help users who don't like use regedit and like install asap 22H2 form WU.

**Comment by rcmaehl** [comment]
Added
