### ISSUE TITLE
Conflicting check values should be better displayed.

### ISSUE THREAD

**Issue by ErikBrown2** [rcmaehl/WhyNotWin11#688]
**Describe the bug**
<br>A clear and concise description of what the bug is.
Version 2.5.0.0 reports that secureboot is disabled/not detected while msinfo32 reports that it is enabled.
**To Reproduce**
<br>Steps to reproduce the behavior:
1. Run WhyNotWin11 and see it reporting that secureboot is disabled/not detected. Then run msinfo32 and see that secureboot state is reported as being on.

**Expected behavior**
<br>A clear and concise description of what you expected to happen.
That WhyNotWin11 reports the secureboot status correctly
**Screenshots**
<br>If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/32511867/176982124-fdb5a1e5-5b2f-4fa0-aae1-239672939920.png)

Msinfo32 shows the following:

![image](https://user-images.githubusercontent.com/32511867/176982164-ab187bdb-93d4-4f94-92ca-90a84be34867.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]Win10 
 - Version [e.g. 2.3.0.0]
21H2 build 19044.1806
**Additional context**
<br>Add any other context about the problem here.

**Comment by rcmaehl** [comment]
> **Describe the bug** A clear and concise description of what the bug is. Version 2.5.0.0 reports that secureboot is disabled/not detected while msinfo32 reports that it is enabled. **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Run WhyNotWin11 and see it reporting that secureboot is disabled/not detected. Then run msinfo32 and see that secureboot state is reported as being on.
> 
> **Expected behavior** A clear and concise description of what you expected to happen. That WhyNotWin11 reports the secureboot status correctly **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> ![image](https://user-images.githubusercontent.com/32511867/176982124-fdb5a1e5-5b2f-4fa0-aae1-239672939920.png)
> 
> Msinfo32 shows the following:
> 
> ![image](https://user-images.githubusercontent.com/32511867/176982164-ab187bdb-93d4-4f94-92ca-90a84be34867.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]Win10
> * Version [e.g. 2.3.0.0]
>   21H2 build 19044.1806
>   **Additional context**
>   Add any other context about the problem here.

Please check `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\TargetVersionUpgradeExperienceIndicators\NI22H2` value `RedReason` and let me know what is listed.

**Comment by rcmaehl** [comment]
Ah, you were in the discord earlier. Yep, in progress
