### ISSUE TITLE
i7 1260p not detected

### ISSUE THREAD

**Issue by BlueHairMinerBoy** [rcmaehl/WhyNotWin11#694]
New Dell XPS 9320, with a 12th gen i7 and it's not getting picked up as supported.

![1260p](https://user-images.githubusercontent.com/76572698/186114025-009005ef-8b34-454b-900c-3cd6195510fb.png)
![CPU](https://user-images.githubusercontent.com/76572698/186114034-c42d6b8a-f601-4857-b86a-32aa95cd9c26.png)

 ```
MaxClockSpeed             : 2100


Name                      : 12th Gen Intel(R) Core(TM) i7-1260P
NumberOfCores             : 12
NumberOfLogicalProcessors : 16
AddressWidth              : 64
```

**Comment by micwoj92** [comment]
@BlueHairMinerBoy Could you try 2.5.0.3?

**Comment by BlueHairMinerBoy** [comment]
Still showing as unsupported, also on some other 12th gen machines we've got

**Comment by v-olin** [comment]
Wouldn't the obvious answer be that this model is missing from the [list of supported CPUs](https://github.com/rcmaehl/WhyNotWin11/blob/main/includes/SupportedProcessorsIntel.txt)? There are only 6 supported 12th gen processors both according to this file but also confirmed by Microsoft [here](https://docs.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors). Could you try to add it manually in your cloned repo and try it out?

**Comment by BlueHairMinerBoy** [comment]
Good point, although the official Microsoft tools show that the PC can run 11, it shipped with it on and the keyboard has a Windows 11 style superkey instead of the 10 style. I guess keeping an up to date list of *every* 11 capable CPU is quite a challenge

**Comment by BlueHairMinerBoy** [comment]
Update to this - I use this tool at work to decide wether a PC can run Windows 11 or not, we get a lot of new PCs in now that aren't on the list so don't show up as supported.

I ran Strings.exe on the appraiserres.dll from the Windows 11 ISO and found the following strings:

```
[LT_OEMIncProductName]
Surface_Studio_2
Precision_5520
[DT_ALL_REF_OEMIncProductName]
I:ProductName=LT_OEMIncProductName
I:ProcessorName=Intel(R)_Core(TM)_i7-7820HQ_CPU_@_2.90GHz
[DT_ALL_REF_CpuFmsArmV81AtomicNotSupported]
M:Architecture=12
I:ARMv81ProcessorSupport=FALSE
[DT_ANY_REF_CpuFmsBlockingArm64]
T:DT_ALL_REF_CpuFmsArmV81AtomicNotSupported=TRUE
[DT_ALL_REF_CpuFmsBlockingIntel]
I:CpuVendor=GenuineIntel
I:CpuFamily>=6
I:CpuModel<=95
I:CpuModel!=85
[DT_ALL_REF_CpuFmsBlockingIntelKL]
I:CpuVendor=GenuineIntel
I:CpuFamily=6
I:CpuModel=142
I:CpuStepping=9
I:PlatformId!=0x00000010
[DT_ALL_REF_CpuFmsBlockingIntelKL2]
I:CpuVendor=GenuineIntel
I:CpuFamily=6
I:CpuModel=158
I:CpuStepping=9
I:PlatformId!=0x00000008
T:DT_ALL_REF_OEMIncProductName!=TRUE
[DT_ALL_REF_CpuFmsBlockingAmd]
I:CpuVendor=AuthenticAMD
I:CpuFamily<=22
[DT_ALL_REF_CpuFmsBlockingAmdRR]
I:CpuVendor=AuthenticAMD
I:CpuFamily=23
I:CpuModel=17
[DT_ALL_REF_CpuFmsBlockingAmdSR]
I:CpuVendor=AuthenticAMD
I:CpuFamily=23
I:CpuModel=1
```

This shows the Family, Model and Stepping that Microsoft use to determine if the PC can run 11 or not - these can be found in the registry: `HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\PROCESSOR_IDENTIFIER` or WMI: `gwmi win32_processor | select Caption`

I've put this PowerShell script together, it gets the job done but I'm no means a programmer of any sort. I've tested this at work and it appears to work for our purposes, it seems like a much more solid way of determining the CPU compatibility.

https://gist.github.com/BlueHairMinerBoy/bc7e6acac356f59647cd849cffe0d79f

**Comment by rcmaehl** [comment]
> Update to this - I use this tool at work to decide wether a PC can run Windows 11 or not, we get a lot of new PCs in now that aren't on the list so don't show up as supported.
> 
> I ran Strings.exe on the appraiserres.dll from the Windows 11 ISO and found the following strings:
> 
> ```
> [LT_OEMIncProductName]
> Surface_Studio_2
> Precision_5520
> [DT_ALL_REF_OEMIncProductName]
> I:ProductName=LT_OEMIncProductName
> I:ProcessorName=Intel(R)_Core(TM)_i7-7820HQ_CPU_@_2.90GHz
> [DT_ALL_REF_CpuFmsArmV81AtomicNotSupported]
> M:Architecture=12
> I:ARMv81ProcessorSupport=FALSE
> [DT_ANY_REF_CpuFmsBlockingArm64]
> T:DT_ALL_REF_CpuFmsArmV81AtomicNotSupported=TRUE
> [DT_ALL_REF_CpuFmsBlockingIntel]
> I:CpuVendor=GenuineIntel
> I:CpuFamily>=6
> I:CpuModel<=95
> I:CpuModel!=85
> [DT_ALL_REF_CpuFmsBlockingIntelKL]
> I:CpuVendor=GenuineIntel
> I:CpuFamily=6
> I:CpuModel=142
> I:CpuStepping=9
> I:PlatformId!=0x00000010
> [DT_ALL_REF_CpuFmsBlockingIntelKL2]
> I:CpuVendor=GenuineIntel
> I:CpuFamily=6
> I:CpuModel=158
> I:CpuStepping=9
> I:PlatformId!=0x00000008
> T:DT_ALL_REF_OEMIncProductName!=TRUE
> [DT_ALL_REF_CpuFmsBlockingAmd]
> I:CpuVendor=AuthenticAMD
> I:CpuFamily<=22
> [DT_ALL_REF_CpuFmsBlockingAmdRR]
> I:CpuVendor=AuthenticAMD
> I:CpuFamily=23
> I:CpuModel=17
> [DT_ALL_REF_CpuFmsBlockingAmdSR]
> I:CpuVendor=AuthenticAMD
> I:CpuFamily=23
> I:CpuModel=1
> ```
> 
> This shows the Family, Model and Stepping that Microsoft use to determine if the PC can run 11 or not - these can be found in the registry: `HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\PROCESSOR_IDENTIFIER` or WMI: `gwmi win32_processor | select Caption`
> 
> I've put this PowerShell script together, it gets the job done but I'm no means a programmer of any sort. I've tested this at work and it appears to work for our purposes, it seems like a much more solid way of determining the CPU compatibility.
> 
> https://gist.github.com/BlueHairMinerBoy/bc7e6acac356f59647cd849cffe0d79f

Hi @BlueHairMinerBoy. Mind if I convert your PS script and use it in the next version?

**Comment by BlueHairMinerBoy** [comment]
Go for it.

**Comment by rcmaehl** [comment]
Please try the latest test build

**Comment by BlueHairMinerBoy** [comment]
Still getting "CPU Not Supported" on an i7 12700H which is 12th gen.
