### ISSUE TITLE
Remove seperate indicators that have been added in 2.5.0.1

### ISSUE THREAD

**Issue by rollodroid** [rcmaehl/WhyNotWin11#696]
I installed Windows 10 on a new PC and want to check if everything is good for Windows 11, because it's not shown yet in Windows Update. Now I'm shown yellow and green results like here

https://user-images.githubusercontent.com/716581/177788481-63eeff8c-179a-492a-b5d8-2b0c865a4ce3.png

So what is that telling me? It's confusing and nothing else. I don't know if I will be able to update to Windows 11Please remove this "feature" and maybe add again when it is improved. The tool is unusable in the current version.

**Comment by rcmaehl** [comment]
Changed in 2.5.0.2
