### ISSUE TITLE
Error on Launch

### ISSUE THREAD

**Issue by Lounderr** [rcmaehl/WhyNotWin11#697]
**Error on Launch**<br>
After launching either the x64 or x86 version of the program, I receive an error:
```
Line 2210 (File "C\Users\User\Desktop\WhyNotWin11.exe");

Error: Array variable has incorrect number of subscripts or subscript dimension range exceeded.
```

**To Reproduce**
<br>Steps to reproduce the behavior:
1. Download ZIP/x64/x86 version of the program
2. Open the program
3. Wait until the loading bar finishes

**Expected behavior**
<br>I expect the program to launch normally.

**Screenshot**
https://prnt.sc/MdSxj0ye-pQy

**Desktop:**
 - OS: Windows 10 Pro 64-bit, 
    - Version: `21H2`, 
    - OS build: `19044.1889`, 
    - Experience: `Windows Feature Experience Pack 120.2212.4180.0`

Program Version 2.5.0.2

My system fits the system requirements.

**Comment by rcmaehl** [comment]
WHOOPS
