### ISSUE TITLE
Update _GetDiskInfoFromWmi.au3 to v1.4.2

### ISSUE THREAD

**Issue by htcfreek** [rcmaehl/WhyNotWin11#698]
The new release v1.4.2 of _GetDiskInfoFromWmi.au3 contains the official fix for the build errors in v1.4.1!
It is included in AutoIT-Script v1.3.2: https://github.com/htcfreek/AutoIT-Scripts/releases/tag/v1.3.2

@rcmaehl I created this issue to inform you about the new release.

**Comment by micwoj92** [comment]
There were no code changes so I just updates it, thanks for the heads up.
