### ISSUE TITLE
Minor typo in "Supported" message

### ISSUE THREAD

**Issue by Cpt-Dingus** [rcmaehl/WhyNotWin11#701]
**Describe the bug**
<br> The Supported message has a small typo - "may you are not" is not legible.

**To Reproduce**
<br>Steps to reproduce the behavior:
Have a Win11 supported pc, run the program
The dialogue popup will appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/100243410/191310120-32defc97-421e-4f7a-8ccd-10826ea8d65b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2; Build 19044.1889

**Comment by rcmaehl** [comment]
*Whoops*
