### ISSUE TITLE
Why these 3 lines in 0000.lang have blank space before "="?

### ISSUE THREAD

**Issue by PriitUring** [rcmaehl/WhyNotWin11#706]
Seems to be inconsistent to have these spaces before "=" only in these 3 lines:

https://github.com/rcmaehl/WhyNotWin11/blob/a3c91becaa3b9bc5621011677562c15c6eed4008/Langs/0000.lang#L83-L85

If spaces were a typo, then would be good if all lang files with these 3 lines would get unnecessary spaces removed in single pull or commit, because it's a small change.

**Comment by PriitUring** [comment]
Another thing that seems incorrect, inconsistent or misleading in translation template file is usage of "&&" in line 91, while other lines use the word "and" not "&" or this "&&": https://github.com/rcmaehl/WhyNotWin11/blob/a3c91becaa3b9bc5621011677562c15c6eed4008/Langs/0000.lang#L91

**Comment by rcmaehl** [comment]
I'll update all the language files in a bit.
