### ISSUE TITLE
line 254 has a "then" that should not be there (i think)

### ISSUE THREAD

**Issue by michaeldchristopherETS** [rcmaehl/WhyNotWin11#71]
I got an error. I saw that line was the only one with THEN. I removed it and everything ran fine.

**Comment by rcmaehl** [comment]
Thank you. I've been a bit busy with #66

**Comment by michaeldchristopherETS** [comment]
I appreciate your work.

Michael Christopher

Director of Software Engineering

ETS-Lindgren | 1301 Arrow Point Drive| Cedar Park, TX, 78613

Tel: + (512) 531-6441 | Cell: + (937) 829-4650

***@***.*** | ets‑lindgren.com

Connect with us on social media


CONFIDENTIALITY AND PRIVACY NOTICE: You are receiving this email because you requested product or service information from ETS-Lindgren, or you have opted in to receiving ongoing updates emails from ETS-Lindgren on their product and service offerings. View our Privacy Policy and Privacy Notices outlining the guidelines used for protecting your personal information. The information in this communication may be confidential and is intended only for the use of the recipient(s) named above. You are hereby notified that any dissemination, distribution, or copying of this communication, or any of its contents, to any other party, is strictly prohibited. If you have received this communication in error, please return it to the sender immediately and delete the original message and any copy of it from your computer system. If you have any questions concerning this message, please contact the sender.

On Jun 27, 2021 9:09 AM, "Robert C. Maehl" ***@***.***> wrote:

Thank you. I've been a bit busy with #66<https://github.com/rcmaehl/WhyNotWin11/issues/66>

**Comment by krystian3w** [comment]
Hey I see your telephones...

**Comment by micwoj92** [comment]
> Hey I see your telephones...

Iphone?

**Comment by krystian3w** [comment]
> Iphone?

Nope - numbers. 

@michaeldchristopherETS - no better edit before deletion an remove history of edits?

**Comment by rcmaehl** [comment]
They've been deleted. I'm locking the issue as well.
