### ISSUE TITLE
Update the supported processors

### ISSUE THREAD

**Issue by hensephil** [rcmaehl/WhyNotWin11#713]
Can you please Update the supported processors for Windows 11 version 22H2.

**Comment by arjanvlek** [comment]
There are no differences with the currently included lists (article date 10/17/2022). 

You can copy the list for both versions (21H2 and 22H2) and you'll see there is no difference (yet).

**Comment by rcmaehl** [comment]
> Can you please Update the supported processors for Windows 11 version 22H2.

Working on it!

**Comment by vonDubenshire** [comment]
>> Can you please Update the supported processors for Windows 11 version 22H2.

>Working on it!

The processor I have is listed as compatible on the app **WhyNotWin11** (latest).  However, my processor is **NOT COMPATIBLE** according to Windows and Microsoft -- at least anymore.

I just learned I have the older variation of the AMD Ryzen 5 1600, the "AE" model that was quietly replaced with a more efficient model in 2019.

- [In December 2019 AMD silently launched a new variant, dubbed Ryzen 5 1600 "AF" (based on the changed SKU). It's based on the newer and improved Zen+ architecture and user testings suggest a slightly higher boost clock (3600Mhz compared to 3300MHz for original "AE") under multi-core load compared to the fresh-man 1600.](https://en.wikichip.org/wiki/amd/ryzen_5/1600)'
- [First-Gen AMD Ryzen CPUs are Appearing with 12nm Zen+ Architecture - Dec 21, 2019 02:02 PM EST](https://wccftech.com/first-gen-amd-ryzen-cpus-are-appearing-with-12nm-zen-architecture/)

**Comment by rcmaehl** [comment]
> The processor I have is listed as compatible on the app **WhyNotWin11** (latest). However, my processor is **NOT COMPATIBLE** according to Windows and Microsoft -- at least anymore.

Are you sure?

https://github.com/rcmaehl/WhyNotWin11/blob/5706678b2663686a7171372cac120e8c33eff593/includes/_Checks.au3#L49

Is setup to only return Compatible if the AF ("Stepping 2") is detected. Can you verify yours doesn't have stepping 2 listed when running `wmic cpu get version` in command prompt?
