### ISSUE TITLE
Update supported processor lists (article date: 2023/05/25)

### ISSUE THREAD

**Issue by arjanvlek** [rcmaehl/WhyNotWin11#722]
The supported processor lists have been updated today. They now include 13th generation Core processors, Ryzen 7xxx series and Microsoft SQ3.

I think it's time for an update of WNW11 with these new processor lists.

Sources:

Intel:

https://learn.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-22h2-supported-intel-processors

AMD:

https://learn.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-22h2-supported-amd-processors

Qualcomm:

https://learn.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-22h2-supported-qualcomm-processors

**Comment by rcmaehl** [comment]
Please try the latest dev build
