### ISSUE TITLE
Missing Company Name in WhyNotWin11.exe Digital Certificate Causes Issue with Software Updater

### ISSUE THREAD

**Issue by ljmacri** [rcmaehl/WhyNotWin11#736]
I would like to request that a **Company** name be added to the file attributes and/or digital certificate of the WhyNotWin11.exe executable.

I am currently using WhyNotWin11 Portable v2.5.0.5 on a 64-bit Win 10 Pro v22H2 machine that I have unzipped on a removable USB stick at E:\Portable\WhyNotWin11 2_5_0_5. The file attributes and/or digital certificate for WhyNotWin11.exe is missing a value for the **Company** field, as shown in this Sysinternals [Sigcheck](https://learn.microsoft.com/en-us/sysinternals/downloads/sigcheck) output:

```
Sigcheck v2.90 - File version and signature viewer
Copyright (C) 2004-2022 Mark Russinovich
Sysinternals - www.sysinternals.com

C:\Users\ljmac\Downloads\Test\WhyNotWin11.exe:
        Verified:       Unsigned
        Link date:      8:51 PM 31-May-2023
        Publisher:      n/a
        Company:        n/a
        Description:    Detection Script to help identify why your PC isn't Windows 11 Release Ready. Now Supporting Update Checks!
        Product:        WhyNotWin11
        Prod version:   2.5.0.5
        File version:   2.5.0.5
        MachineType:    64-bit
        Binary Version: 2.5.0.5
        Original Name:  n/a
        Internal Name:  n/a
        Copyright:      Robert Maehl, using LGPL 3 License
        Comments:       https://www.whynotwin11.org
        Entropy:        5.841
```
As a result the [UCheck](https://www.adlice.com/ucheck/) v5.x software updater I use to check for available updates for my ~ 80 installed and portable applications is **unable to find the latest available version for WhyNotWin11** (i.e., a UCheck script filters out WhyNotWin11 from the scan results as "uninteresting") because this software updater requires a Company name to confirm a match for the program executable. _NOTE: Only one other app I use, [BleachBit Portable](https://www.bleachbit.org/download/windows) v4.6.0, has the same problem because of a missing value for "Company"_.

I have reported this issue to Tigzy, the developer of UCheck (see my UCheck bug report at https://github.com/AdliceSoftware/UCheck/issues/28), but Tigzy has closed that bug report and stated that it is the responsibility of the developer of WhyNotWin11 to add the missing Company name to the digital certificate of the WhyNotWin11.exe.

![UCheck v5_2_2 WhyNotWin11 v2_5_0_5 Part A Latest Version Missing 14 Jan 2023](https://github.com/rcmaehl/WhyNotWin11/assets/145856101/0502494a-6528-4d7e-b881-bffa6660b270)

![UCheck v5_2_2 WhyNotWin11 v2_5_0_5 Part B Company Name Missing 14 Jan 2023](https://github.com/rcmaehl/WhyNotWin11/assets/145856101/74a093a9-7396-4566-b71f-3521943de382)

**Comment by rcmaehl** [comment]
Yeah, I can do that. Give me a bit to get home

**Comment by rcmaehl** [comment]
It's been added to test builds. I'll probably release a new stable build by end of the month or so

**Comment by ljmacri** [comment]
Hi @rcmaehl 

**Problem solved**.

The [UCheck](https://www.adlice.com/ucheck/) v5.2.2.0 software updater utility is now detecting my WhyNotWin11 Portable v2.6.0.0 app as a "Community" program (i.e., where the latest available version is determined from telemetry collected from the wider UCheck community) and correctly identifies v2.6.0.0 as the latest available version since you added a value for COMPANY to the file attributes / digital signature to the WhyNotWin11 executables.

![UCheck v5_2_2 WhyNotWin11 v2_6_0_0 Part C Company Added Now Community 18 Jan 2023](https://github.com/rcmaehl/WhyNotWin11/assets/145856101/334571a9-7eaf-487b-9b65-3973f037aae0)

Kudos for fixing this so quickly.  You can close this bug report now.
