### ISSUE TITLE
Windows Security detects trojan

### ISSUE THREAD

**Issue by vivadavid** [rcmaehl/WhyNotWin11#740]
**Describe the bug**

Windows Security detects a trojan on the file WhyNotWin11.zip: Trojan:Win32/ScarletFlash.A. To be more precise, the trojan is detected in the file WhyNotWin11_x86.exe contained in the ZIP.

I've waited for a few days, as false positives are eventually sorted out, but I still get the warning.

![screenshot](https://github.com/rcmaehl/WhyNotWin11/assets/9334287/86350f45-9556-4205-bfb5-e90f2370357f)

**Desktop:**
 - OS: Windows 11.
 - Version: 23H2.

**Comment by ExtremePro11299** [comment]
I have the same problem, but only with the x86 version.
![image](https://github.com/rcmaehl/WhyNotWin11/assets/134209046/7632813e-77fe-4a0d-9ab8-2bbe66cde2bc)

**Comment by WilloIzCitron** [comment]
Hi! anyone was scared about it? please read this issue precisely, it can be help you from this!
https://github.com/rcmaehl/WhyNotWin11/issues/49

**Comment by ExtremePro11299** [comment]
Windows security does not detect it anymore. According to [VirusTotal](https://www.virustotal.com/gui/file/dc18416a0445fb3a046d834636426d41dfee76cfc0b6be291d14fd3f6e66fea6), some still detect it.

**Comment by vivadavid** [comment]
Thanks for the information.
