### ISSUE TITLE
GUI issues / improvemnts

### ISSUE THREAD

**Issue by bovirus** [rcmaehl/WhyNotWin11#747]
@rcmaehl 

**Describe the bug**
<br>A clear and concise description of what the bug is.
Pelase check screenshot
**To Reproduce**
<br>Steps to reproduce the behavior:

**Expected behavior**
<br>A clear and concise description of what you expected to happen.

**Screenshots**
<br>If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - Version [e.g. 2.3.0.0]

**Additional context**
<br>Add any other context about the problem here.

![image](https://github.com/rcmaehl/WhyNotWin11/assets/1262554/04ec80cd-1362-475a-8327-f05a28d4d063)
"Myprojects" not translated.
pelase add to language file

![image](https://github.com/rcmaehl/WhyNotWin11/assets/1262554/ce910573-ee25-4ddb-965f-466415eaa912)
"CPU" is not right there:
About HD pelase post before unit (C:) and after GB size

For other info on bottom is not clear what are refer to (Computer name/BIOS info/Graphic board).
My proposal is this (see text in red that clarify the inf (Computer name/BIOS info/CPU/Graphic board)
![image](https://github.com/rcmaehl/WhyNotWin11/assets/1262554/cec94d73-6c17-4d27-bda3-24734f9f00ed)

Windows 11 not read
In this window you used "Not supprted" strings as caption.I sugest to ad d aspecfic strings "Windows 11 not supported" for this caption
![image](https://github.com/rcmaehl/WhyNotWin11/assets/1262554/672a8b49-0606-428d-a99f-ab4d3ab34f7a)

Note about strings for not english language.
ùIn not english the striongs could be male/female/singular/plural.
Then suie same string for more conetxt can create problem with not english language,.

If you can please avoid create strings using substring.
Use specfic strings (ex. "Supprted" "Notsupported", etc) instead one string for each situation
Use specfic string for specific context. Ex

CPU compatible
CPU not compatible
Secure Boot supported
Secure Boot not suooported
TPM v. xx not supported
TPM v. xx supported

**Comment by rcmaehl** [comment]
I've implemented some of these, but the rest won't be as a redesign is coming.
