### ISSUE TITLE
Please add support for new supported Intel CPU's

### ISSUE THREAD

**Issue by shamu35** [rcmaehl/WhyNotWin11#748]
**Describe the bug**
<br>We have some Lenovo Notebooks which have a "Intel(R) Core(TM) Ultra 7 155H" CPU.
This CPU is currently not detected as compatible by the stable nor the testing release.

Can you add these Ultra 5, Ultra 7 and Ultra 9 Intel CPU's which are also mentioned on the official MS webseite?
https://learn.microsoft.com/en-us/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors

Many thanks
shamu
![ultra7 155H](https://github.com/rcmaehl/WhyNotWin11/assets/67783471/291500e5-5360-4f4a-9658-6fb3581c9b33)

**Comment by rcmaehl** [comment]
Holy shit.

Intel finally abandoned Family 6

https://www.phoronix.com/news/Intel-CPU-Family-6-Ending

I'll get this fixed

**Comment by rcmaehl** [comment]
Actually, it looks like you're running WhyNotWin11 on Windows 11. This will assume you're checking for future update compatibility. I'll get this clarified

**Comment by shamu35** [comment]
> Actually, it looks like you're running WhyNotWin11 on Windows 11.
Yes this is true, we have already installed Windows 11 on these devices.
But anyway, the CPU "Intel(R) Core(TM) Ultra 7 155H" should be added to the list of the supported CPU's in WhyNotWin11.

**Comment by mpibpc-mroose** [comment]
Seems that 14th generation of Intel CPUs is missing, too?

![image](https://github.com/rcmaehl/WhyNotWin11/assets/8191021/b64e15fd-f763-4771-9ea6-36478363ccc7)

[M$ Compatibilty list](https://learn.microsoft.com/de-de/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors)

**Comment by rcmaehl** [comment]
Should be actually fixed as of e7b3887

Intel CPUs don't return a "Version" like AMD does in WMIC...
