### ISSUE TITLE
security.txt : current date above Expires

### ISSUE THREAD

**Issue by lhpitn** [rcmaehl/WhyNotWin11#749]
**Describe the bug**
<br>hi, thanks for the grate tool, only sad that so much antivirus software dislikes 32-bit autoit executrices... 

while browsing a bit through the source files i found that security.txt ; i am not completely sure what this is about but it looks like we are above that date specified there under Expires...

**To Reproduce**
<br>Steps to reproduce the behavior:
1. Go to https://github.com/rcmaehl/WhyNotWin11/blob/main/security.txt
2. compare date with current date

keep up the good work!

**Comment by rcmaehl** [comment]
Completed with 37fe2b9 and ff31b0f
