### ISSUE TITLE
Host Name is Blank

### ISSUE THREAD

**Issue by 3gfvgFWESAs44545** [rcmaehl/WhyNotWin11#755]
**Describe the bug**
<br> When running silently and using the switches to produce a CSV the hostname field is blank. The other columns are filled in correctly.

**To Reproduce**
<br>Run the program using the following switches /s /export CSV LOG.CSV

**Expected behavior**
<br>The PC name is shown in the CSV

**Screenshots**
<br>
![image](https://github.com/rcmaehl/WhyNotWin11/assets/166209825/9d26b92d-e6a2-465f-819a-f27d0888592f)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version Enterprise 64bit 22H2

**Additional context**
<br>I'm hoping to run this on all computers on site to produce a big CSV with the status for all computers, but obviously I will need the hostname for this to be useful. Many Thanks!

**Comment by rcmaehl** [comment]
Give me just a bit

**Comment by rcmaehl** [comment]
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/166209825/346899336-9d26b92d-e6a2-465f-819a-f27d0888592f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MjY3OTQsIm5iZiI6MTcyMDUyNjQ5NCwicGF0aCI6Ii8xNjYyMDk4MjUvMzQ2ODk5MzM2LTlkMjZiOTJkLWU2YTItNDY1Zi04MTlhLWYyN2QwODg4NTkyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMjAxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lN2Q4YTI2OWU1ODM2YjQyNWMzYmI4NDMzMzU4N2MwNTE4MWU3OTIwMTdmNzQ0MTFhYTliYzk2Y2UzNGVjMTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fej8m9YVJLT7Ra9o5qfSljF3nK1v9IhyJRX5nRU3BZA)

Looks like maybe the hostname ended up in the TPM field?

**Comment by 3gfvgFWESAs44545** [comment]
> > **Screenshots** ![image](https://private-user-images.githubusercontent.com/166209825/346899336-9d26b92d-e6a2-465f-819a-f27d0888592f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MjY3OTQsIm5iZiI6MTcyMDUyNjQ5NCwicGF0aCI6Ii8xNjYyMDk4MjUvMzQ2ODk5MzM2LTlkMjZiOTJkLWU2YTItNDY1Zi04MTlhLWYyN2QwODg4NTkyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMjAxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lN2Q4YTI2OWU1ODM2YjQyNWMzYmI4NDMzMzU4N2MwNTE4MWU3OTIwMTdmNzQ0MTFhYTliYzk2Y2UzNGVjMTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fej8m9YVJLT7Ra9o5qfSljF3nK1v9IhyJRX5nRU3BZA)
> 
> Looks like maybe the hostname ended up in the TPM field?

Yes you are right, so perhaps the csv creation code is slightly wrong somewhere?

**Comment by rcmaehl** [comment]
Should be fixed in this build:

https://github.com/rcmaehl/WhyNotWin11/actions/runs/9857483366/artifacts/1682062538


I'll have a full 2.6.1.1 version out by end of day with a couple extra changes as well.

**Comment by 3gfvgFWESAs44545** [comment]
> Should be fixed in this build:
> 
> https://github.com/rcmaehl/WhyNotWin11/actions/runs/9857483366/artifacts/1682062538
> 
> I'll have a full 2.6.1.1 version out by end of day with a couple extra changes as well.

That version seems to be working correctly now. many thanks for the rapid fix! :)

**Comment by PicoMitchell** [comment]
It looks like the download for https://github.com/rcmaehl/WhyNotWin11/actions/runs/9857483366/artifacts/1682062538 has expired. Is it possible to get a new temporary build, or is there an ETA on the 2.6.1.1 final release?

**Comment by micwoj92** [comment]
I've triggered new build https://github.com/rcmaehl/WhyNotWin11/actions/runs/11263682084/artifacts/2037455992

**Comment by PicoMitchell** [comment]
When trying to do `/export` with that build, I'm just getting a windows that says only "0" and an "OK" button, and I get no exported file at the specified path.

**Comment by rcmaehl** [comment]
> When trying to do `/export CSV [PATH] /silent /force` with that build, I'm just getting an alert window that says only "0" and an "OK" button, and I get no exported file at the specified path.

Gimme a sec

**Comment by PicoMitchell** [comment]
Correction, it IS outputting the file (I wasn't being patient enough), but the alert with "0" isn't great when I need to use it silently within a script.

**Comment by rcmaehl** [comment]
> Correction, it IS outputting the file (I wasn't being patient enough after closing the "0" alert which the output process seems to hang on), but the alert with "0" isn't great when I need to use it silently within a script.

https://github.com/rcmaehl/WhyNotWin11/actions/runs/11264180630/artifacts/2037598175

This has the dialog removed. Was fixing an edge case in which someone forgot the trailing \ in a directory

2.6.1.1 will be out soon. I actually have most of the code for #757, I just have to finish and commit it before releasing that.

**Comment by PicoMitchell** [comment]
Working perfectly now. Thank you so much for the quick fix!
