### ISSUE TITLE
WinPE and Skip Parameter returns 1

### ISSUE THREAD

**Issue by stephannn** [rcmaehl/WhyNotWin11#758]
Hi,

using following code on WinPE:
`powershell -command "EXIT (Start-Process -FilePath WhyNotWin11.exe -ArgumentList """/s /skip DirectX,Disk,Storage /f /e TXT $env:temp\WhyNotWin11_check.log""" -PassThru -Wait).ExitCode"`
does not return 0 even when the checks in the log file return all true. In the GUI you can see that all checks passed, except the skip ones.

Running same code on a running Windows 11 works fine, but also everything is present.

I am not very familiar with au3, but the only return 1 line I could find is:
`If $aResults[$iLoop][0] = False Or $aResults[$iLoop][0] < 1 Then Exit 1`

Btw.: I also tried version 2.6.1.1

Thanks
Stephan

**Comment by rcmaehl** [comment]
Yep. I'll get this fixed!
