### ISSUE TITLE
Please migrate the checksum-files to the standard checksum.sha256

### ISSUE THREAD

**Issue by skyteddy** [rcmaehl/WhyNotWin11#81]
Hello Robert,

thank you very much for your great tool! 

I would have a small wish:

Especially because you continuously release new versions of your great tool, it would be nice if you replace your two proprietary checksum files shasum64.txt and shasum86.txt with the standard checksum file checksums.sha256. This makes it easier to check the checksums with different tools.

There are several tools for both generation and verification. I like the following HashCheck, because its small and smooth integrated in Windows:
https://github.com/idrassi/HashCheck

Or even a fork of it:
https://github.com/namazso/OpenHashTab

Or many other checksum-tools.

Both tools generate a file, e.g. checksums.sha256, in the following format. My example for your version v2.2.2:

790a7a3f19625c3dd9e598e38e1920a5862d2490851e8332d48f8d6a98ae72cc *WhyNotWin11.exe
a7479b6b2c62c1544de95e2c5fd70d3b5cad894cc3637e40abcab55f9df594f6 *WhyNotWin11_x86.exe
23b2296cb7d3348200e088abdfa81c04bf2c15780fc648462d44016e1eb4b9ca *SupportedProcessorsAMD.txt
488a41fc329a43380f220ceb0914a23c160472b4f680211dbc6d7eb1adc1dc5d *SupportedProcessorsIntel.txt
3e912be5780387d2ecae6b918448612f264739eb23905058a4967e7cd0d30309 *SupportedProcessorsQualcomm.txt
a88e1d9ddbf35d89d1a41271be7a87f4387c2034e2d19347f6874ec8e1431514 *2.2.2.zip
23e367e1f5dc40120ec174945eebd48f143899ffee83738d18732f9c1072be88 *2.2.2.tar.gz

How to create the checksum.sha256:
- install the HashCheck
- select the files to generate checksums
- right mouse button -> properties -> Checksums
- save as: checksum.sha256
-> that's it :)

To verify if the checksums are correct:
- double click on the checksums.sha256
-> a windows opens with the the compare of given and generated checksums.

Hope that helps

many thanks in advance!
skyteddy

**Comment by micwoj92** [comment]
Do these tools have command line options?

**Comment by skyteddy** [comment]
> Do these tools have command line options?

As far as I know not, but there exists a lot of command line checksum-tools. Also powerhell has a function for this.

**Comment by micwoj92** [comment]
Currently powershell is being used, so it's probably just matter of formatting + outputting to different file.

https://github.com/rcmaehl/WhyNotWin11/blob/46a5b0e1ca135698ee300d7341b28979c7825394/.github/workflows/wnw11.yml#L29

**Comment by skyteddy** [comment]
Ok, so it's very easy to put alle the checksums in one checksums.sha256

Please do not use a text-file for the output. checksums.sha256 or checksums.sha512 or whatever make it easy to check.

thanks

**Comment by micwoj92** [comment]
Hello @skyteddy could you files from this artifact if this is right?
https://github.com/micwoj92/WhyNotWin11/actions/runs/976981957

**Comment by skyteddy** [comment]
Hello micwoj92,

thank you very much for your quick reply. It works perfectly!

![Checksum-Result](https://user-images.githubusercontent.com/13059236/123573613-93552e00-d7ce-11eb-99c7-03268723c94a.png)

Are the two exe files the only files in the future that will be published? You can add all files in the checksum-file.

many thanks!

ps: What is the better/correct name? checksum.sha256 or checksums.sha256 (with "s" at the end)?

**Comment by micwoj92** [comment]
> Are the two exe files the only files in the future that will be published? You can add all files in the checksum-file.

CPU lists also will be published, but I don't think that it's needed as they are just text files.

> ps: What is the better/correct name? checksum.sha256 or checksums.sha256 (with "s" at the end)?

I don't know, but if checksum.sha256 works, then I will leave it at that.

**Comment by skyteddy** [comment]
> > Are the two exe files the only files in the future that will be published? You can add all files in the checksum-file.
> 
> CPU lists also will be published, but I don't think that it's needed as they are just text files.

If anything going wrong during download (e.g. wrong coding, ...) , checksum help here to find a problem too.



> > ps: What is the better/correct name? checksum.sha256 or checksums.sha256 (with "s" at the end)?
> 
> I don't know, but if checksum.sha256 works, then I will leave it at that.

If the file contains more than one checksum, I would prefer checksums (with s) since it is the plural.
It works, because the file extension is ".sha256", the name before is unimportant.

**Comment by micwoj92** [comment]
Okay, I've renamed the file. I will add checksums to cpu file lists later.

**Comment by skyteddy** [comment]
micwoj92, thank you very much for your patience and good work!
