### ISSUE TITLE
Crash When Launch

### ISSUE THREAD

**Issue by RocketNinja15** [rcmaehl/WhyNotWin11#82]
I downloaded it, but when I get to CPU, it says...
![image](https://user-images.githubusercontent.com/50027436/123558688-7841da00-d74c-11eb-818e-bbf0f1679214.png)

**Comment by micwoj92** [comment]
Could you check latest CI build?

**Comment by rcmaehl** [comment]
Duplicate of #63

**Comment by billysielu** [comment]
I think you need
`#include <StringConstants.au3>`
for `$STR_NOCOUNT` 
https://www.autoitscript.com/autoit3/docs/functions/StringSplit.htm

**Comment by RocketNinja15** [comment]
> Could you check latest CI build?
> https://github.com/rcmaehl/WhyNotWin11/actions/runs/976897310

I will soon, when I get back to my PC

**Comment by rcmaehl** [comment]
No Additional Reports. Closing due to age
