### ISSUE TITLE
Long CPU names extend to 3 lines, cutting off the bottom

### ISSUE THREAD

**Issue by ajax146** [rcmaehl/WhyNotWin11#88]
![Bug](https://user-images.githubusercontent.com/31014239/123569850-a3611380-d7b6-11eb-874b-81b9c099d413.png)

Using dev build #104

CPU is Intel(R) Core(TM) i7-1065G7 CPU @ 1.30 GHz

**Comment by rcmaehl** [comment]
"Fixed" in 64046a57b145bc02173ab062bca891bb44d19796
