### ISSUE TITLE
Is WhyNotWin11 Portable?

### ISSUE THREAD

**Issue by Gitoffthelawn** [rcmaehl/WhyNotWin11#90]
I've been asked to recommend an application like this, so I'm going to review the source code soon.  In the meantime, can you answer a couple questions?

1. Is the tool portable?  *"Portable"* meaning no writing anywhere outside of files in the folder containing the application, and no writing to the Windows registry.
2. Does anything that the application calls result in files/folders/registry/other changing?
3. Does the tool use the internet or local networks for anything?

Of course, since this runs on Windows, you can ignore the obvious exceptions like an MUI cache registry change or `prefetch` file change.

Thanks!

**Comment by rcmaehl** [comment]
Depends on who's definition of portable you're looking for. There's no setup, config files that need to be saved, etc. It does generate some files but 

1. %temp% is currently used to extract supported CPU Lists and Powershell output. There is no issue with those files being left behind. No first time setup, or any other conflicts. However, this will be changing to %localappdata%\WhyNotWin11 with upcoming translation additions. I'd rather not extract 4-5 files in the same folder as the application as people like to just drop it on their desktop.

2. Nay

3. Nope

If WhyNotWin11 has to meet the more strict requirements of using the same folder as the executable, please plead your case, but I think anyone reasonable would consider the application portable as is.

**Comment by rcmaehl** [comment]
Correction added to 3

**Comment by Gitoffthelawn** [comment]
Thanks for your answers.

> Depends on who's definition of portable you're looking for.

LOL.  That's exactly why I defined *"portable"*.

> There's no setup, config files that need to be saved, etc. It does generate some files but nothing it needs between systems

Thanks.  I'm more concerned about cleanup than files needed between systems.

>     1. %temp% is currently used to extract supported CPU Lists and Powershell output. There is no issue with those files being left behind. No first time setup, or any other conflicts. However, this will be changing to %localappdata%\WhyNotWin11 with upcoming translation additions. 

Using `%temp%` is fine by me (and actually preferred to `%localappdata%`).  Not portable, but easy to clean up without hunting for leftovers.

> I'd rather not extract 4-5 files in the same folder as the application as people like to just drop it on their desktop.

Some people still run applications from their desktops?  Oh dear.

>     2. Nay

Great.  That was my biggest concern.

>     3. For checking for updates, yes. Social links use ShellExecute

Are update checks disabled by default or does it just venture onto the interwebs on its own?  Either way, does it correctly handle being blocked?
 
> If WhyNotWin11 has to meet the more strict requirements of using the same folder as the executable, please plead your case, but I think anyone reasonable would consider the application portable as is.

I have no problem with it writing to `%temp%`, but I doubt you'll be able to convince most people that it's portable.  Writing outside of its own folder, by definition, means its not truly portable.  But I can fix that minor issue in 10-15 seconds, so no problem by me.

Just for giggles, my brain suddenly started imagining you pleading your case with a law enforcement officer... "Sir, I didn't drink any beer, so no reasonable person would consider me drunk.... just please ignore the pungent fumes of tequila wafting from my mouth and the empty bottle of El Padrino in my hand." 😄

**Comment by rcmaehl** [comment]
> Are update checks disabled by default or does it just venture onto the interwebs on its own? Either way, does it correctly handle being blocked?

Update checks have to be done manually by clicking "Check for Updates", it should fail gracefully with a message saying it failed to check if there's no internet.

**Comment by Gitoffthelawn** [comment]
> > Are update checks disabled by default or does it just venture onto the interwebs on its own? Either way, does it correctly handle being blocked?
> 
> Update checks have to be done manually by clicking "Check for Updates", it should fail gracefully with a message saying it failed to check if there's no internet.

Thanks.  What you describe is ideal.

**Comment by rcmaehl** [comment]
> > > Are update checks disabled by default or does it just venture onto the interwebs on its own? Either way, does it correctly handle being blocked?
> > 
> > 
> > Update checks have to be done manually by clicking "Check for Updates", it should fail gracefully with a message saying it failed to check if there's no internet.
> 
> Thanks. What you describe is ideal.

If you don't mind, may I ask what you're doing with it? ,paf.exe? SCCM Deployment?

**Comment by Gitoffthelawn** [comment]
> If you don't mind, may I ask what you're doing with it? ,paf.exe? SCCM Deployment?

I don't mind at all, especially considering that you have been very helpful to me and have also generously published the source code you have written.  Plus, questions are free. :)

For better or worse, I am the person that many (too many, IMO) people/businesses/charities look to for learning what software to use for particular tasks.  Part of the reason is that, for open source software, I actually go through all the source code and also compile/assemble/build the executable(s) myself.  Over time, I've learned to ask the developers of each application a few essential questions before I invest the time required to analyze all the code.

**Comment by Gitoffthelawn** [comment]
> Well AutoIt is generally very human readable, so hopefully there shouldn't be much issues analyzing it, but if you have any questions let me know!

Thank you.  Yes, it's very readable... plus, I no longer remember exactly why, but I learned AutoIt when it was first released years ago.  It's a rather fun tool for which to write code.

As an aside, one reason why I chose your project as a potential recommendation is because the UI is well done.  Good job!

**Comment by Gitoffthelawn** [comment]
I'm going to close this now because all questions are answered.  Feel free to re-open if there is a need.
