### ISSUE TITLE
Add a UI line regarding system Linux compatibility

### ISSUE THREAD

**Issue by Gitoffthelawn** [rcmaehl/WhyNotWin11#91]
You can likely generate many smiles (and much awareness) if you add a line in the UI that indicates whether or not 99% of Linux distributions will be portable with the system's hardware. :)

**Comment by micwoj92** [comment]
Could you specify what you mean by "Linux distributions will be portable with the system's hardware"?

**Comment by Gitoffthelawn** [comment]
@micwoj92 Yes, I just mean a line that says "System compatible with most Linux distros" with a yes/no indicator.  The reason being threefold:

1. To subtly (and a bit humorously) point out how ridiculous and arbitrary Microsoft's requirements for Windows 11 are.  Almost all of the requirements are not truly needed for a quality OS to operate, even if MS is requiring them for Windows 11.  macOS doesn't even have such requirements, and Apple runs a closed shop catering to what many consider to be an elite and wealthy audience.
2. To provide awareness that fully supported operating systems ***are*** available that support the user's hardware.
3. To possibly help prevent the unneeded massive electronics waste (which is often toxic to the watershed) caused by people needlessly buying new hardware when their are excellent OS options for their hardware available.

BTW, I'm not anti-MS (I use Windows at least 30% of the time when I'm using a computing device), I'm just *pro-honesty* and *pro-full-disclosure*.

**Comment by micwoj92** [comment]
I mean, currently there is "easter egg" when running on Wine, so another "humorous" addition wouldn't hurt imo. But as I already said, I have no power here.

**Comment by rcmaehl** [comment]
> I mean, currently there is "easter egg" when running on Wine, so another "humorous" addition wouldn't hurt imo. But as I already said, I have no power here.

You are literally collaborator. I've been considering adding text along the lines of

"You're running a Windows Program on Linux, WHY!? It won't work right!" 
"Windows 7 isn't supported and neither are you"

But that's more along the lines of frustrations and not actually helpful.

**Comment by micwoj92** [comment]
> > I mean, currently there is "easter egg" when running on Wine, so another "humorous" addition wouldn't hurt imo. But as I already said, I have no power here.
> 
> You are literally collaborator. 

I meant more that you probably wouldn't be happy if I did some serious change without your consent.

**Comment by rcmaehl** [comment]
I'll add in something similar with item descriptions, but I'm going to close this out for now.
